### ISSUE TITLE
Could not find class

### ISSUE THREAD

**Issue by NARKOZ** [coursera-dl/coursera-dl#109]
```
./coursera-dl -u **** -p ***** guitar
Downloading class: guitar
Could not find class: guitar
```

**Comment by DuinoDu** [comment]
So how can I find the current version of the class? e.g. https://www.coursera.org/learn/teaching

**Comment by balta2ar** [comment]
There are no more versions in on-demand classes on Coursera.

**Comment by DuinoDu** [comment]
"coursera-dl -u *** -p *** -d *** teaching" still throws exception: Unknown class teaching. So where can I find the correct class name?

**Comment by balta2ar** [comment]
pip version is out of date. Use version from github.

**Comment by DuinoDu** [comment]
Thanks~
