### ISSUE TITLE
Issue with using coursera-dl

### ISSUE THREAD

**Issue by hariiyer16** [coursera-dl/coursera-dl#129]
I just installed the coursera downloader as follows:

sudo port install py-beautifulsoup
sudo port install py-argparse
sudo port install py-setuptools

When I ra "install py24-distribute", I had an error saying I should use "install py-setuptools".  So I used the latter.  The installation seemed fine.

But when I run "coursera-dl -u" in my terminal, I get the error:
-bash: coursera-dl: command not found

I would really appreciate help with getting this running.  I am using a Mac OSX (Snow leopard)

Best
Hari

**Comment by akm24136** [comment]
they says to me open terminal i have no terminal how can i have terminal olease tell me
from where i can get the terminal
