### ISSUE TITLE
Videos are not downloaded from full course contents

### ISSUE THREAD

**Issue by altmas5** [coursera-dl/coursera-dl#195]
Hello Folks,

I am trying to download the crypto-2012-002 course using:
```/coursera-dl -u me@mail.com -p myPass crypto-2012-002```
and it downloads srt, pdf, pptx and txt files but the videos are not found by the script and finally gets a 403 response:
```Downloading: crypto-2012-002/01_Introduction/01_Course_Overview.mp4
Downloading https://class.coursera.org/crypto-2012-002/lecture/download.mp4?lecture_id=1 -> crypto-2012-002/01_Introduction/01_Course_Overview.mp4
Starting new HTTPS connection (1): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 2 seconds ...
Starting new HTTPS connection (2): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 4 seconds ...
Starting new HTTPS connection (3): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 8 seconds ...
Starting new HTTPS connection (4): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 16 seconds ...
Starting new HTTPS connection (5): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 32 seconds ...
Skipping, can't download file ...
Forbidden 403
Downloading: crypto-2012-002/01_Introduction/01_Course_Overview.txt```

I am using the latest version of the script. (I have just cloned the repo)
I am using openSuSE 12.2
Any ideas on what could be happening? It looks like it's related to coursera's CDN
Thank you in advance

**Comment by victorwestmann** [comment]
Hi @altmas5 how do you do? Just trying to help here... were you able to solve your issue? What is the complete course name and url? I'd like to give you guys a hand and restest this issue. :smile:

**Comment by rbrito** [comment]
@victorwestmann, no that's an older iteration of Cyrptography I (great course, BTW). I'm still waiting for Crypto II to see the light of the day, but it has been postponed since 2013, as I believe that Dan Boneh may have his hands busy.

Back to the issue, things have changed so much (both wrt our code and on Coursera's side) that I think that we should close this issue. If it is still relevant, do not hesitate to open another ticket.

Thanks.
