### ISSUE TITLE
What is the username?

### ISSUE THREAD

**Issue by karambir** [coursera-dl/coursera-dl#213]
Is it the email address I use to login in coursera or the long string which coursera gives to every user(mine is something like 0f084b7d7cce109d4............57 ) or something else?

I have tried both and they did not work. Please help

**Comment by tasnim2487** [comment]
when I run the command 
~/coursera-dl$ ./coursera-dl -u <email> -p <pass> class
terminal says,
bash: email:no such file/directory .
what can I do?

**Comment by Khun111** [comment]
Not working. Tried the options in this thread. Still doesn't work
