### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by cgmac** [coursera-dl/coursera-dl#216]
Hi,
I have the following error and I have tried to solve it to the very best of my knowledge, but I am stuck, could you please give some help?

OS: windows 7

Error:
 C:\Python27\coursera-master>coursera-dl help
Traceback (most recent call last):
  File "C:\Python27\coursera-master\coursera-dl", line 4, in <module> from coursera import coursera_dl
  File "C:\Python27\coursera-master\coursera\coursera_dl.py", line 56, in <module>
    import requests
ImportError: No module named requests

Thank you.

**Comment by sagar-m** [comment]
Hi, I hope its ok if I open this old issue, since I am facing the same problem about "requests" module. This [link](https://www.coursera.org/learn/bayesian-methods-in-machine-learning/discussions/weeks/4/threads/vMm30QWhEeiE9xKcLu8KBA) mentions to upload the assignment file and the grader and work, however, it is not working for me. 

And the installing dependencies [link](https://github.com/coursera-dl/coursera#install-any-missing-dependencies), that you have mentioned above, has a lot of information. Is there a specific part I should be looking at? Thank you very much.

```
ImportErrorTraceback (most recent call last)
<ipython-input-1-f9efcc288581> in <module>()
      5 from matplotlib import animation
      6 import pymc3 as pm
----> 7 from grader import Grader
      8 get_ipython().magic(u'pylab inline')

/home/jovyan/work/Week4/grader.py in <module>()
----> 1 import requests
      2 import json
      3 import numpy as np
      4 from collections import OrderedDict
      5 

ImportError: No module named requests
```

**Comment by balta2ar** [comment]
Just install requests library:
```
pip install requests
```
or
```
pip install --user requests
```
you may need to use pip3 instead of pip, depends on your system.

**Comment by balta2ar** [comment]
You must be executing this command in Jupyter notebook as a Python code. This isn't Python code, it's a shell command. You can still run it in Jupyter if you prepend "!":
```
!pip3 install --user requests
```

**Comment by sagar-m** [comment]
Hi @balta2ar the following does not make sense.

`!pip3 install --user requests`

```
Requirement already satisfied: requests in /opt/conda/lib/python3.6/site-packages
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests)
Requirement already satisfied: idna<2.8,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests)
```

```
import numpy as np
import pandas as pd
import numpy.random as rnd
import seaborn as sns
from matplotlib import animation
import pymc3 as pm
from grader import Grader
%pylab inline
```
```
ImportErrorTraceback (most recent call last)
<ipython-input-2-f9efcc288581> in <module>()
      5 from matplotlib import animation
      6 import pymc3 as pm
----> 7 from grader import Grader
      8 get_ipython().magic(u'pylab inline')

/home/jovyan/work/Week4/grader.py in <module>()
----> 1 import requests
      2 import json
      3 import numpy as np
      4 from collections import OrderedDict
      5 

ImportError: No module named requests
```

**Comment by ZurMaD** [comment]
> Hola @ balta2ar lo siguiente no tiene sentido. Gracias.
> 
> `!pip3 install --user requests`
> 
> ```
> Requirement already satisfied: requests in /opt/conda/lib/python3.6/site-packages
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests)
> Requirement already satisfied: idna<2.8,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests)
> Requirement already satisfied: urllib3<1.24,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests)
> Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests)
> ```
> ```
> import numpy as np
> import pandas as pd
> import numpy.random as rnd
> import seaborn as sns
> from matplotlib import animation
> import pymc3 as pm
> from grader import Grader
> %pylab inline
> ```
> ```
> WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named mkl
> 
> ImportErrorTraceback (most recent call last)
> <ipython-input-2-f9efcc288581> in <module>()
>       5 from matplotlib import animation
>       6 import pymc3 as pm
> ----> 7 from grader import Grader
>       8 get_ipython().magic(u'pylab inline')
> 
> /home/jovyan/work/Week4/grader.py in <module>()
> ----> 1 import requests
>       2 import json
>       3 import numpy as np
>       4 from collections import OrderedDict
>       5 
> 
> ImportError: No module named requests
> ```

Are you running with prompt or jupyter?

**Comment by sagar-m** [comment]
Hi, i am running it inside jupyter (in the same page as the assignments). Thank you.

**Comment by sagar-m** [comment]
Hi, I am using python 2.7 in jupyter. And I have both python2.7 and python3.6 (anaconda) installed in my mac. Requests is downloaded in 3.6 and when I access it from jupyter using python3.6, it is easily imported. How do I also install requests for python 2.7? Thank you.

**Comment by balta2ar** [comment]
Usually it's `pip2` instead of `pip` or `pip3`, but it depends on your system configuration. For example, anaconda, when installed, offers to add automatic initialization into `~/.bashrc` (or simialar) so that you have python3 by default in your shell.

**Comment by sagar-m** [comment]
Hi, do the below codes identify why I am getting an error? Thank you.

```
import numpy
numpy.__path__
['/opt/conda/envs/python2/lib/python2.7/site-packages/numpy']

!conda env list
pip is /opt/conda/bin/pip

import sys
sys.path

['',
 '/opt/conda/envs/python2/lib/python27.zip',
 '/opt/conda/envs/python2/lib/python2.7',
 '/opt/conda/envs/python2/lib/python2.7/plat-linux2',
 '/opt/conda/envs/python2/lib/python2.7/lib-tk',
 '/opt/conda/envs/python2/lib/python2.7/lib-old',
 '/opt/conda/envs/python2/lib/python2.7/lib-dynload',
 '/opt/conda/envs/python2/lib/python2.7/site-packages',
 '/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/extensions',
 '/home/jovyan/.ipython']

!conda install --yes --prefix {sys.prefix} requests
Solving environment: 
```
