### ISSUE TITLE
Long file name throws exception

### ISSUE THREAD

**Issue by karma0** [coursera-dl/coursera-dl#217]
When attempting to scrape the content for the class posa-001, the script exits with an error about the file name being too long.

I copy/pasted the attempted file name and tried to touch the file, and I received the same error, so it's definitely a limitation of the linux environment I'm using.  I'm on Ubuntu with an encrypted home directory (ecryptfs) and it isn't accepting file names bigger than a little over 140 characters.  The file name it's attempting and failing on is this one (about 150 characters): 

'downloads/posa-001/04_Section_3/24_W7-8_Patterns_and_Frameworks_for_Concurrency_and_Synchronization-_Part_8_0_Patterns_and_Frameworks_for_Concurrency_and_Synchronization-_Part_8.pdf'

I altered the format_resource and format_combined_number_resource functions in coursera_dl.py, forcing truncation of (lec)name and title if they're above a certain length.

**Comment by tpborion** [comment]
Did you find a good solution to that?

**Comment by seanf** [comment]
One workaround to allow longer path names is to use the `--path` option with a UNC pathname[1], by putting `\\?\` in front of the drive letter. For instance, to save files to the directory `d:\coursera`:

    coursera-dl -u <username> -p <password> --path \\?\d:\coursera <course-id>

[1] http://stackoverflow.com/a/18747460/14379

**Comment by seanf** [comment]
Ah, I see that this workaround was just used in https://github.com/coursera-dl/coursera-dl/commit/b282c3596170d6939bf1ff6916c5c38c53c6ebcd and released in 0.6.0. That's great!

@balta2ar Should this issue be closed then?

**Comment by balta2ar** [comment]
@seanf Sure! Thanks for noticing!

**Comment by GlowingCrystallineEntity** [comment]
The UNC pathname seems to work with the internal downloader, but it fails with, in particular, Aria2 (1.24.0).  It fails completely -- Aria2 can't download any of those files.  That was the suggested solution to #518, though.

That's probably really Aria2's problem -- but I don't know if they'd be able/willing to fix it....

(... and... it looks like there are other issues (it seems to create login timeouts) with those 63 second delays on failed downloads with the internal downloader, but that's for a different issue....)
