### ISSUE TITLE
Question: How to download subtitle files of a course preview

### ISSUE THREAD

**Issue by javiqm12** [coursera-dl/coursera-dl#237]
The command
coursera-dl -n -b cplusplus4c-002
downloaded nicely the videos in the preview but did not catch the subtitles.
Is there a way to download the subtitles as well. Thanks

**Comment by flyafly** [comment]
+1 ,I need the preview video's subtitle too

**Comment by balta2ar** [comment]
Not actual anymore. Old courses are not supported.
