### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by levibotelho** [coursera-dl/coursera-dl#241]
I'm getting this error directly when trying to run the script. No content is downloaded. The last output I have before the error is as follows.

```
Starting new HTTPS connection (1): class.coursera.org
```

I'm running on Windows 7, with Python 3.4. I installed all dependencies using pip. These are the versions I have.

```
beautifulsoup4==4.1.3 in c:\python34\lib\site-packages (from -r requirements.txt (line 1))
coverage==3.7 in c:\python34\lib\site-packages (from -r requirements.txt (line 2))
html5lib==1.0b2 in c:\python34\lib\site-packages (from -r requirements.txt (line 3))
nose==1.3.0 in c:\python34\lib\site-packages (from -r requirements.txt (line 4))
requests==1.2.3 in c:\python34\lib\site-packages (from -r requirements.txt (line 5))
six==1.3.0 in c:\python34\lib\site-packages (from -r requirements.txt (line 6))
```

**Comment by hiepxanh** [comment]
uninstall requests and install again, it worked with me

**Comment by 7Anant** [comment]
I am having a similar issue
on the below code
{
import requests
from bs4 import BeautifulSoup

page = requests.get("http://dataquestio.github.io/web-scraping-pages/simple.html")
soup = BeautifulSoup(page.content, 'html.parser')
print(soup.prettify())
}

I am gettign the following error message

{
Traceback (most recent call last):
  File "C:/Users/anant/PycharmProjects/proj/requests1.py", line 6, in <module>
    soup = BeautifulSoup(page.content, 'html.parser')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\bs4\__init__.py", line 153, in __init__
    builder = builder_class()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\bs4\builder\_htmlparser.py", line 39, in __init__
    return super(HTMLParserTreeBuilder, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'strict'}

I have also tried updating my requests package and it still doesn't get fixed

**Comment by rbrito** [comment]
@7Anant, please open another issue with your problem, with more details. This was closed 4 years ago and I can't even remember the details of this case...
