### ISSUE TITLE
single item from course content is not fetched

### ISSUE THREAD

**Issue by silpol** [coursera-dl/coursera-dl#293]
/usr/local/bin/coursera-dl -> coursera-dl==3.0.0

fetching content causes some error messages
--8<--
Course 1 of 1
* Collecting downloadable content from https://class.coursera.org/growtogreatness-003/lecture/index
* Got all downloadable content for growtogreatness-003
* growtogreatness-003 will be downloaded to /home/silpol/coursera/growtogreatness-003
 - Downloading lecture/syllabus pages
Warning: failed to download about file HTTP Error 400: Bad Request

--8<--

and then later few items goes missing, and it is not clear whether this is result of first error or just content is not available via HTTP due to failures at Coursera.org

e.g. like this 
--8<--
  - Downloading resources for Week 3 Lesson 7 (Defender Direct interview) (14.14)
    - failed:  https://class.coursera.org/growtogreatness-003/lecture/subtitles?q=43_en&format=srt <urlopen error [Errno -2] Name or service not known>
    - "3 - 7 - Week 3 Lesson 7 (Defender Direct interview) (14.14).mp4" already exists, skipping
--8<--

I check them with curl and see stuff like this (URL material seem to be HTTP 200 Ok)
--8<--
silpol@hostname:~/coursera$ curl -I "https://class.coursera.org/growtogreatness-003/lecture/subtitles?q=43_en&format=srt"
HTTP/1.1 200 OK
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Disposition: attachment; filename="3%20-%207%20-%20Week%203%20Lesson%207%20%28Defender%20Direct%20interview%29%20%2814.14%29.srt"; filename*=UTF-8''3%20-%207%20-%20Week%203%20Lesson%207%20%28Defender%20Direct%20interview%29%20%2814.14%29.srt
Content-length: 0
Content-Type: application/force-download
Date: Wed, 03 Dec 2014 17:17:57 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: nginx
Set-Cookie: __204u=5640019888-1417627077017; Expires=Thu, 03 Dec 2015 18:17:57 CET; Path=/; Domain=.coursera.org
Set-Cookie: csrf_token=wSetNPGqnK1h6H7xAnvK; Expires=Fri, 02 Jan 2015 18:17:57 CET; Path=/growtogreatness-003
Strict-Transport-Security: max-age=31536000
X-Coursera-Request-Id: UwAoq3sQEeSyiSIACxMGlw
X-Frame-Options: SAMEORIGIN
Connection: keep-alive

--8<--

I re-run again and again until no error messages apart from that top one - it is 100% repeatable

so
1) what should I do about 1st item?
2) should I trust script it had downloaded items done not from 1st time but from 2nd or N+1? Or should I check manually? Is there way to be more precise/explicit about it?

**Comment by rbrito** [comment]
Hi.

This is a bug in a project that is *not* ours, but that has the same name. Yes, we know that it is confusing. You are, OTOH, welcome to use our project, as it keeps getting better and better.

Just uninstall the package that you installed with pip and install the one with the name `coursera` (note: **excluding** the `-dl` at the end).

After that, you can use the program to download everything that we support.


Hope this helps,

Rogério Brito.
