### ISSUE TITLE
Create tests for ondemand courses

### ISSUE THREAD

**Issue by rbrito** [coursera-dl/coursera-dl#319]
Given that we now have support for ondemand courses, we need some tests of their functionality.

This may be a good opportunity to employ what pytest has to offer, BTW, as suggested by the kind members of our community.

**Comment by victorwestmann** [comment]
I`d like to help. Could you please provide instructions on how to start? :smile:

**Comment by rbrito** [comment]
I believe that the best place to start would be to see what tests we have so far. One of our easiest modules to understand is the `utils` module:

https://github.com/coursera-dl/coursera-dl/blob/master/coursera/utils.py

The corresponding tests are:

https://github.com/coursera-dl/coursera-dl/blob/master/coursera/test/test_utils.py

Perhaps it is best to skip the first tests above (since they contain some pytest annotations), but the rest (say, from `test_fix_url_adds_scheme`) should be pretty self-explanatory.

Actually, adding more tests (any kind of test) that improves our test coverage (see https://coveralls.io/github/coursera-dl/coursera or https://codeclimate.com/github/coursera-dl/coursera) would be *great*.

Thanks.

**Comment by balta2ar** [comment]
There are some tests already and more are added as needed. No reason to keep this ticket open, I think. Closing.
