### ISSUE TITLE
requirements cannot be installed

### ISSUE THREAD

**Issue by Make42** [coursera-dl/coursera-dl#357]
Again in my Kubuntu 14.4... what's up with this new error?

      :~$ git clone https://github.com/coursera-dl/coursera.git
      :~$ python --version
      Python 2.7.6
      :~$ pip --version
      pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
      :~$ cd coursera
      :~/coursera$ pip install requirements.txt 
      Downloading/unpacking requirements.txt
        Could not find any downloads that satisfy the requirement requirements.txt
      Cleaning up...
      No distributions at all found for requirements.txt
      Storing debug log for failure in /home/raeg/.pip/pip.log

PS: I had been using coursera-dl for ages (at least it felt like that) without any issues, but recently I have new issues every time I try to use it again. I love coursera-dl and appreciate all the hard work! I would love to see it work seamlessly again! Keep up the good work.

**Comment by azarudeen90** [comment]
@Make42 Try upgrade to 2.7.9  it resolved my issue and also add - r option to pip otherwise pip won't know to parse the info in the file

**Comment by Make42** [comment]
2.7.9 is not in the repositories - how do I upgrade?

**Comment by azarudeen90** [comment]
Download the tarball and install from the web.  

did you try using the -r option to pip??  go through the readme marddown please

**Comment by Make42** [comment]
By now I have been using a different angle:

      $ pip install coursera

Which gets the installation done.
However now I get a different error when trying to download:

:~$ coursera-dl -u my@example.com -p mypassword procmin-002
Downloading class: procmin-002
Starting new HTTPS connection (1): class.coursera.org
/home/user/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Starting new HTTPS connection (1): www.coursera.org
/home/user/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/home/user/.local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.0.3', 'console_scripts', 'coursera-dl')()
  File "/home/user/.local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 944, in main
    result = download_class(args, class_name)
  File "/home/user/.local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 842, in download_class
    username=args.username, password=args.password)
  File "/home/user/.local/lib/python2.7/site-packages/coursera/cookies.py", line 337, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/home/user/.local/lib/python2.7/site-packages/coursera/cookies.py", line 160, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "/home/user/.local/lib/python2.7/site-packages/coursera/cookies.py", line 115, in login
    headers=headers, allow_redirects=False)
  File "/home/user/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

**Comment by azarudeen90** [comment]
add the o/p of pip show. I faced the same issue because of the pyOpenSSL package. It needs to be updated. Once i updated to Python 2.7.9 my issue got resolved. You better checkitout

**Comment by rbrito** [comment]
On May 14 2015, Make42 wrote:
> By now I have been using a different angle:
> 
>       $ pip install coursera
> 
> Which gets the installation done.

Great!

> However now I get a different error when trying to download:
(...)
>   File "/home/user/.local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

This is likely a problem with OpenSSL and the fact that things have been
changing in the SSL/TLS world (e.g., SSLv3 is disabled now in many sites).

Please, let me know if installing the package `ndg-httpsclient` with pip
helps with the current situation.  It will download pyOpenSSL as a
dependency and pyOpenSSL will require compilation of some C code.

As you told us that you are using Kubuntu, I guess that the following recipe
would make things closer to work (and I hope that they work):

```
sudo apt-get install build-essentiall python-dev libssl-dev libffi-dev
pip install ndg-httpsclient
```

After that, please let me know you can download your courses or not. If it
works, then I guess that we should include those instructions in our
README.md file.

Oh, BTW, don't forget to install any security updates in your *buntu system
before that `apt-get install`.  It may very well have updates to openssl and
python that need to be installed before doing anything else.


Regards,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment]
Hi.
On May 14 2015, Make42 wrote:
(...)
>       :~/coursera$ pip install requirements.txt 

You forgot to put `-r` in front of requirements.txt

But this shouldn't be necessary anymore. Just do

        pip install coursera

and it will download the latest version that I released to PyPI and pull in
all the requirements.

> PS: I had been using coursera-dl for ages (at least it felt like that)
> without any issues, but recently I have new issues every time I try to use
> it again. I love coursera-dl and appreciate all the hard work!
> I would love to see it work seamlessly again! Keep up the good work.

Thanks a lot. I love that kind of feedback, which is what motivates me to
keep on going with the project. Right now, the project is essentially only a
one-person-show, but I would love to have more assistance from the
community.


Thanks again,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by Make42** [comment]
> add the o/p of pip show.
I don't know what that means. Could you provide a command line command?
> Once i updated to Python 2.7.9 my issue got resolved. You better checkitout. 
I am not sure whether installing Python 2.7.9 from outside a repository is a good idea. Maybe a virtualenvironment-solution might be the way to go for me. However, I don't know how to do this. Could I get a explanation... for dummies. (Like a list of command line commands.)

      :~$ sudo apt-get install build-essential python-dev libssl-dev libffi-dev
      ...
      :~$ sudo apt-get update
      :~$ sudo apt-get upgrade
      :~$ pip install ndg-httpsclient
      Traceback (most recent call last):
        File "/usr/bin/pip", line 9, in <module>
          load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
        File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
          return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
          return ep.load()
        File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
          entry = __import__(self.module_name, globals(),globals(), ['__name__'])
        File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 61, in <module>
          from pip.vcs import git, mercurial, subversion, bazaar  # noqa
        File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
          from pip.download import
      path_to_url
      File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
      from requests.compat import IncompleteRead
      ImportError: cannot import name IncompleteRead

What now?

**Comment by rbrito** [comment]
@Make42, Is this still relevant? Can we close this bug?

**Comment by rbrito** [comment]
I'm closing this bug. If it is still relevant, please comment on it or open another issue.

Thanks a lot.
