### ISSUE TITLE
We need a logo for the project

### ISSUE THREAD

**Issue by rbrito** [coursera-dl/coursera-dl#358]
It would be awesome if we had a logo for the project, so that we can substitute our non-informative "picture" at https://github.com/coursera-dl with a nicer, more informative logo that would get pulled from social networks like LinkedIn, Google+, Twitter, Facebook etc.

Can anybody contribute something that is compatible with our license? (Our license is at: https://github.com/coursera-dl/coursera/blob/master/LICENSE).

Thanks.

**Comment by victorwestmann** [comment]
Hi rbrito. I tried to address this issue in the following item: https://github.com/coursera-dl/coursera-dl/issues/394

Regards.

**Comment by rbrito** [comment]
Thanks, @victorwestmann. Fixed with https://github.com/coursera-dl/coursera-dl/commit/03b6b8f2669a1bb5255478b3934137629f12e46a
