### ISSUE TITLE
Feature request - support for udemy courses

### ISSUE THREAD

**Issue by madmax2** [coursera-dl/coursera-dl#362]
Can you add feature to download udemy course...with all course materials?

Or support automatically download of PDF handouts, course materials for udemy-dl

**Comment by rbrito** [comment]
Hi, @madmax2.

I believe that supporting Udemy is currently out-of-scope of this program.

If you happen to know of a project that works for Udemy *and* that project is willing to join us (or, perhaps, be hosted under the https://github.com/coursera-dl umbrella, just like we had with edx-dl, now hosted at https://github.com/coursera-dl/edx-dl).

We may even change the name of the organization to `mooc-dl` in the future to accomodate the diversity of scope of our project.

Thanks for your request,

Rogério Brito.
