### ISSUE TITLE
Login to coursera using Google+ is failing.

### ISSUE THREAD

**Issue by msj2** [coursera-dl/coursera-dl#363]
Hi Rogério, I login to coursera using Google+....
When I run coursera-dl in command prompt giving my google+ userid & passwd, I get error

"requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure"

I tried 2 options..

1)  coursera-dl https://www.udemy.com/abap-objects/ -u <gmail email id>
and enter the gmail password
2)  coursera-dl https://www.udemy.com/abap-objects/ -u <User ID>
and enter the gmail password

Can you help?

**Comment by azarudeen90** [comment]
hey you are using udemy urls. Please read the Readme.md file

**Comment by azarudeen90** [comment]
for udemy please use udemy-dl
