### ISSUE TITLE
Does coursera-dl supports download quiz contents, final exams and exercises?

### ISSUE THREAD

**Issue by madushan1000** [coursera-dl/coursera-dl#364]
Some courses have interactive exercises in the middle of the video, course notes, quizzes and past exam papers. Is the functionality for downloading these already implemented?

**Comment by mxamin** [comment]
Can you give us some examples?

**Comment by madushan1000** [comment]
For example this lecture video (https://class.coursera.org/intrologic-004/lecture/3 ) has an interactive exercise at 3:14. 
And this course (https://class.coursera.org/logic2-002) has course notes section and a homework quiz section.

**Comment by balta2ar** [comment]
Not sure about in-video quizzes, regular quizzes and exams, but related materials and assignment pages are very valuable. Sometimes they contain description and steps for implementations. I definitely want this feature at least partially be implemented.

**Comment by balta2ar** [comment]
Possible duplicate of #356. Or at least related to.

**Comment by rbrito** [comment]
Thanks @balta2ar and others.

Yes, this issue is a duplicate of #356. I'm closing this then. Let's move the discussion there.

Thanks for all the feedback,

Rogério.
