### ISSUE TITLE
Provide a GUI for coursera-dl

### ISSUE THREAD

**Issue by rbrito** [coursera-dl/coursera-dl#367]
Here is a service that seems to offer a platform for users to help with translation of programs:

https://crowdin.com/

Is there any interest in this? In particular, this would allow users to see messages translated to their native languages, instead of forcing them to use English.

**Comment by victorwestmann** [comment]
I believe this is a very cool idea and it would, certainly, encourage users to use our app. And help spread the word on it. How can we make this happen? I could make the 1st tests in localizing this app into brazilian portuguese (ptBR).

Regards.

**Comment by rbrito** [comment]
I have changed my mind after discussing with @shk3 and @balta2ar on the same issue on edx-dl. I think that it would be better to have a GUI here.

I'm removing the easy-to-fix label, since this may involve substantial coding. *AFTER* we implement a GUI, then we may want to deal with internationalization, but not now.

**Comment by rbrito** [comment]
As this is a duplicate of #184, I'm closing it.

**Comment by shk3** [comment]
Thanks for all the efforts, @rbrito.
