### ISSUE TITLE
get video download link via program

### ISSUE THREAD

**Issue by redstoneleo** [coursera-dl/coursera-dl#372]
I want extract Coursera video download link via program(mainly Python) behind those links 

https://www.coursera.org/learn/human-computer-interaction/lecture/s4rFQ/the-interaction-design-specialization 

https://www.coursera.org/learn/calculus1/lecture/IYGhT/why-is-calculus-going-to-be-so-much-fun 

After red a lot of articles about this, still cannot find a way to extract the video download link via program, anyone can offer a step by step solution of extracting the video download link ? Thanks! 

 but the code is so complex in this project ,  so I dropped out.

**Comment by redstoneleo** [comment]
I know the two packages : BeautifulSoup and requests may help, I am also able to login in Coursera via requests, the difficulty is how to find out  the video download link from the page.

**Comment by rbrito** [comment]
Hi, @redstoneleo.

I don't quite understand the problem that you are trying to solve. Are you trying to duplicate the functions that our project has? Are you trying to learn how it works? You can try to read our code and send us more specific questions or, better yet, send pull requests refactoring the code into modules (with tests, please).

A good first step to contribute to our project (or to learn how things work) would be to see if you can clone the repository, install py.test and tox and run our test suite with tox.

Then you would gain a better understanding on how we organized things.

I'm closing this issue, but feel free to add some more information and we can, depending on the circumstances, reopen it.


Thanks,

Rogério Brito.
