### ISSUE TITLE
Download Self Paced Courses 

### ISSUE THREAD

**Issue by waheed8999** [coursera-dl/coursera-dl#379]
A new type of courses coursera supports which is a self paced which can't be downloaded using coursera-dl,  is there is a new update soon for this type?

**Comment by mxamin** [comment]
If by *self-paced* courses you mean *on-demand* courses, coursera-dl supports it already, the only thing you need to do is to add `--on-deman` option:
`coursera-dl -u <username> -p <password> --on-demand <course-name>`
there is also an introduction about these type of courses in README file, read it.

**Comment by waheed8999** [comment]
Yes --on-demand what i meant by self paced, thank you so much
