### ISSUE TITLE
Changed URL scheme, still works or not?

### ISSUE THREAD

**Issue by Geethebluesky** [coursera-dl/coursera-dl#380]
Hello! It looks like coursera has changed their URL scheme, for example a class that used to be accessible here:
https://class.coursera.org/career-002/

... now redirects here:
https://www.coursera.org/course/career

I'm not sure how to get coursera-dl to work with the above.

Thanks for any help!

**Comment by mxamin** [comment]
As far as I know, nothing has been changed. What is exactly the command you entered to download this course?

**Comment by Geethebluesky** [comment]
Sorry, I see I didn't explain myself properly, or maybe I'm not seeing
where the course code name is located now.

I'm currently enrolled in a specific class here:
https://www.coursera.org/learn/physiology

It doesn't seem to have a URL with any code, there are no links pointing
to/from "*class.coursera.org <http://class.coursera.org>"* for that class.

So how do I determine the code of the class with that new URL format?
Without it, I can't DL anything, correct?

Thanks.

**Comment by mxamin** [comment]
You can get full introduction  about courses or how to get the course code by reading the README file, but as you asked here, I will describe it for you:
First of all before you can start downloading a course, you **MUST** enroll to that course manually by visiting the course web page and click the *enroll* or *start* button (which ever you found on that page).
There is two type of courses, the first one called *Regular Courses* (this is the name I gave them) and *On-Demand Courses*. You can recognize each course type by looking at their page URL:
* Regular Courses: https://class.coursera.org/sdn1-001
* On-Demand Courses: https://www.coursera.org/learn/public-speaking
The code name of theses two courses are: `sdn1-001` and `public-speaking` respectively.
According to what type of courses you want to download, you can enter one of the following commands:
* `coursera-dl -u <username> -p <password> sdn1-001`
* `coursera-dl -u <username> -p <password> --on-demand public-speaking`

This was the quick introduction on how to download a course, as I mentioned earlier you can get more information on how to download different courses by reading the *README* file.

I hope it will solve your problem.

**Comment by NelsonMinar** [comment]
I was having the same problem downloading the machine-learning course at `https://www.coursera.org/learn/machine-learning`. I had no idea what an "on-demand" class was or that I was in one. Using the `--on-demand` flag works for me. If many users are confused it may be worth explaining it differently in the docs or maybe try to make the code guess which kind of class it is.

**Comment by mxamin** [comment]
Until now, I couldn't find a way to recognize the course type by looking at its code name only, but as coursera API improves, I hope they add this feature.
But about the doc, you are welcome to improve the doc in a way that a new user can understand it better, and post it as a *Pull Request*. This is an open project and everyone is welcome to contribute in its development.

**Comment by Geethebluesky** [comment]
Thank you for the extra info, I was also confused about which classes are
on-demand and which are not. Now everything works properly!

**Comment by rbrito** [comment]
@Geethebluesky,

If you want to help with our project, feel free to send a modification/patch to our README file, so that other people may not experience the difficulties that you had.

In fact, any contributions are welcome, BTW.

I'm closing this issue, but please *do* help us improve our documentation.

Thanks,

Rogério.
