### ISSUE TITLE
Unknown error with Anaconda's distribution

### ISSUE THREAD

**Issue by Smitty010** [coursera-dl/coursera-dl#381]
I recently changed my Python install to Anaconda.  I did the 'pip install coursera' and that seemed to work fine.  But, when I try to run coursera, I get:

 File "coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "C:\MyPrograms\Coursera\python\coursera\coursera_dl.py", line 781, in main
    if download_class(args, class_name):
  File "C:\MyPrograms\Coursera\python\coursera\coursera_dl.py", line 718, in download_class
    session = requests.Session()
  File "C:\MyPrograms\Coursera\python\lib\site-packages\requests\sessions.py", line 287, in __init__
    self.headers = default_headers()
  File "C:\MyPrograms\Coursera\python\lib\site-packages\requests\utils.py", line 563, in default_headers
    'User-Agent': default_user_agent(),
  File "C:\MyPrograms\Coursera\python\lib\site-packages\requests\utils.py", line 532, in default_user_agent
    _implementation = platform.python_implementation()
  File "C:\MyPrograms\Coursera\python\lib\platform.py", line 1458, in python_implementation
    return _sys_version()[0]
  File "C:\MyPrograms\Coursera\python\lib\platform.py", line 1423, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)]'

Has anyone seen this?  I've googled, but I'm not finding anything that seems to tell me what's wrong.

**Comment by rbrito** [comment]
I guess that this is a problem with the parsing of the version string. It was probably expecting to see only `2.7.10`, but got all that string.

Perhaps you should tell that to the continuum developers?

**Comment by rbrito** [comment]
@Smitty010,

Just for documentation purposes, what do you get if you open a python interpreter and type the following two commands:

```
import platform
platform._sys_version()
```

Here, I get:
```
('CPython', '3.4.3+', '', '', 'default', 'Jul 28 2015 13:17:50', 'GCC 4.9.3')
```
or, when I'm using python 2, I get:
```
('CPython', '2.7.10', '', '', 'default', 'Jul  1 2015 10:54:53', 'GCC 4.9.2')
```

**Comment by Smitty010** [comment]
('CPython', '2.7.10', '', '', 'default', 'May 28 2015 16:44:52', 'MSC v.1500 64
bit (AMD64)')

**Comment by rbrito** [comment]
and what about

platform.python_implementation()

?

**Comment by rbrito** [comment]
And
```
import sys
sys.version
```
?

And also
```
import platform
platform.python_version()
```

**Comment by Smitty010** [comment]
>>> import sys
>>> import platform
>>> platform.python_implementation()
'CPython'
>>> sys.version
'2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)]'
>>> platform.python_version()
'2.7.10'
>>> platform._sys_version()
('CPython', '2.7.10', '', '', 'default', 'May 28 2015 16:44:52', 'MSC v.1500 64bit (AMD64)')

**Comment by rbrito** [comment]
Gee, no idea what may be happening here. You may try to reproduce manually the code that is failing from the code in the `platform` module:
```
platform._sys_version_parser.match(sys.version)
```
If it doesn't print anything (that is, the result is `None`), then we have something fishy going on. Otherwise, If it returns an `_sre.SRE_Match object`, then the exception shouldn't be thrown in the first place (and we also have a fishy situation).

If you get an `_sre.SRE_Match object` as a result, then you can use
```
platform._sys_version_parser.match(sys.version).groups()
```
to see what would be used *past* the exception...

Anyway, I have no clue here other than a PATH/PYTHONPATH thing going on.

**Comment by balta2ar** [comment]
Is this related? https://github.com/ContinuumIO/anaconda-issues/issues/33

**Comment by rbrito** [comment]
@balta2ar, ah, thanks.

It seems that their code is slightly different from what I had and reading the code that I have at my disposal just led me to confusion.

Perhaps we can close this issue after putting some notes regarding compatibility on the README? @balta2ar, @Smitty010? Can any of you help?

**Comment by Smitty010** [comment]
I played with it some more.  I'm beginning to think that the issue was not totally deleting the old version of python when I upgraded to the Anaconda release.  At any rate, I've gotten it to work (no changes to the coursera-dl code).  I'm going to make this as closed.  Sorry.
