### ISSUE TITLE
New course format not downloadable

### ISSUE THREAD

**Issue by oponcea** [coursera-dl/coursera-dl#386]
It seems that 'Successful Negotiation: Essential Strategies and Skills!' at https://www.coursera.org/learn/negotiation-skills/home/welcome fails to download. The course itself is not hosted at class.coursera.org but at www.coursera.org.

**Comment by mxamin** [comment]
Use the `--on-demand` option:
`python coursera-dl -u <username> -p <password> --on-demand negotiation-skills`
please let me know if it solves your problem.

**Comment by rbrito** [comment]
@oponcea, I hope that the answer that @mxamin gave you solves your problem.

If you feel that our documentation (https://github.com/coursera-dl/coursera-dl/blob/master/README.md) could be improved, please send a pull request/suggestion and we will gladly take your observations into account, so as to make it more obvious.

**Comment by rbrito** [comment]
I tagged this as "more-info-needed" (@mxamin, if you see the tags, feel free to apply them to the bugs, as that would help a lot with our task).

I wonder why many people don't find the `--on-demand` option. I just sent a commit that tries to make this more obvious. Let's see its results.

But then, again, feel free to add tags/labels to the bug reports, as you see fit.

**Comment by mxamin** [comment]
Ok

**Comment by rbrito** [comment]
@oponcea, I believe that this can be closed now. If you still face problems, please let us know and don't be afraid to file another bug.

Thanks.

**Comment by oponcea** [comment]
Thx! it's working - sorry for my late reply, I missed github's notifications
