### ISSUE TITLE
Adding support for downloading slides?

### ISSUE THREAD

**Issue by laike9m** [coursera-dl/coursera-dl#388]
I think this feature is very appealing, as least I need it. What do you think?

**Comment by mxamin** [comment]
This feature is already included, can you point out the course you intend to download its slides. It can be a bug that needs to be fixed.

**Comment by laike9m** [comment]
Ah, that's good. I haven't tried coursera-dl. But I didn't see anyting about "downloading slides" in README, where can I find it? Or the default option is to download all resources including videos&slides?

**Comment by mxamin** [comment]
Ok, the default mode is to download all the course materials.

**Comment by laike9m** [comment]
Alright. Thank you.
