### ISSUE TITLE
Not every resource is downloaded for on-demand/new-style courses.

### ISSUE THREAD

**Issue by linpackzh** [coursera-dl/coursera-dl#391]
Hi, 

I can't download this course 'https://www.coursera.org/learn/financial-engineering-2/home/welcome',
I know URL isn't like 'https://class.coursera.org/<CLASS_NAME>/class/index', but how to solve it?

**Comment by balta2ar** [comment]
Did you try `--on-demand` option?

**Comment by rbrito** [comment]
Hi there. I'm back.

OK, we have to fix this somehow. This is, currently, the most frequently reported issue that we're facing. I guess that we need both documentation and some change of behavior in the program.

I'll be following up on the other bug, so that I can expose my thoughts.

Regards,

Rogério.

**Comment by linpackzh** [comment]
Thanks all of you. --on-demand option works! But it may work better since it doesn't download 'Lesson Materials', for example, financial-engineering-2.

**Comment by mxamin** [comment]
@linpackzh, what do you mean by course materials? do you mean assignments? or something else.

**Comment by linpackzh** [comment]
Yes, for example, PDF files from this link:
https://www.coursera.org/learn/financial-engineering-2/supplement/HAUq7/lesson-supplements

**Comment by mxamin** [comment]
Ok, this is new :), These are called **Assets** in *Coursera* language but I don't think they are hard to get. Needs more research

**Comment by linpackzh** [comment]
Thanks for your response!

**Comment by victorwestmann** [comment]
@rbrito So can this be closed? :smile:

**Comment by rbrito** [comment]
@mxamin, are they called assets? I just downloaded the syllabus in JSON form from coursera and this is what I get with `grep`:

```
grep "typeName" json-syllabus-000.json | sort -u
"typeName": "exam"
"typeName": "lecture"
"typeName": "supplement"
```

Of course, I fear that we don't want to follow links to exams (especially if they are timed!), but other resources may be what we want (if they are, say, in PDF format).

Alas, I really wish that Coursera kept the old-style courses, as they were easier, more explicit to parse, without multiple network invocations.

**Comment by mxamin** [comment]
Yes, that's correct, they are called *Assets* which in json file are named *supplement*.
I have downloaded a json sample about three weeks a ago but didn't have the time to work on them since.

**Comment by AhmedKamal** [comment]
F

**Comment by StevenMaude** [comment]
In case anyone hasn't noticed already, there are also **non-PDF** assets, e.g. additional course notes for the on-demand courses.

For instance, in [this course](https://www.coursera.org/learn/introcss/),

```json
              {
                "timeCommitment": 0,
                "slug": "syllabus",
                "content": {
                  "definition": {
                    "optional": true,
                    "assetId": "634J90O3EeWBRwonRzbMiw@7",
                    "assetTypeName": "cml"
                  },
                  "typeName": "supplement"
                },
                "name": "Syllabus",
                "id": "nK6Y8"
              },
```

If you retrieve the content of this resource, you get:

```
<co-content><heading level="1">Welcome</heading><text>Welcome to Introduction to CSS3.  CSS stands for Cascading Style Sheets, a method of styling your HTML documents with various colors, fonts, layouts, and spacing.  But that is just the beginning.  You can also do some "cool" stuff such as creating transitions or adding animations.   There are so many things you can do with CSS, that we focus on the following:</text><list bulletType="bullets"><li><text>Rules and syntax (how to write CSS code)</text></li><li><text>Simple styling (fonts, colors, borders)</text></li><li><text>More styling (background images and opacity)</text></li><li><text>Positioning - how to get the different parts of your page to go where you want them to go</text></li><li><text>Pseudo-classes - styling things that aren't even there!</text></li></list>...
```
(remaining content snipped)

This would need converting into some kind of suitable format.

Otherwise, the content gets rendered into actual HTML on the page as a single div, so potentially could be scraped from there.

```html
<div class="content" data-reactid=".0.1.1.1.$nK6Y8.0.2.0">
    <div class="rc-CMLPreview rc-Reading with-styles" data-reactid=
    ".0.1.1.1.$nK6Y8.0.2.0.0">
        <h1>Welcome</h1>
        <p>Welcome to Introduction to CSS3. CSS stands for Cascading Style
        Sheets, a method of styling your HTML documents with various
        colors, fonts, layouts, and spacing. But that is just the
        beginning. You can also do some "cool" stuff such as creating
        transitions or adding animations. There are so many things you can
        do with CSS, that we focus on the following:</p>
        <ul>
            <li>Rules and syntax (how to write CSS code)</li>
            <li>Simple styling (fonts, colors, borders)</li>
            <li>More styling (background images and opacity)</li>
            <li>Positioning - how to get the different parts of your page
            to go where you want them to go</li>
            <li>Pseudo-classes - styling things that aren't even
            there!</li>
        </ul>...
```
(remaining content snipped again)

**Comment by ratijas** [comment]
+1
i would like to have those notes also.

possibly, there is some `xslt` file that should be applied to source to render in HTML, and than save it into file.  is there any official info from coursera docs?

**Comment by balta2ar** [comment]
Let's update the status here. Support for PDFs (and other files) is implemented in #437, so they are being downloaded now. Do you want to save notes in a file as well? Let's settle on which notes are required. So far I've seen notes for these `typeName`s: `supplement`, `gradedProgramming`, `ungradedProgramming`.

If we want to focus on saving notes, let's rename the issue to something more narrow.

**Comment by StevenMaude** [comment]
@balta2ar As for which notes to include, my criterion would be: are they still useful if I'm offline without being logged into Coursera?

I'm not sure of the other types you mention — what do they contain? — but `supplement` seems to be relevant course material usable offline.

BTW, if this is something the team won't be handling for a while, I'm happy to try to tackle this sometime. That said, not sure of the best approach for processing the output as mentioned in my [earlier comment](https://github.com/coursera-dl/coursera-dl/issues/391#issuecomment-163717679).

Does Coursera use `<co-content>` style content elsewhere on the site, and does `coursera-dl` already have some way of handling this? Or would an acceptable solution be to just scrape it from the rendered HTML?

**Comment by balta2ar** [comment]
> Does Coursera use <co-content> style content elsewhere on the site

From what I have seen when I was implementing #437 and #439, they use `<co-content>` pretty much in every section that has text in it, that includes `supplement` and both `gradedProgramming` and `ungradedProgramming`.

> does coursera-dl already have some way of handling this

We only use it to extract `<a href>` and `<asset>` tags from the text.

> would an acceptable solution be to just scrape it from the rendered HTML

We don't have rendered HTML anywhere in on-demand scraper and I suggest we keep it that way as long as we can.

As for conversion, I think we can start with replacing one set of tags with another. E.g. `co-content` => `body`, `text` => `p`, `heading` => `h3` and so on. BeautifulSoup to the rescue here.

> I'm happy to try to tackle this sometime

I recommend to either wait for #439 to be reviewed and merged, or start working on top of it and rebase later.

**Comment by StevenMaude** [comment]
@balta2ar Thanks for the details; have subscribed to #439 to look once it's merged.

**Comment by flutable** [comment]
This may be related, but when fetching a resource outside Coursera, the script fails.
Debug log at: https://dl.dropboxusercontent.com/u/1348289/basic-statistics-debug.txt

**Comment by rbrito** [comment]
Hi, everybody.

Is this issue still present with the current version (0.5.2) that you can install with pip? It includes a lot of amazing work by @balta2ar so things should just work now.

Please make sure that you use something like to install the latest version:

```
pip3 install --upgrade --user coursera
```

I'm closing this issue. If you still have problems, please don't hesitate to add more information here and reopen this bug.


Thanks,

Rogério Brito.
