### ISSUE TITLE
with --preview option program only download videos rather than other materials

### ISSUE THREAD

**Issue by linpackzh** [coursera-dl/coursera-dl#392]
For example, https://class.coursera.org/linearopt-002/lecture.
Thanks!

**Comment by rbrito** [comment]
Hi, @linpackzh.

That's not our problem, unfortunately. As far as I know, that's what they (coursera) make available to us.

Hope this helps,

Rogério.

**Comment by rbrito** [comment]
If you can access *other* contents via your browser, then please reopen this bug with more details. Specifically, the output of the

**Comment by aliok** [comment]
In this preview course, https://class.coursera.org/machlearning-001/lecture/preview, I don't see any link to slides in Coursera website.

`coursea-dl` works as expected; downloads the videos.

But, is there any way to download the annotated slides? They're there; shown embedded in the video player.

**Comment by balta2ar** [comment]
Not actual. Old courses are not supported anymore.
