### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by victorwestmann** [coursera-dl/coursera-dl#394]
Hi there. I'm new to the project but I'd like to propose a new logo. What do you -- developers -- think?

It is stored in this link: http://victorwestmann.deviantart.com/art/Sugestao-3-557938555?ga_submit_new=10%253A1441251625

Regards.

**Comment by vladistan** [comment]
I like it

**Comment by rbrito** [comment]
@victorwestmann, Great.

You won't believe it, but I was toying with something that had the same concept (I took the Markdown logo as inspiration) and grabbed the very same hat from openclipart. I was just unsure of where I should have put the down arrow, and I think that you nailed it. :)

Great, I'll merge it and include it as the logo for the organization (or, if you want, I can help you with your first pull request).

Thanks,

Rogério.

**Comment by rbrito** [comment]
@victorwestmann, Just looked further and it is only available in bitmapped form, apparently. Do you have the source (i.e., SVG)?

----

Oh, scrap that. The source is in the e-mail that you sent me, but it was outside the viewport.

**Comment by rbrito** [comment]
Excellent. I just committed that (https://github.com/coursera-dl/coursera-dl/commit/03b6b8f2669a1bb5255478b3934137629f12e46a) and we are now able to close this bug and #358. :)
