### ISSUE TITLE
troubles to donwload archived courses

### ISSUE THREAD

**Issue by victorwestmann** [coursera-dl/coursera-dl#398]
The thing is... the course was already closed but the video materials were still available to watch.

So I'm not oficcially enrolled inthe course. Is that why I'm facing download errors using coursera-dl?

```
C:\coursera-dl>coursera-dl.bat -u yyyyyyyyyyyyyy -p xxxxxxxxx programming1
Downloading class: programming1
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found
Could not find class: programming1:
When trying to dowload an on-demand course, use the --on-demand option. See README.md for details.
```

Using Windows 10 64bit and the latest version of coursera-dl.

**Comment by rbrito** [comment]
Courses that are *not* on-demand have names of the form `<coursename>-<an integer>`. Please, log into the course with your browser and see what the URL contains.

It should be something like `programming1-002` or so.

**Comment by victorwestmann** [comment]
@rbrito I'll need your help on this one (since your more skilled in this than me).

This is the course URL: https://www.coursera.org/course/programming1
And this is the course title: Learn to Program: The Fundamentals

**Comment by balta2ar** [comment]
Even though it's already closed, try to Enroll so that you can open this page (https://class.coursera.org/programming1-002) and see course contents in your browser. After that try downloading the course again.

**Comment by victorwestmann** [comment]
NO Waaay! It worked! Thanks for the help @balta2ar :+1:
