### ISSUE TITLE
Unable to download Wireless communications course

### ISSUE THREAD

**Issue by code-is-god** [coursera-dl/coursera-dl#400]
I am trying to download the course https://www.coursera.org/learn/wireless-communication-technologies/home/welcome

The program ends after trying to parse syllabus.

I've used --on-demand option, still it doesn't work. Coursera has updated their interface, maybe this is breaking the program?

**Comment by rbrito** [comment]
Hi.

All the courses that have a URL starting with `https://www.coursera.org/learn/` are on-demand courses and you should use the `--on-demand` option when calling the script, until we implement a new strategy to download such courses automatically (see issue #387).

@code-is-god, @victorwestmann, can you add a few paragraphs to our documentation *or* to our wiki regarding this kind of thing, please?

Thanks for any collaboration,

Rogério.

**Comment by code-is-god** [comment]
Thanks, I was using `-sf` filter along with the `--on-demand` option, and the code failed. I removed the `-sf` filter and the thing works.

Would try to add some documentation around it, though am a newbie here, and will need to look around the system to see how add/edit before getting started.

Thanks again for this awesome tool.
