### ISSUE TITLE
[ssl-issues] SSL problem when running under Ubuntu 14.04 with Python 3.4

### ISSUE THREAD

**Issue by Trailglider** [coursera-dl/coursera-dl#402]
Hi,

I installed the script under Python 3.4 on Ubuntu 14.04 and was able to download on-demand courses fine, but for every regular course I try I get an SSL error:

ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

Any idea what causes this and how to fix it?

The full traceback looks like this:
user@Ubuntu-XX:/media/sf_Virtual_Share/coursera$ coursera-dl -u [myusername] -p [mypassword] acoustics1-002
Downloading class: acoustics1-002
Starting new HTTPS connection (1): class.coursera.org
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 578, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.0.3', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python3.4/dist-packages/coursera/coursera_dl.py", line 944, in main
    result = download_class(args, class_name)
  File "/usr/local/lib/python3.4/dist-packages/coursera/coursera_dl.py", line 842, in download_class
    username=args.username, password=args.password)
  File "/usr/local/lib/python3.4/dist-packages/coursera/cookies.py", line 337, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/usr/local/lib/python3.4/dist-packages/coursera/cookies.py", line 160, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "/usr/local/lib/python3.4/dist-packages/coursera/cookies.py", line 83, in login
    r = requests.get(class_url, allow_redirects=False)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

**Comment by balta2ar** [comment]
It's not the first time we get SSL error reports here. This might be related to https://github.com/coursera-dl/coursera-dl/issues/377. Sorry, I don't have a specific solution for this very problem for you right now, but I've seen some related discussions before. Try searching for similar error reports and reading comments there, it might help (or not).

**Comment by Trailglider** [comment]
#377 seems to have a solution for python 2.7.6, but the instructions say using python 3.4 is preferred and I would prefer using that if possible rather than being on an unsupported python version and risking encountering more problems in future. But thanks, if nothing else crops up I may need to explore the 2.7.6 solution.

**Comment by balta2ar** [comment]
Looking at your problem again, I think the issue I mentioned is not related. I believe you're having problems because Python 2.x and 3.x at some point enabled automatic SSL certificate verification by deafult (https://www.python.org/dev/peps/pep-0476/). My understanding is that someone's (your neighbor, ISP, goverment, whatever) trying to "MITM" you with their own cerfificate, what Python immediately detects.

Anyway, I think we need an option to disable SSL cert verification for such cases. Again, we can catch this exception, check whether it's failed verification and advice to use `--skip-ssl-certificate-verification`. What do you think, @rbrito?

**Comment by Trailglider** [comment]
Strange thing is, on-demand courses worked fine. One would assume coursera uses same certificate - is something different in certificate verification of on-demand vs traditional course download?

**Comment by balta2ar** [comment]
On-demand courses are located at `https://www.coursera.org/learn`. Regular courses are located at `https://class.coursera.org`. `openssl` output is different for them:

```
$ openssl s_client -connect class.coursera.org:443
CONNECTED(00000003)
depth=3 C = US, O = "The Go Daddy Group, Inc.", OU = Go Daddy Class 2 Certification Authority
verify return:1
depth=2 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", CN = Go Daddy Root Certificate Authority - G2
verify return:1
depth=1 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", OU = http://certs.godaddy.com/repository/, CN = Go Daddy
 Secure Certificate Authority - G2
verify return:1
depth=0 OU = Domain Control Validated, CN = *.coursera.org
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/CN=*.coursera.org
   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate $
uthority - G2
 1 s:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate $
uthority - G2
   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2
 2 s:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2
   i:/C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority
---
Server certificate
...
```
And
```
$ openssl s_client -connect www.coursera.org:443
CONNECTED(00000003)
140672174970520:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 318 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---
```

Though I'm not sure that output is to be trusted, maybe I'm doing something wrong. My browser says that connection to both sites are secure though. Details show that they indeed share the same certificate. Well, I'm out of ideas.

If you're in a hacky mood, try adding this code after existing imports in `coursera/coursera_dl.py`:
``` python
import ssl

if hasattr(ssl, '_create_unverified_context'):
    ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by rbrito** [comment]
I'm speaking this without 100% of confidence, but knowing how Debian tends to treat things in general (which is generally shared with Ubuntu).

Apart from java <= 7 (but with Java 8 and above going the way of the rest of the packages), all packages try to use certificates from the package `ca-certificates`. If you have a site certificate that is not recognized, then the first things to try would be to see if the certificate is self-signed/expired/invalid etc. (which I don't believe is the case here) or you can upgrade your `ca-certificates` package.

In general, you may even grab a new version of `ca-certificates` from a more recent distribution (install it with dpkg) and you should be generally be fine (and, if anything goes wrong---which, in general, probably won't---, you can download the version that you had before and reinstall it manually).

**Comment by balta2ar** [comment]
Hopefully fixed by https://github.com/coursera-dl/coursera-dl/commit/2763681bf08a2abf172aba6b5b337ab771f3579e. Closing.
