### ISSUE TITLE
[shorten-filenames] "IOError: [Errno 1] Operation not permitted" with long filenames under Windows

### ISSUE THREAD

**Issue by Trailglider** [coursera-dl/coursera-dl#406]
In the process of downloading several traditional courses, I have encountered one video in one course that refuses to download. 5 full courses have downloaded fine.

Problem is with the 05_14 video in "learning-001" - below is the console output. I retried several times, problem is always with this one specific file. 

Downloading https://class.coursera.org/learning-001/lecture/subtitles?q=99_en&format=txt -> learning-001/05_Week_Four-_Renaissance_Learning__and_Unlocking_Your_Potential/05_13_Added_Bonus-_Part_2-_Learning_something_new_interview_with_Dr._Richard_Felder_and_Dr._Rebecca_Brent_9-05.txt
--%                                                                    N/A at 71[##################################################] 100%            3.10KB at 67.86KB/s
Downloading: learning-001/05_Week_Four-_Renaissance_Learning__and_Unlocking_Your_Potential/05_13_Added_Bonus-_Part_2-_Learning_something_new_interview_with_Dr._Richard_Felder_and_Dr._Rebecca_Brent_9-05.srt
Downloading https://class.coursera.org/learning-001/lecture/subtitles?q=99_en&format=srt -> learning-001/05_Week_Four-_Renaissance_Learning__and_Unlocking_Your_Potential/05_13_Added_Bonus-_Part_2-_Learning_something_new_interview_with_Dr._Richard_Felder_and_Dr._Rebecca_Brent_9-05.srt
--%                                                                   N/A at 136[##################################################] 100%           4.74KB at 134.61KB/s
Downloading: learning-001/05_Week_Four-_Renaissance_Learning__and_Unlocking_Your_Potential/05_14_Added_Bonus-_Part_3-_The_imposter_syndrome_and_dealing_with_procrastination_interview_with_Dr._Richard_Felder_and_Dr._Rebecca_Brent_9-55.mp4
Downloading https://class.coursera.org/learning-001/lecture/download.mp4?lecture_id=101 -> learning-001/05_Week_Four-_Renaissance_Learning__and_Unlocking_Your_Potential/05_14_Added_Bonus-_Part_3-_The_imposter_syndrome_and_dealing_with_procrastination_interview_with_Dr._Richard_Felder_and_Dr._Rebecca_Brent_9-55.mp4
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.0.3', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 944, in main
    result = download_class(args, class_name)
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 873, in download_class
    args.intact_fnames)
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 514, in download_lectures
    downloader.download(url, lecfn)
  File "/usr/local/lib/python2.7/dist-packages/coursera/downloaders.py", line 43, in download
    self._start_download(url, filename)
  File "/usr/local/lib/python2.7/dist-packages/coursera/downloaders.py", line 302, in _start_download
    with open(filename, 'wb') as f:
IOError: [Errno 1] Operation not permitted: u'learning-001/05_Week_Four-_Renaissance_Learning__and_Unlocking_Your_Potential/05_14_Added_Bonus-_Part_3-_The_imposter_syndrome_and_dealing_with_procrastination_interview_with_Dr._Richard_Felder_and_Dr._Rebecca_Brent_9-55.mp4'

**Comment by balta2ar** [comment]
I couldn't enroll to `learning-001` but I am enrolled to `learning-002`. I can't reproduce your problem locally.

I think it is related to the maximum path length of your file system. The problematic file is the longest of all, it's probably exceeding path length limit. Try moving the directory with your downloaded courses somewhere up the filesystem hierarchy or switch to file system that has longer path length limit. P.S. I have ext4 and it works fine for me.

**Comment by rbrito** [comment]
@Trailglider, what filesystem are you using?

Oh, I just saw that @balta2ar has just mentioned the problem with long file names. If the problem is really with windows, then I have no idea how to solve it. Perhaps the "cleanest" (well, not so clean, but the best compromise) that I know of is implemented in musicbrainz's Picard (which has a compatible license with us, IIRC, which means that we can kindly "steal" their solution).

If indeed the problem are long pathnames, we may end up having to trim so much of the file names that we can't even put a proper extension (say that the full path, minus the filename leaves us with only 3 bytes---which characters should we keep and which ones should we drop?).

**Comment by Trailglider** [comment]
Thanks, I will try with shorter folder name tonight and let you know.

The system is Ubuntu running on VirtualBox and the destination is a virtualbox shared folder on the NTFS Win7 host. The shared folder path is currently about 45 characters long.

**Comment by Trailglider** [comment]
Works with shorter folder name.

**Comment by nishad** [comment]
You can try with a windows binary of `coursera-dl` available here at https://github.com/nishad/coursera-dl-windows

**Comment by abdalrohman** [comment]
Try change to exFAT and shared with VirtualBox 
I have exFAT and work good on VM

**Comment by FoxBearBear** [comment]
For those using Windows and having the aforementioned problem or this one _**[Errno 2] No such file or directory:**_

You can enable longer paths by:

- Registry editor

- HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem

- Set **LongPathsEnabled** to 1

- Reboot and be happy

**Comment by rbrito** [comment]
@FoxBearBear, can you submit a pull request with this information in our README file? This is a FAQ and should be answered there, I guess...
