### ISSUE TITLE
How to find className after coursera revised its version?

### ISSUE THREAD

**Issue by pangjac** [coursera-dl/coursera-dl#411]
Dear talents,

I have read about the guidance for how to find a proper class name from :
" Make sure the class name you are using corresponds to the resource name used in the URL for that class: https://class.coursera.org/<CLASS_NAME>/class/index "

However coursera is revising its course version for specification. For example, for one specification course:  https://www.coursera.org/learn/object-oriented-java
I use object-oriented-java as resourcename to verify per :  https://class.coursera.org/object-oriented-java/class/index  , however, it returns error.

So in this case, could you give me some more hint on how to find a proper class name?

Thanks!

**Comment by balta2ar** [comment]
Classes that contain `/learn/` in the URL are most likely (that may change in the future) on-demand. Add `--on-demand` option to the command line and try again.
