### ISSUE TITLE
how to download self study course video

### ISSUE THREAD

**Issue by widon1104** [coursera-dl/coursera-dl#412]
like this course:
https://www.coursera.org/learn/zhichang-suyang/home/welcome

**Comment by balta2ar** [comment]
Try `--on-demand` option.

**Comment by rbrito** [comment]
I *just* saw the following and I think that it may change our lives in coursera-dl soon:

https://learner.coursera.help/hc/en-us/articles/203879739-Course-Types

/cc: @mxamin, @balta2ar

**Comment by balta2ar** [comment]
@rbrito Why? Isn't it the same on-demand type of course that is already supported? At least I've managed to download the course that @widon1104 has referenced.

**Comment by rbrito** [comment]
I think that, essentially, the distinction between on-demand and regular courses (which had to be parsed differently, with the former in JSON format and the latter with scraping with BeautifulSoup) is becoming more and more blurred.

My guess is that the "current" format (now called by coursera as "old platform") is essentially dead and that we should make (at least) 2 changes:

1. To change the current behavior and adopt what you suggested before (and that I had thought about a bit earlier, but never acted on) of first trying as one type of course, then as another. This has the benefit of killing the `--on-demand` option and making the program easier to use for end-users.
2. Invest more time into polishing the JSON parsing to bring it up to speed in comparison to the current BeautifulSoup parsing. In particular, the JSON parsing doesn't seem to download PDF files etc.

Comments?

**Comment by balta2ar** [comment]
1. Here is my take on this: #413
2. I haven't looked at the code thoroughly yet, but could you hint what's slowing down JSON parsing and how to speed it up? Is it the same as edx-dl where you have have to download and parse multiple pages?
