### ISSUE TITLE
old link format?...

### ISSUE THREAD

**Issue by btyukodi** [coursera-dl/coursera-dl#416]
So I just started using coursera-dl but get the following error:

404 Client Error: Not Found for url: https://class.coursera.org/machine-learning
Could not find class: machine-learning

which seems normal since the actual link to the course is:
https://www.coursera.org/learn/machine-learning/

Is it possible that coursera-dl is trying to work with an older link format? If so, how do I fix this?

Thanks!

**Comment by balta2ar** [comment]
Use `--on-demand` option. Or update to the latest version on github and it will detect course type automatically.

**Comment by btyukodi** [comment]
Tried it, but raises the following error:

requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

**Comment by balta2ar** [comment]
That problem has been reported numerous times and it looks like there is no consistent and reliable solution yet. Please use search to find other issues and read them, it may help. Start here: https://github.com/coursera-dl/coursera-dl/issues/383. Thanks.

**Comment by btyukodi** [comment]
Thanks! This solution from #383 seemed to fix it:

sudo easy_install virtualenv
virtualenv -p /usr/bin/python3 coursera
cd coursera/
./bin/pip install coursera
./bin/coursera-dl -u username@gmail.com -p password --on-demand machine-learning
