### ISSUE TITLE
Link with learn inside the adress

### ISSUE THREAD

**Issue by steveprudhomme** [coursera-dl/coursera-dl#417]
Ok, if my link is https://www.coursera.org/learn/html-css-javascript/.
It is not a class.coursera.org. It is possible to use coursera-dl.

**Comment by ratijas** [comment]
open the 'wiki' of this repository (button on the right), and here you are:

https://github.com/coursera-dl/coursera-dl/wiki

**Comment by balta2ar** [comment]
@steveprudhomme Use the latest version from github, it detects course type automatically.

**Comment by balta2ar** [comment]
Repeating myself once again, github version should work in your case. If you have any troubles, feel free to report here. Closing.

**Comment by rbrito** [comment]
The version that I just sent to PyPI has all the usability fixes for this.

**Comment by steveprudhomme** [comment]
Thanks I will test it with pleasure.
