### ISSUE TITLE
Unable to download the on-demand courses

### ISSUE THREAD

**Issue by kakumarabhishek** [coursera-dl/coursera-dl#422]
I ran the following command on my Ubuntu MATE 15.10 PC.
**./coursera-dl -u USERNAME -p PASSWORD --on-demand python-data**
and I got the following error.
**coursera-dl: error: unrecognized arguments: --on-demand**

Then I realized that the --on-demand is deprecated and tried running without the command, upon which I got a 404 error saying 

**Downloading class: python-data**
**Starting new HTTPS connection (1): class.coursera.org**
**404 Client Error: Not Found for url: https://class.coursera.org/python-data**
**Could not find class: python-data**

. The course I am trying to download is this -
*https://www.coursera.org/learn/python-data/* or *https://www.coursera.org/learn/python-network-data/* or anything which has links like this.

**Comment by balta2ar** [comment]
`--on-demand` option should be recognized. You might be using old version of the script. Try running the latest version from github.

**Comment by ratijas** [comment]
somebody, maintain the pip version please.  it's very confusing, i ran into the same problem when `pip install ...`.

**Comment by kakumarabhishek** [comment]
@ratijas Yeah, I got this issue after doing **pip install coursera**
Should I download the **master.zip** from GitHub? I tried doing the same on my office PC and ran into the same issue. Please suggest what I should do.

**Comment by balta2ar** [comment]
@rbrito Could you please update pip version?

@kakumarabhishek Try `git clone`ing the repo.

**Comment by jjzz** [comment]
`pip3 install coursera==0.1.0a3` to install the alpha version, it works.
check https://pypi.python.org/pypi/coursera for latest unstable version

Anyway, github repo is a better choice.

**Comment by balta2ar** [comment]
@kakumarabhishek Is your problem still there? Have you tried github version?

**Comment by rbrito** [comment]
This should be fixed in pypi. Please, upgrade to version 0.5.0.
