### ISSUE TITLE
Can't be installed on Raspbian Wheezy

### ISSUE THREAD

**Issue by SergeySeleznyov** [coursera-dl/coursera-dl#428]
Can't install on Raspbian wheezy:

$ sudo pip3 install coursera
>
Collecting coursera
  Using cached coursera-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-703gr5vq/coursera/setup.py", line 26, in <module>
        long_description=open('README.rst', 'r').read(),
      File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16781: ordinal not in range(128)

>  ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-703gr5vq/coursera

Any idea how can i workaround it?
Thanks!

=========================
Hardware: Raspberry Pi 2 Model B
Os:            Raspbian Wheezy

$ uname -a
>Linux r64 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux

$ python3 --version
>Python 3.5.0

$ pip3 --version
>pip 7.1.2 from /usr/local/lib/python3.5/site-packages (python 3.5)

$ sudo pip3 install -r requirements.txt
>
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4>=4.1.3 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): html5lib>=1.0b2 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): requests>=2.4.3 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.0 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): urllib3>=1.10 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): keyring>=4.0 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 7))

**Comment by hxhxd** [comment]
Don't use pip, instead clone it, and make soft link.
But I don't think it will work, there's some big change in coursera now.

**Comment by SergeySeleznyov** [comment]
Thanks! It works now!

Here are the steps to get it working on Raspberry Pi with Raspbian Wheezy.
Would someone simplify it if possible?

### 1. Intall python3 and pip3
Instruction is taken from:
http://bohdan-danishevsky.blogspot.ru/2015/10/building-python-35-on-raspberry-pi-2.html
For my configuration i omitted "sudo apt-get dist-upgrade"

### 2. Install coursera-dl 
Based on the reference (with some small corrections):
https://github.com/coursera-dl/coursera-dl#alternative-installation-method-for-unix-systems

$ cd /opt
$ sudo mkdir coursera-dl && cd $_

$ sudo virtualenv --python=python3.5 my-coursera
$ cd my-coursera
$ source bin/activate
$ sudo git clone https://github.com/coursera-dl/coursera
$ cd coursera
$ sudo pip3 install -r requirements.txt

edit: /opt/coursera-dl/my-coursera/coursera/coursera-dl
replace shabang:
   '#!/usr/bin/env python' 
with: 
   '#!/usr/bin/env python3.5'

$ sudo ln -s /opt/coursera-dl/my-coursera/coursera/coursera-dl /usr/local/bin/coursera-dl

**Comment by balta2ar** [comment]
pip version lags behing github version, unfortunately. The issue might be solved if we updated pip version, which I hope is going to happen in the future. Closing for now.

**Comment by rbrito** [comment]
This should be fixed in pypi. Please, upgrade to version 0.5.0.
