### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by raffamaiden** [coursera-dl/coursera-dl#430]
Running the following command

`coursera-dl --path=C:\data\finance\coursera -u USERNAME -p MYPASSWORD --on-demand financial-engineering-1`

starts to download some videos, but a certain point crash with the following error message.

It looks like coursera-dl tries to download an srt file which doesn't exists
`
Downloading: C:\data\finance\coursera\financial-engineering-1\07_introduction-to
-mortgage-mathematics-and-mortgage-backed-securities\01_introduction-to-mortgage
-mathematics-and-mortgage-backed-securities\01_introduction-to-mortgage-mathemat
ics-and-mortgage-backed-securities.srt

Downloading https://www.coursera.org/api/subtitleAssetProxy.v1/k455F8hVQ1qOeRfIV
bNaXw?expiry=1451347200000&hmac=8PT9_hIPdL3SOyx4jIUpsJdbcEfs-JWLyQsnf9qjpbk&file
Extension=srt -> C:\data\finance\coursera\financial-engineering-1\07_introductio
n-to-mortgage-mathematics-and-mortgage-backed-securities\01_introduction-to-mort
gage-mathematics-and-mortgage-backed-securities\01_introduction-to-mortgage-math
ematics-and-mortgage-backed-securities.srt

Traceback (most recent call last):
  File "C:\data\progetti_altrui\coursera-dl\coursera\cookies.py", line 91, in lo
gin
    r.raise_for_status()
  File "C:\Python34\lib\site-packages\requests\models.py", line 840, in raise_fo
r_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://clas
s.coursera.org/financial-engineering-1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\data\progetti_altrui\coursera-dl\coursera\coursera_dl.py", line 1086,
 in download_class
    return download_old_style_class(args, class_name)
  File "C:\data\progetti_altrui\coursera-dl\coursera\coursera_dl.py", line 967,
in download_old_style_class
    username=args.username, password=args.password)
  File "C:\data\progetti_altrui\coursera-dl\coursera\cookies.py", line 345, in g
et_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "C:\data\progetti_altrui\coursera-dl\coursera\cookies.py", line 166, in g
et_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "C:\data\progetti_altrui\coursera-dl\coursera\cookies.py", line 94, in lo
gin
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: financial-engineering-1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\data\progetti_altrui\coursera-dl\\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "C:\data\progetti_altrui\coursera-dl\coursera\coursera_dl.py", line 1111,
 in main
    if download_class(args, class_name):
  File "C:\data\progetti_altrui\coursera-dl\coursera\coursera_dl.py", line 1089,
 in download_class
    return download_on_demand_class(args, class_name)
  File "C:\data\progetti_altrui\coursera-dl\coursera\coursera_dl.py", line 1070,
 in download_on_demand_class
    args.resume
  File "C:\data\progetti_altrui\coursera-dl\coursera\coursera_dl.py", line 584,
in download_lectures
    downloader.download(url, lecfn, resume=resume)
  File "C:\data\progetti_altrui\coursera-dl\coursera\downloaders.py", line 50, i
n download
    self._start_download(url, filename, resume)
  File "C:\data\progetti_altrui\coursera-dl\coursera\downloaders.py", line 366,
in _start_download
    f = open(filename, 'ab') if resume else open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\data\\finance\\cour
sera\\financial-engineering-1\\07_introduction-to-mortgage-mathematics-and-mortg
age-backed-securities\\01_introduction-to-mortgage-mathematics-and-mortgage-back
ed-securities\\01_introduction-to-mortgage-mathematics-and-mortgage-backed-secur
ities.srt'
`

**Comment by raffamaiden** [comment]
Nothing? How can  I solve this? It looks like it tries to download an srt file which doesn't exists

**Comment by balta2ar** [comment]
@raffamaiden From what I can see in `coursera-dl --help`, there is no option to ignore HTTP errors. I suggest looking at options that allow to utilize external downloader. For example, I personally use `--aria2` option. You can specify default settings for `area2c` in its configuration file (see `man area2c` for the details) to ignore HTTP errors.

**Comment by balta2ar** [comment]
On the other hand, I think you're facing famous MAX_LEN=256 path problems of Windows:
``` python
In [72]: len('C:\data\finance\coursera\financial-engineering-1\07_introduction-to-mortgage-mathematics-and-mortgage-backed-securities\01_introduction-to-mortgage-mathematics-and-mortgage-backed-securities\01_introduction-to-mortgage-mathematics-and-mortgage-backed-securities.srt')
Out[72]: 257
```

Possible solutions were discussed here and there (see #406) but there is nothing we can do about it right now. You may want to consider using virtual machine with GNU/Linux to download materials anyway.
Closing as duplicate.
