### ISSUE TITLE
download very slow in china

### ISSUE THREAD

**Issue by widon1104** [coursera-dl/coursera-dl#435]
only 40kb, I have 10m bandwidth

**Comment by klimenko** [comment]
Hello!
It happens sometimes with Coursera.
Try --wget option.

**Comment by widon1104** [comment]
use --wget download probably fail "can't resolve host address"

**Comment by balta2ar** [comment]
I don't think there is anything we can do in the downloader to get your download speed higher. That's networking/connectivity problems.

**Comment by hyhy01** [comment]
所以我都翻墙了

**Comment by skywb** [comment]
最终还得靠翻墙
