### ISSUE TITLE
File not Found error

### ISSUE THREAD

**Issue by achaleus** [coursera-dl/coursera-dl#436]
Hello I got File not found error while downloading the one mentioned below
I assume the problem might be length of the file name. Any solutions for this

FileNotFoundError: [Errno 2] No such file or directory: 'finiteelementmethods-001\\07_Unit_7-_Linear_elliptic_partial_differential_equations_for_a_scalar_variable_in_three_dimensions._Heat_conduction_and_mass_diffusion_at_steady_state\\01_07.01._The_strong_form_of_steady_state_heat_conduction_and_mass_diffusion_-_I_18-24.srt'

**Comment by frswedom** [comment]
I have the same problem with this course (finite element methods)
As far as I know, Windows don't allow to use file path longer than 259~260 characters.

**Comment by balta2ar** [comment]
Long file names problem on Windows is a known problem which we don't know yet how to solve properly. Possible solutions were discussed here and there (see #406) though. Closing as duplicate.
