### ISSUE TITLE
Please provide some working examples of downloading from on-demand courses

### ISSUE THREAD

**Issue by flutable** [coursera-dl/coursera-dl#440]
Hi,
I've been trying to download courses as follows:
coursera-dl -u _UUU _-p _password  _"Basic-Statistics" --path=c:\temp2\Intro_Statistics

but I keep getting http error 400s. What format should the class name be?
The courses are:
https://www.coursera.org/learn/basic-statistics/home/welcome
https://www.coursera.org/learn/statistical-inference/home/welcome
etc.

I haven't yet tried with the old coursera URIs. Things were simpler then :(

**Comment by balta2ar** [comment]
https://www.coursera.org/learn/basic-statistics/home/welcome => `basic-statistics`
https://www.coursera.org/learn/statistical-inference/home/welcome => `statistical-inference`
```
coursera-dl -u <username> -p <password> basic-statistics --path=c:\temp2\Intro_Statistics
```

**Comment by flutable** [comment]
I pledge hand-on-heart I tried that, and it didn't work. Yes, the hyphen was there. Now it works. Many thanks!
