### ISSUE TITLE
cant recognize password with special characters

### ISSUE THREAD

**Issue by vincentzlt** [coursera-dl/coursera-dl#445]
seems the script can only recognize numbers and letters, but not brackets in -p password specifications

**Comment by balta2ar** [comment]
How do you provide them?

**Comment by vincentzlt** [comment]
Actually my original Coursera account has a password containing “[”and “]”. And when I tried to use the script, it just returns information of “missing files” and doesn’t do anything. After I changed my password to [a-zA-Z0-9], it begins to work…

 

发件人: Yuri Bochkarev [mailto:notifications@github.com] 
发送时间: 2016年2月20日 05:34
收件人: coursera-dl/coursera-dl <coursera-dl@noreply.github.com>
抄送: vincentzlt <vincentzlt@gmail.com>
主题: Re: [coursera-dl] cant recognize password with special characters (#445)

 

How do you provide them?

**Comment by balta2ar** [comment]
I understand that, thank you. I'm asking how you provide the password to the script? In command line, in netrc file? If you're doing that in a shell, certain characters may be interpreted by the shell differently. That's just a wild guess.

**Comment by vincentzlt** [comment]
Oh yes, I type the password in cmd shell. Maybe that is the problem. Thanks!

 

发件人: Yuri Bochkarev [mailto:notifications@github.com] 
发送时间: 2016年2月20日 06:31
收件人: coursera-dl/coursera-dl <coursera-dl@noreply.github.com>
抄送: vincentzlt <vincentzlt@gmail.com>
主题: Re: [coursera-dl] cant recognize password with special characters (#445)

 

I understand that, thank you. I'm asking how you provide the password to the script? In command line, in netrc file? If you're doing that in a shell, certain characters may be interpreted by the shell differently. That's just a wild guess.

**Comment by vincentzlt** [comment]
And, may I ask another question? I got some warning messages like this:

 

Downloading: cpp-chengxu-sheji\04_yun-suan-fu-zhong-zai\05_ke-cheng-jiang-yi-xia-zai\01_ke-cheng-slides_05_%E6%B5%81%E6%8F%92%E5%85%A5%E8%BF%90%E7%AE%97%E7%AC%A6%E5%92%8C%E6%B5%81%E6%8F%90%E5%8F%96%E8%BF%90%E7%AE%97%E7%AC%A6%E7%9A%84%E9%87%8D%E8%BD%BD.pdf

Downloading https://d396qusza40orc.cloudfront.net/pkupop/lectures/Week4/05_%E6%B5%81%E6%8F%92%E5%85%A5%E8%BF%90%E7%AE%97%E7%AC%A6%E5%92%8C%E6%B5%81%E6%8F%90%E5%8F%96%E8%BF%90%E7%AE%97%E7%AC%A6%E7%9A%84%E9%87%8D%E8%BD%BD.pdf -> cpp-chengxu-sheji\04_yun-suan-fu-zhong-zai\05_ke-cheng-jiang-yi-xia-zai\01_ke-cheng-slides_05_%E6%B5%81%E6%8F%92%E5%85%A5%E8%BF%90%E7%AE%97%E7%AC%A6%E5%92%8C%E6%B5%81%E6%8F%90%E5%8F%96%E8%BF%90%E7%AE%97%E7%AC%A6%E7%9A%84%E9%87%8D%E8%BD%BD.pdf

Traceback (most recent call last):

  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 91, in login

    r.raise_for_status()

  File "C:\Python34\lib\site-packages\requests\models.py", line 851, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 404 Client Error: Not Found

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1031, in download_class

    return download_old_style_class(args, class_name)

  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 912, in download_old_style_class

    username=args.username, password=args.password)

  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 345, in get_cookies_for_class

    get_authentication_cookies(session, class_name, username, password)

  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 166, in get_authentication_cookies

    login(session, username, password, class_name=class_name)

  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 94, in login

    raise ClassNotFound(class_name)

coursera.cookies.ClassNotFound: cpp-chengxu-sheji

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "C:\Python34\Scripts\coursera-dl-script.py", line 9, in <module>

    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()

  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1056, in main

    if download_class(args, class_name):

  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1034, in download_class

    return download_on_demand_class(args, class_name)

  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1015, in download_on_demand_class

    args.resume

  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 528, in download_lectures

    downloader.download(url, lecfn, resume=resume)

  File "C:\Python34\lib\site-packages\coursera\downloaders.py", line 50, in download

    self._start_download(url, filename, resume)

  File "C:\Python34\lib\site-packages\coursera\downloaders.py", line 366, in _start_download

    f = open(filename, 'ab') if resume else open(filename, 'wb')

FileNotFoundError: [Errno 2] No such file or directory: 'cpp-chengxu-sheji\\04_yun-suan-fu-zhong-zai\\05_ke-cheng-jiang-yi-xia-zai\\01_ke-cheng-slides_05_%E6%B5%81%E6%8F%92%E5%85%A5%E8%BF%90%E7%AE%97%E7%AC%A6%E5%92%8C%E6%B5%81%E6%8F%90%E5%8F%96%E8%BF%90%E7%AE%97%E7%AC%A6%E7%9A%84%E9%87%8D%E8%BD%BD.pdf'

 

C:\Python34\Scripts>

 

And I cant continue downloading. What Can I do?

 

Thanks!

 

发件人: Yuri Bochkarev [mailto:notifications@github.com] 
发送时间: 2016年2月20日 06:31
收件人: coursera-dl/coursera-dl <coursera-dl@noreply.github.com>
抄送: vincentzlt <vincentzlt@gmail.com>
主题: Re: [coursera-dl] cant recognize password with special characters (#445)

 

I understand that, thank you. I'm asking how you provide the password to the script? In command line, in netrc file? If you're doing that in a shell, certain characters may be interpreted by the shell differently. That's just a wild guess.

**Comment by rbrito** [comment]
Please, cut the unimportant parts of your reply, so that they are easier to follow by someone with the attention span of a mouse (my case).

That being said, are you using a Unix (Linux, FreeBSD, MacOSX, other BSDs) command line? If yes, then you should be able to type your password enclosed in single quotes and everything should work.

Otherwise, if you *don't* type the password on the command line, the script will ask you for your password interactively and I suppose that that has a higher probability of working.

Another option is just using a `netrc` file (which is what i personally use).


P.S.: Just saw (rereading your previous message) that you are using Windows. Unfortunately, I don't have a Windows machine at my disposal. Are you willing to be our Windows tester?

**Comment by vincentzlt** [comment]
Yes, I am using Windows. I can be your Windows tester. What should I do as a tester?

 

发件人: Rogério Brito [mailto:notifications@github.com] 
发送时间: 2016年2月23日 01:36
收件人: coursera-dl/coursera-dl <coursera-dl@noreply.github.com>
抄送: vincentzlt <vincentzlt@gmail.com>
主题: Re: [coursera-dl] cant recognize password with special characters (#445)

 

Please, cut the unimportant parts of your reply, so that they are easier to follow by someone with the attention span of a mouse (my case).

That being said, are you using a Unix (Linux, FreeBSD, MacOSX, other BSDs) command line? If yes, then you should be able to type your password enclosed in single quotes and everything should work.

Otherwise, if you don't type the password on the command line, the script will ask you for your password interactively and I suppose that that has a higher probability of working.

Another option is just using a netrc file (which is what i personally use).

P.S.: Just saw (rereading your previous message) that you are using Windows. Unfortunately, I don't have a Windows machine at my disposal. Are you willing to be our Windows tester?

**Comment by balta2ar** [comment]
@vincentzlt Is this still actual? Did you try putting your password into quotes?

**Comment by vincentzlt** [comment]
I think the problem has already been solved :)

**Comment by balta2ar** [comment]
Closing then.
