### ISSUE TITLE
Unicode filenames

### ISSUE THREAD

**Issue by vincentzlt** [coursera-dl/coursera-dl#446]
I believe it would be better if the script can remain the Unicode filenames such as chinese. if it is transformed to a long-list of random string during downloading, it will dramatically add to the length to the link and whenever the link is longer than 255 characters, I believe the whole program will stop work.

**Comment by rbrito** [comment]
We have an option called `--unrestricted-filenames`. Does it help you?

Unfortunately, I don't quite understand how limiting the filenames to be just ASCII (nota bene: we are *not* transcoding the names into ASCII; we are just dropping non-ASCII characters) could increase the size of the filenames.

Perhaps I didn't understand exactly your issue? Also, what operating system are you using?

**Comment by vincentzlt** [comment]
Sorry maybe I did not express myself clear. I did not notice this option and I will try it out. And regarding the transcoding issue: I am downloading a course in Chinese and some of the materials in that course are provided with a file name in Chinese Characters. And when I downloaded it, the file name automatically transcodes to a long string of letters. Perhaps this only happens to me. But thanks for your help! 

 

发件人: Rogério Brito [mailto:notifications@github.com] 
发送时间: 2016年2月23日 01:24
收件人: coursera-dl/coursera-dl <coursera-dl@noreply.github.com>
抄送: vincentzlt <vincentzlt@gmail.com>
主题: Re: [coursera-dl] Unicode filenames (#446)

 

We have an option called --unrestricted-filenames. Does it help you?

Unfortunately, I don't quite understand how limiting the filenames to be just ASCII (nota bene: we are not transcoding the names into ASCII; we are just dropping non-ASCII characters) could increase the size of the filenames.

Perhaps I didn't understand exactly your issue? Also, what operating system are you using?

**Comment by rbrito** [comment]
Ah, I just saw from your previous comment that the files *are* in ASCII, but they are URL encoded with percent signs, like in:

`https://d396qusza40orc.cloudfront.net/pkupop/lectures/Week4/05_%E6%B5%81%E6%8F%92%E5%85%A5%E8%BF%90%E7%AE%97%E7%AC%A6%E5%92%8C%E6%B5%81%E6%8F%90%E5%8F%96%E8%BF%90%E7%AE%97%E7%AC%A6%E7%9A%84%E9%87%8D%E8%BD%BD.pdf`

Once decoded to real characters, I get (with a real Python 3 session):

```python
>>> import urllib.parse
>>> s = 'https://d396qusza40orc.cloudfront.net/pkupop/lectures/Week4/05_%E6%B5%81%E6%8F%92%E5%85%A5%E8%BF%90%E7%AE%97%E7%AC%A6%E5%92%8C%E6%B5%81%E6%8F%90%E5%8F%96%E8%BF%90%E7%AE%97%E7%AC%A6%E7%9A%84%E9%87%8D%E8%BD%BD.pdf'
>>> urllib.parse.unquote(s)
'https://d396qusza40orc.cloudfront.net/pkupop/lectures/Week4/05_流插入运算符和流提取运算符的重载.pdf'
```

Is that what you would expect the script to save the file as?

**Comment by vincentzlt** [comment]
Yes!! Certainly :)

 

I think it would be better if it can save directly to the decoded form.

 

Thanks 

 

发件人: Rogério Brito [mailto:notifications@github.com] 
发送时间: 2016年2月23日 01:46
收件人: coursera-dl/coursera-dl <coursera-dl@noreply.github.com>
抄送: vincentzlt <vincentzlt@gmail.com>
主题: Re: [coursera-dl] Unicode filenames (#446)

 

Ah, I just saw from your previous comment that the files are in ASCII, but they are URL encoded with percent signs, like in:

https://d396qusza40orc.cloudfront.net/pkupop/lectures/Week4/05_%E6%B5%81%E6%8F%92%E5%85%A5%E8%BF%90%E7%AE%97%E7%AC%A6%E5%92%8C%E6%B5%81%E6%8F%90%E5%8F%96%E8%BF%90%E7%AE%97%E7%AC%A6%E7%9A%84%E9%87%8D%E8%BD%BD.pdf

Once decoded to real characters, I get (with a real Python 3 session):

>>> import urllib.parse
>>> s = 'https://d396qusza40orc.cloudfront.net/pkupop/lectures/Week4/05_%E6%B5%81%E6%8F%92%E5%85%A5%E8%BF%90%E7%AE%97%E7%AC%A6%E5%92%8C%E6%B5%81%E6%8F%90%E5%8F%96%E8%BF%90%E7%AE%97%E7%AC%A6%E7%9A%84%E9%87%8D%E8%BD%BD.pdf'
>>> urllib.parse.unquote(s)
'https://d396qusza40orc.cloudfront.net/pkupop/lectures/Week4/05_流插入运算符和流提取运算符的重载.pdf'

Is that what you would expect the script to save the file as?

**Comment by balta2ar** [comment]
@vincentzlt Could you check the latest github version with `--unrestricted-filenames` argument? I've just  downloaded your course and I have filenames as follows: `01_ke-cheng-slides_W11-01_枚举-基本思想.pdf`. Unquoting should be working for on-demand courses now. I'm closing the issue. Feel free to comment here if you are still having issues.
