### ISSUE TITLE
Could not authenticate: Did not find necessary cookies.

### ISSUE THREAD

**Issue by nagarajan-techhue** [coursera-dl/coursera-dl#447]
Downloading class: learn/learning-how-to-learn
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Could not authenticate: Did not find necessary cookies.

**Comment by rbrito** [comment]
Please, use only `learning-how-to-learn` as the name of the course, instead of `learn/learning-how-to-learn`.

If this solves you problem, can you submit a change to our documentation (perhaps in the troubleshooting section) so that we are more precise about the URLs that they should choose?

**Comment by findways** [comment]
Hi There,
I am having a similar issue.
The course html is given as:
https://www.coursera.org/learn/ml-foundations/home/week/1

So I took the course name as:
ml-foundations
which doesn't follow the naming nomenclature. I get the following error:


C:\Users\shane_000>coursera-dl -u ****.com -p **** ml-foundations

Coursera-dl v3.1.1 (html.parser)
Logging in as '***.com'...
Traceback (most recent call last):
  File "c:\users\shane_000\appdata\local\enthought\canopy\user\scripts\coursera-
dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()
  File "C:\Users\shane_000\AppData\Local\Enthought\Canopy\User\lib\site-packages
\courseradownloader\courseradownloader.py", line 648, in main
    d.login(args.course_names[0])
  File "C:\Users\shane_000\AppData\Local\Enthought\Canopy\User\lib\site-packages
\courseradownloader\courseradownloader.py", line 136, in login
    raise Exception("Unknown class %s" % className)
Exception: Unknown class ml-foundations

What am I doing wrong?
Thanks!

**Comment by mfrna** [comment]
I'm also trying to download "learning-how-to-learn" course, if I just execute 
coursera-dl learning-how-to-learn -u USERNAME

I get a 404 error

but when I add learn/, the process continues but fails to authenticate

**Comment by li-xinyang** [comment]
It is an on-demand course, all you need to do is to add a `--on-demand` flag.

```
coursera-dl --on-demand -u <USERNAME> -p <PASSWORD> ruby-on-rails-intro
```

You can find more options/flags using `coursera-dl --help`.

**Comment by balta2ar** [comment]
This should be fixed in 0.7.0.

**Comment by Jasonzming** [comment]
I have found the same issue today.
I get the following error:
C:\....\Python\Python35\Scripts>coursera-dl -
u <username> -p <userpassword> java-for-android
Downloading class: java-for-android
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Could not authenticate: Did not find necessary cookies.
What am I doing wrong?
Thanks!

**Comment by balta2ar** [comment]
@Jasonzming What's your version?
