### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by sondra-kinsey** [coursera-dl/coursera-dl#448]
I just ran git master of coursera-dl for the first time. It downloaded 2 1/2 classes worth of videos fine, but then I got this error message:

> Downloading: everyday-leadership-foundation/01_course-orientation/01_about-the-course/02_syllabus_url?u=https-3A__learner.coursera.help_hc_en-2dus_articles_207033333-2dspecialization-2dpayments&d=bqmfaq&MORE_ARGS
> Downloading https://urldefense.proofpoint.com/v2/url?u=https-3A__learner.coursera.help_hc_en-2Dus_articles_207033333-2DSpecialization-2DPayments&MORE_ARGS -> everyday-leadership-foundation/01_course-orientation/01_about-the-course/02_syllabus_url?u=https-3A__learner.coursera.help_hc_en-2dus_articles_207033333-2dspecialization-2dpayments&d=bqmfaq&MORE_ARGS
> Starting new HTTPS connection (1): urldefense.proofpoint.com
> Starting new HTTPS connection (1): learner.coursera.help
> Traceback (most recent call last):
>   File "./coursera-dl", line 6, in <module>
>     coursera_dl.main()
>   File "/home/lubuntu/Desktop/coursera-dl.git/coursera/coursera_dl.py", line 1056, in main
>     if download_class(args, class_name):
>   File "/home/lubuntu/Desktop/coursera-dl.git/coursera/coursera_dl.py", line 1034, in download_class
>     return download_on_demand_class(args, class_name)
>   File "/home/lubuntu/Desktop/coursera-dl.git/coursera/coursera_dl.py", line 1015, in download_on_demand_class
>     args.resume
>   File "/home/lubuntu/Desktop/coursera-dl.git/coursera/coursera_dl.py", line 528, in download_lectures
>     downloader.download(url, lecfn, resume=resume)
>   File "/home/lubuntu/Desktop/coursera-dl.git/coursera/downloaders.py", line 50, in download
>     self._start_download(url, filename, resume)
>   File "/home/lubuntu/Desktop/coursera-dl.git/coursera/downloaders.py", line 366, in _start_download
>     f = open(filename, 'ab') if resume else open(filename, 'wb')
> OSError: [Errno 36] File name too long: 'everyday-leadership-foundation/01_course-orientation/01_about-the-course/02_syllabus_url?u=https-3A__learner.coursera.help_hc_en-2dus_articles_207033333-2dspecialization-2dpayments&MORE_ARGS'
> [18:17:47]$awd~/Desktop/coursera-dl.git/$ 
> 

I replace some of the URL for `MORE_ARGS` because I don't know if it encodes login information. The replaced portion is ~175 characters, admittedly a very long filename.

I would be happy to test solutions to this bug.

**Comment by rbrito** [comment]
Dear @sondra-kinsey,

Since this was already reported on issue #414, could you please add your problems there? As this is a duplicate report, I am closing it or I am going to lose my mind...

I would sincerely appreciate it if you could keep following that issue with further information and testing solutions as we develop them.

Thanks in advance,

Rogério.
