### ISSUE TITLE
Bad request errors for courses every once in a while

### ISSUE THREAD

**Issue by deepakjois** [coursera-dl/coursera-dl#459]
```
> ~/courses/my-coursera/coursera/coursera-dl -n --aria2  -- internetgiants
…
Gathering subtitle URLs for video_id <WiOIexU7EeWg2CIAC9kAag>.
Gathering transcript URLs for video_id <WiOIexU7EeWg2CIAC9kAag>.
Gathering supplement URLs for element_id <v0HBs>.
Gathering supplement URLs for element_id <CaXvq>.
Gathering supplement URLs for element_id <OkQbT>.
Gathering supplement URLs for element_id <nxjpy>.
Gathering supplement URLs for element_id <GlMJe>.
Error 400 Client Error: Bad Request for url: https://www.coursera.org/api/onDemandSupplements.v1/V9_aHBU7EeWfzgpfp_iBVw~GlMJe?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 getting page https://www.coursera.org/api/onDemandSupplements.v1/V9_aHBU7EeWfzgpfp_iBVw~GlMJe?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29
HTTPError 400 Client Error: Bad Request for url: https://www.coursera.org/api/onDemandSupplements.v1/V9_aHBU7EeWfzgpfp_iBVw~GlMJe?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29

The user-provided path internetgiants does not exist.
```

If the parsing and gathering URL phase completes successfully, I have found that the course downloads fine almost all the time. But many times, it fails like above. It is not 100% reproducible, but I have seen it quite a few times to be annoying. Any clues why this might be happening?

**Comment by deepakjois** [comment]
Other courses I am seeing this quote often for:
* home-care
* learning-how-to-learn

**Comment by deepakjois** [comment]
I am seeing these kinds of errors for other courses as well. For, example, here is a portion of the output when downloading course  _gastronomy_

```
~/coursera/coursera/coursera-dl --debug -n --aria2  -- gastronomy
…
…<snipped>…
…
root[_get_asset_urls] Parsing JSON for asset_id <CxdUF-RGEeWZrBJBE6vaOQ>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/assets.v1/_Wb-t-RFEeWBDQ73-3lhaw HTTP/1.1" 400 32
root[get_page] Error 400 Client Error: Bad Request for url: https://www.coursera.org/api/assets.v1/_Wb-t-RFEeWBDQ73-3lhaw getting page https://www.coursera.org/api/assets.v1/_Wb-t-RFEeWBDQ73-3lhaw
root[main] HTTPError 400 Client Error: Bad Request for url: https://www.coursera.org/api/assets.v1/_Wb-t-RFEeWBDQ73-3lhaw
```

However, using `curl` seems to return a valid result:
```
$> curl https://www.coursera.org/api/assets.v1/_Wb-t-RFEeWBDQ73-3lhaw

{"elements":[{"id":"_Wb-t-RFEeWBDQ73-3lhaw","name":"SCIGAST 9.3.pdf","typeName":"generic","url":{"url":"https://d3c33hcgiwev3.cloudfront.net/_191e0ecf1aa845e9022433bf7236a4a7_SCIGAST-9.3.pdf?Expires=1459382400&Signature=Bu6DpFRqA7mWXwFYAjRi3RQo7mzrL6QGC~Ge68zgMowCwpxnpW2fJuZBfUR2qAveOoy2lCf~d2HP6PA1ygB~fQ0ybhWFTC58sCKzU0vPE3DFHGbLMs-0tVMonZ-4Wh8ER5k2vJMGG3nUtvTAn9TGkDWvn93OmuQylcm1ZuceTbY_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A","expires":1459382400000}}],"paging":null,"linked":null}
```

Any clues as to what might be causing this?

**Comment by balta2ar** [comment]
@deepakjois Does this persist? Maybe those were temporarily Coursera platform issues which you unluckily happened to witness.

**Comment by balta2ar** [comment]
I started to get this replies too today when I was testing the script. I don't know about your pattern, but my frequent requests can easily be classified as anomaly/service abuse. I presume they may have some protection against insistent visitors. But that's just a wild guess.

**Comment by deepakjois** [comment]
It happens to me for some courses when I try to run coursera-dl inside AWS. Maybe it is the high bandwidth connection that triggers it, because then the ‘gathering’ happens really fast, and there is some sort of rate limiting going on. Adding retries with some sort of delay or sleep might help.

**Comment by deepakjois** [comment]
Another guess is that it is happening for courses that have a large number of resources, which need to be ‘gathered’, thus triggering the rate-limiting.

**Comment by deepakjois** [comment]
I don’t have definitive answers, but I did some more investigation and made some progress that I wanted to document here:

I have noticed a couple of things - 
1. This happens more when the number of assets for a course is very large.
2. This happens more when I am on a high bandwidth connection which means HTTP requests are happening faster.

One smoking gun is a lot of messages in the log which say: `Resetting dropped connection: www.coursera.org`. This indicates that connections that are (maybe) being kept alive by the urllib3 connection pool are being closed by Coursera, and are being re-established by urllib3. This is an indication of some sort of rate-limiting/abuse prevention logic. 

I decided to add a delay in the `get_page` method in network.py by doing:

```
sleep(0.2)
```

I tried values from 0.05 (50ms)  to 0.2(200ms), and 0.2 worked best and caused the least problems.

Another option that I have not tried is that we could consider disabling keepalive in `get_session` method in coursera_dl.py by doing:

```
session.keep_alive = false
```

Maybe a combination of adding a delay (maybe specified by a CLI flag) and disabling keep-alive might help solve this problem.

**Comment by balta2ar** [comment]
Ugh... I really don't want to bloat the script with a gazillion of flags... Let's sleep on it.

I'd really appreciate If you could check whether disabling keep-alive helps anyhow.

**Comment by deepakjois** [comment]
> Ugh... I really don't want to bloat the script with a gazillion of flags... Let's sleep on it.

Yes absolutely. I wasn’t suggesting actually making the change. It’s not the preferred option. We really need more information about what is happening in the background exactly. Need some deeper investigation using wireshark to figure out who is dropping connections and why. I will do that when I find the time. I will also check if disabling keep-alive helps.

**Comment by deepakjois** [comment]
> I'd really appreciate If you could check whether disabling keep-alive helps anyhow.

I can confirm that disabling keep-alive definitely does not help. I can also say with more confidence (after downloading several courses with the `sleep` as mentioned above) that adding a delay is by far the most reliable mechanism for me to not see this behavior.

**Comment by balta2ar** [comment]
Thank you for your efforts, @deepakjois! Does it mean we can forget about parsing syllabus in parallel?

**Comment by deepakjois** [comment]
Just to update this bug report…I have been downloading a lot of courses with the latest code recently, and this problem is not occuring anymore. It seems to have been fixed automagically with the whatever is the new way to establish connections and make requests. Or maybe something on Coursera side managed to fix a regression.

I believe this can be closed.

**Comment by rbrito** [comment]
Thanks @deepakjois. I'm closing then.
