### ISSUE TITLE
Feature Request: Speed Limit

### ISSUE THREAD

**Issue by djdylan2000** [coursera-dl/coursera-dl#464]
It would really be useful to have an option to limit the download rate when downloading course videos. For example, I might keep my raspberry pi on to download videos, but wouldn't want it to consume the entire internet bandwidth. wget has a _--limit-rate <rate>_ option, so an option could be passed on from the top level if wget is selected as the downloader by the user.

**Comment by balta2ar** [comment]
You can do that. According to the documentation wget reads `.wgetrc` file where you can put bandwidth-limiting opitons: https://ftp.gnu.org/old-gnu/Manuals/wget-1.8.1/html_chapter/wget_6.html.

**Comment by balta2ar** [comment]
Usage:
```
coursera-dl --aria --downloader-arguments='--max-download-limit=5K' -n --path . <course_name>
coursera-dl --wget --downloader-arguments='--limit-rate=5k' -n --path . parprog1 <course_name>
```
