### ISSUE TITLE
Problem in course download, unnecessary character attached to url

### ISSUE THREAD

**Issue by dareTake** [coursera-dl/coursera-dl#466]
The program seems to attach some unneeded characters at the end of the class name [%0D]. 
Fyi, there were no white spaces when I use the command. 

Is the problem happening with the latest version of the script?
Yes

What operating system are you using?
OSX 10.11

Do you have all the recommended versions of the modules? See them in the file requirements.txt.
Yes

What is the course that you are trying to access?
[angular-js](https://www.coursera.org/learn/angular-js/)

What is the precise command line that you are using (feel free to hide your username and password with asterisks, but leave all other information untouched).
`coursera-dl -n -f "mp4 ppt pdf srt" --resume angular-js`

What are the precise messages that you get? Please, use the --debug option before posting the messages as a bug report. Please, copy and paste them. Don't reword/paraphrase the messages.

[debug.txt](https://github.com/coursera-dl/coursera-dl/files/187837/debug.txt)

**Comment by balta2ar** [comment]
I can't reproduce the issue. I've downloaded the course just fine. Try manually typing course name in the command line, not copy-paste it.
