### ISSUE TITLE
Issue using pip on osx el capitan

### ISSUE THREAD

**Issue by codiceexerceo** [coursera-dl/coursera-dl#471]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
I can't seem to upgrade six 1.4.1

### Your environment
* Operating System (name/version):
* Python version: 2.7.11
* coursera-dl version: how do you check for the version?

### Steps to reproduce
pip install coursera
Requirement already satisfied (use --upgrade to upgrade): coursera in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4>=4.1.3 in /Library/Python/2.7/site-packages (from coursera)
Collecting html5lib>=1.0b2 (from coursera)
  Using cached html5lib-1.0b8.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests>=2.4.3 in /Library/Python/2.7/site-packages (from coursera)
Collecting six>=1.5.0 (from coursera)
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): urllib3>=1.10 in /Library/Python/2.7/site-packages (from coursera)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /Library/Python/2.7/site-packages (from coursera)
Requirement already satisfied (use --upgrade to upgrade): keyring>=4.0 in /Library/Python/2.7/site-packages (from coursera)
Installing collected packages: six, html5lib
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 726, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 746, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/5f/dw9cs7454qz7hxv3ctv15fz80000gn/T/pip-Alxlnv-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

**Comment by xielingwang** [comment]
DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
.....
OSError: [Errno 1] Operation not permitted
===========================
Above means that you do not allow to uninstall a project from a system-built version.
Try pyenv or virtualpython to install a independent version of python and try to install coursera-dl again.

**Comment by balta2ar** [comment]
Or try installing into user directory:

```
pip install --upgrade --user coursera
```
