### ISSUE TITLE
[update-pip] Cannot download on-demand course

### ISSUE THREAD

**Issue by Stef3478** [coursera-dl/coursera-dl#474]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
I cannot download the on-demand course intro-to-big-data (https://www.coursera.org/learn/intro-to-big-data/home/welcome , I have enrolled the course). The script cannot find the course:

$ coursera-dl -u username -p password intro-to-big-data
Coursera-dl v3.1.1 (html.parser)
Logging in as 'username'...
Traceback (most recent call last):
  File "/Users/stef/anaconda/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()
  File "/Users/stef/anaconda/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 648, in main
    d.login(args.course_names[0])
  File "/Users/stef/anaconda/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 136, in login
    raise Exception("Unknown class %s" % className)
Exception: Unknown class intro-to-big-data

### Your environment
* Operating System (name/version): macosx
* Python version: 2.7
* coursera-dl version: 3.1.1

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

**Comment by Stef3478** [comment]
Ok, the problem was resolved by using the cloning the git code instead of using pip, as mentioned in other closed cases.
Perhaps it is an idea to update the pip package, or removing it, or mention it in the troubleshoot section?
Keeping it open for other dummies like me who didn't check the closed issues :-)

**Comment by balta2ar** [comment]
@rbrito I'm sorry to annoy you, but we really need to do something with pip... Is there a chance I could update pip (pypi) as well? That would avoid a lot of frustration among our users...

**Comment by balta2ar** [comment]
Pip package is up to date now. Closing.
