### ISSUE TITLE
[shorten-filenames] automatic shortening of long path names

### ISSUE THREAD

**Issue by maxshat** [coursera-dl/coursera-dl#476]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
If path name is to long it is not possible to download course on Windows systems. Is it possible to implement some automatical path shortening while download is in progress?

### Your environment
* Operating System (name/version): Windows
* Python version: 3.5
* coursera-dl version: latest

### Steps to reproduce
Try to donwload course: country-level-economics 

### Expected behaviour
Folder path is shortened automatically to comply with windows requirements

### Actual behaviour
Path is not found.

**Comment by quevedin** [comment]
Same error here, both with python2.7 and 3.5.

**Comment by LouiseMatthews** [comment]
@maxshat @quevedin - it would be useful to know if this patch fixes the problem for you?
