### ISSUE TITLE
Please, review our tentative Release Notes

### ISSUE THREAD

**Issue by rbrito** [coursera-dl/coursera-dl#482]
Dear people,

This time, I would like to be better at announcing the new release of coursera-dl and I wrote a draft of some release notes at:

https://github.com/coursera-dl/coursera-dl/wiki/First-%28Tentative%29-Release-Notes

Could anybody lend a hand there? I would like to spread the word on as many channels as possible (ideas welcome, but the first thing that comes to mind is my twitter account and, possibly, some Python-related groups on Facebook).

I would love it if you could have a look and see if I missed something. I also want to release the software more often and write more release notes.

Oh, BTW, when I way "I want to", I would like to be inclusive and have the names of the contributors (@balta2ar, @iemejia and others) listed at the bottom of the document.

Please, review what you can. It will be awesome to have great releases and close as many bugs as possible.

Thanks,

Rogério Brito.

**Comment by balta2ar** [comment]
Thank you for your efforts, @rbrito! I have a couple of comments about the release.

> A new logo!
Improved test suite for the program.
Continued improvement to the modularization of the program (which makes easier to maintain the code).
Excellent new contributors, with strong knowledge! Please see them all by visiting: https://github.com/coursera-dl/coursera-dl/graphs/contributors
Fun fact: we broke the barrier of 2900 stars and 1000 forks on GitHub!

@rbrito, I totally understand your enthusiasm, so I'm really uncomfortable saying this, please pardon my ignorance, but I've always felt more pragmatic about release notes. As a user, I've always wanted to see user-visible changes in release notes. I don't think it matters to our users how many stars we have or that our program is modular or anything at all of our internal kitchen. What matters is whether the program is doing its job, what functionality has been added and what bugs have been fixed. For this reason, I would have removed anything not directly related to user experience from release notes. Sorry, that's just my humble opinion.

> I would like to be inclusive and have the names of the contributors

Sure, feel free to list my name.

> Important Note: Yes, while the program is called coursera-dl, to install the package you need to use coursera like above, not coursera-dl. This is very important!

This inconvenience both for us and our users has been following us for long. Could we approach @abhirama (the author of `coursera-dl` on pip), appeal to his benevolence and ask him nicely whether he could spare pip's `coursera-dl` name for our project? His version is abandoned long time ago and this difference in names is really confusing users. What do you think?

**Comment by balta2ar** [comment]
I provide CHANGELOG.md after every significant change. Also, when git tag is set, I put changelog into the commit message so that it can be seen in the Releases page.
Closing for now.

**Comment by rbrito** [comment]
Thanks a lot @balta2ar!
