### ISSUE TITLE
when password has non-alphanumeric characters it fails to login

### ISSUE THREAD

**Issue by fogine** [coursera-dl/coursera-dl#484]
### Subject of the issue
refer to the title of the issue

### Your environment
Operating System (name/version): Ubuntu 14.04.4
Python version: 3.4.3
coursera-dl version: 0.5.2

### Steps to reproduce
Change your coursera password so that it contains "special" characters (non-alphanumerical), then try to login. 
ps.: when I changed my password to alphanumerical characters only, login passed through...

### UPDATE

Not sure if the bug applies strictly for non-alphanumerical passwords, I'm not comfortable sharing the particular characters which cause a login to fail. The characters are part of ASCII table

Command and its output:

````bash
coursera-dl --on-demand --path "/media/username/Seagate Expansion Drive/Tutorial/coursera" -u "email@email.com" -p "password" "practical-machine-learning" --debug            
                                                                                   
root[main] --on-demand option is deprecated and is not required anymore. Do not use this option. It will be removed in the future.
root[main] Downloading class: practical-machine-learning
root[download_class] Downloading old style class practical-machine-learning
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file /tmp/user/1000/username_coursera_dl_cache/cookies/email@email.com.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /practical-machine-learning HTTP/1.1" 404 None
root[login] 404 Client Error: Not Found for url: https://class.coursera.org/practical-machine-learning
root[download_class] Downloading new style (on demand) class practical-machine-learning
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[login] Forging cookie header: csrftoken=l8dR0h1Ms91Zo1BwS895; csrf2_token_oW1U9x0P=8iIj4mgib19tJ5wjaXPRrfCB.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 401 None
root[main] Could not authenticate: Cannot login on coursera.org.
````

**Comment by 5j9** [comment]
My password contains all of these characters and I have no problem logging in:
```
!$%&*@^
```
Of-course I'm using a Windows machine. You may want to have a look at this SO question: [Which characters need to be escaped in Bash?](http://stackoverflow.com/questions/15783701/which-characters-need-to-be-escaped-in-bash-how-do-we-know-it)

**Comment by fogine** [comment]
Ok, thank you @5j9 , one unusual escape method and only the one from the referenced SO question has worked and authentication passed.

**Comment by x-ji** [comment]
Or one may use single quotes to escape the passwords on a Unix system.
