### ISSUE TITLE
HTTPError 404 Client Error: Not Found for url: https://api.coursera.org/api/catalog.v1/courses/...

### ISSUE THREAD

**Issue by adio88** [coursera-dl/coursera-dl#491]
Hi!

I was trying to download the video lectures for a course on the "old" platform: https://class.coursera.org/progfun-005 , but with little luck:

Installation went fine:

> **adrian@mintPC:/m/S/coursera/progfun > pip3 install --user coursera** 
> Downloading/unpacking coursera
>   Downloading coursera-0.5.2.tar.gz (54kB): 54kB downloaded
>   Running setup.py (path:/tmp/pip_build_adrian/coursera/setup.py) egg_info for package coursera
>     
> Downloading/unpacking beautifulsoup4>=4.1.3 (from coursera)
>   Downloading beautifulsoup4-4.4.1-py3-none-any.whl (81kB): 81kB downloaded
> Downloading/unpacking html5lib>=1.0b2 (from coursera)
>   Downloading html5lib-1.0b8.tar.gz (889kB): 889kB downloaded
>   Running setup.py (path:/tmp/pip_build_adrian/html5lib/setup.py) egg_info for package html5lib
>     
> Requirement already satisfied (use --upgrade to upgrade): requests>=2.4.3 in /usr/local/lib/python3.4/dist-packages (from coursera)
> Requirement already satisfied (use --upgrade to upgrade): six>=1.5.0 in /usr/local/lib/python3.4/dist-packages (from coursera)
> Downloading/unpacking urllib3>=1.10 (from coursera)
>   Downloading urllib3-1.15.1-py2.py3-none-any.whl (92kB): 92kB downloaded
> Downloading/unpacking pyasn1>=0.1.7 (from coursera)
>   Downloading pyasn1-0.1.9-py2.py3-none-any.whl
> Downloading/unpacking keyring>=4.0 (from coursera)
>   Downloading keyring-9.0-py2.py3-none-any.whl
> Installing collected packages: coursera, beautifulsoup4, html5lib, urllib3, pyasn1, keyring
>   Running setup.py install for coursera
>     
>   Installing coursera-dl script to /home/adrian/.local/bin
>   Running setup.py install for html5lib
>     
> Successfully installed coursera beautifulsoup4 html5lib urllib3 pyasn1 keyring
> Cleaning up..

...but...

> **adrian@mintPC:/m/S/coursera/progfun > coursera-dl --debug -u xxxx -p xxxx "progfun-005"**
> root[main] Downloading class: progfun-005
> root[download_class] Downloading old style class progfun-005
> root[get_cookies_from_cache] Trying to get cookies from the cache.
> root[load_cookies_file] Loading cookie file /tmp/adrian_coursera_dl_cache/cookies/xxxx.txt into memory.
> root[get_cookies_from_cache] Loaded cookies from /tmp/adrian_coursera_dl_cache/cookies/xxxx.txt
> requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
> requests.packages.urllib3.connectionpool[_make_request] "HEAD /progfun-005/class HTTP/1.1" 302 0
> root[validate_cookies] Stale session.
> root[login] Initiating login.
> root[login] There were no .coursera.org cookies to be cleared.
> requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
> requests.packages.urllib3.connectionpool[_make_request] "GET /progfun-005 HTTP/1.1" 302 None
> root[login] Forging cookie header: csrftoken=MV1SrTDXWm9uFXzLmyXX; csrf2_token_nVvBMb2t=Kn3OC000rrM2EHyF6Qa0AOu0.
> requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
> requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 200 None
> root[login] Logged in on coursera.org.
> requests.packages.urllib3.connectionpool[_make_request] "GET /progfun-005/auth/auth_redirector?type=login&subtype=normal HTTP/1.1" 302 None
> requests.packages.urllib3.connectionpool[_make_request] "GET /progfun-005/class HTTP/1.1" 302 None
> requests.packages.urllib3.connectionpool[_make_request] "GET /progfun-005/ HTTP/1.1" 301 None
> requests.packages.urllib3.connectionpool[_make_request] "GET /progfun-005 HTTP/1.1" 200 None
> root[down_the_wabbit_hole] Following https://class.coursera.org/progfun-005/auth/auth_redirector?type=login&subtype=normal to authenticate on class.coursera.org.
> root[down_the_wabbit_hole] Exiting "deep" authentication.
> root[get_authentication_cookies] Found authentication cookies.
> root[download_about] About file to be written to: progfun-005-about.json
> root[download_about] About url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=progfun
> root[download_about] Downloading about page from: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=progfun
> requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org
> requests.packages.urllib3.connectionpool[_make_request] "GET /api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=progfun HTTP/1.1" 404 None
> root[get_page] Error 404 Client Error: Not Found for url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=progfun getting page https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=progfun
> root[main] HTTPError 404 Client Error: Not Found for url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=progfun

I tried wget-ting the above URL and it actually works, giving me a large json response.

Any help would be very much appreciated!

**Comment by balta2ar** [comment]
@adio88 I'm afraid they configured unconditional redirection to the new OnDeamand course. At least I cannot even open it in the browser, thus it can't be downloaded. Consider enrolling to the new course, it should be very similar.

**Comment by oliyiyi** [comment]
I have the same problem.
