### ISSUE TITLE
Password complexity issue

### ISSUE THREAD

**Issue by vkaracic** [coursera-dl/coursera-dl#50]
When I first tried this script with the -u and -p args I get an error:

bash: !an < rest of the password >: event not found

When I tried with the .netrc file I get a bad cookie or wrong credentials error, even though they were right. This is when I wanted to post the issue but I went through the code and found these lines:

```
if args.username and not args.password and not args.netrc:
  args.password = getpass.getpass("Coursera password for %s: " % args.username)
```

so I just entered my username via -u and the name of the class without my password, I got the prompt for the password, after entering it the download started normally. So I guess there is a problem with parsing the complex passwords - I'm not much of a coder so I'm not sure what exactly is an issue, hopefully you guys will know and improve this script! 

Good script, it's a life savior! Cheers! :)

**Comment by mrb1778** [comment]
I did not get the quoting to work or the .netrc, but i did get the conf file to work
coursera-dl.conf
