### ISSUE TITLE
[windows] "failed to create process."

### ISSUE THREAD

**Issue by cpoptic** [coursera-dl/coursera-dl#500]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
"failed to create process." when i run coursera-dl from command line terminal

### Your environment
* Operating System (name/version): Windows 10
* Python version: 3.5.1
* coursera-dl version: 0.5.2

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script? I downloaded the most recent version so I believe so.
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
I manually ran "pip show <package>" for all 7 of the dependencies listed in requirements.txt and they all meet or exceed the version requirement.
* What is the course that you are trying to access? multiple.  They all failed to run.  pgm-003, among others.
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).  `coursera-dl` --version` returns error message "

> failed to create process.

"
Running `pip show coursera-dl`  returns nothing and simply returns an empty prompt.
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.    Simply returns:

> failed to create process.

### Expected behaviour
Tell us what should happen.  I should at least get the version of coursera-dl

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

actual behavior is it simply returns the error message "failed to create process."

**Comment by balta2ar** [comment]
@cpoptic Could you make a screenshot? I've never seen anything like that before.

**Comment by cpoptic** [comment]
![coursera course downloader error screenshot](https://cloud.githubusercontent.com/assets/7234261/16091276/f159c0ce-3300-11e6-94f6-15e1924a4f4c.png)

**Comment by cpoptic** [comment]
![coursera course downloader error screenshot](https://cloud.githubusercontent.com/assets/7234261/16091330/248b3a72-3301-11e6-95e7-5871cdefe292.png)

**Comment by balta2ar** [comment]
@cpoptic That's weird... Could you try putting your password into double quotes?
Also, pip version is outdated and buggy. Please use the latest github version.

**Comment by vishalgakhare** [comment]
The "coursera-dl" process won't launch. Details are same as provided by the initial submitter:
![image](https://cloud.githubusercontent.com/assets/10359853/16104487/d7ca4a4e-334f-11e6-8af4-480ef1003368.png)

**Comment by vishalgakhare** [comment]
pip version is little behind but that should be find.
![image](https://cloud.githubusercontent.com/assets/10359853/16104521/1a6c39ca-3350-11e6-9c17-111a1ce5cee4.png)

**Comment by balta2ar** [comment]
Judging from what I've quickly found on the Internet, this might be a setuptools bug. Need to look into that.

For the moment, could you make sure path to your Python installation does not contain spaces? For example, if your python is installed into "C:\Program Files\Python 3.5", could you reinstall it into, say, "C:\Python3.5" and see if that helps?

**Comment by lorendunlop** [comment]
in
C:\Users\<user>\AppData\Local\Programs\Python\Python35-32\Scripts

or wherever python installed (above is default for windows)

edit below file in idle:

coursera-dl-script

from

#!c:\users\loren dunlop\appdata\local\programs\python\python35-32\python.exe

to

#"!c:\users\loren dunlop\appdata\local\programs\python\python35-32\python.exe"

(add quotes)

**Comment by balta2ar** [comment]
@lorendunlop Thank you! That's definitely worth adding to the README.

**Comment by cpoptic** [comment]
@lorendunlop Thanks so much!  This solved the issue for my config.  I'm guessing it's related to the Python.exe path having spaces in it.  The double quotes around the full pathname fixed it.
