### ISSUE TITLE
command to be issued

### ISSUE THREAD

**Issue by GitHubAnatta** [coursera-dl/coursera-dl#501]
is this command line correct?!
coursera hiphen dl hiphen username hiphen password hiphen course name

if so, i have two issues!
my username is my email address, and it has 'at', whihc seems to be not acceptable?
Secondly my password has '!', and it seems not to be acceptable.
Please help me understand the correct command!
Thanks.

**Comment by RayBB** [comment]
Here is an example of what the command should look like
`coursera-dl -u email@example.com -p password class-name`

There shouldn't be a problem with an !

**Comment by balta2ar** [comment]
@GitHubAnatta Just in case, put both your username and your password into double quotes.

**Comment by GitHubAnatta** [comment]
Many thanks to you both -RayBB and balta2ar.  Cheers.
