### ISSUE TITLE
Course Code Extractor Script

### ISSUE THREAD

**Issue by RayBB** [coursera-dl/coursera-dl#503]
### Subject of the issue

I do not have an issue but I would like to share the script I wrote to extract name for use with coursera-dl. [Link to github code](https://github.com/RayBB/coursera-slug-extractor).
Basically, you just past it into the console of the coursera page and it will give you a list of all courses on the old coursera platform to easily be downloaded.

I hope the creators of this will add a feature like this in the future but for now this works.

**Comment by balta2ar** [comment]
Thank you! We appreciate your input! Actually, it might be a good idea to have this functionality built-in. For example, edx-dl has --list-courses option to list all courses that you are enrolled to.

**Comment by balta2ar** [comment]
Related: #514
