### ISSUE TITLE
Found 0 sections and 0 lectures on this page

### ISSUE THREAD

**Issue by celsom3** [coursera-dl/coursera-dl#506]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Not finding any sections or lectures to download

### Your environment
* Operating System (name/version): OXS El Capitan 10.11.5 (15F34)
* Python version: 3.5.1
* coursera-dl version: 0.6.0

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you: Created a virtualenv, followed the tutorial:

`virtualenv -p python3 my-coursera`
`cd my-coursera`
`source bin/activate`
`git clone https://github.com/coursera-dl/coursera-dl`
`cd coursera`
`pip install -r requirements.txt`
.`/coursera-dl ...`

* Is the problem happening with the latest version of the script? Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. Yes
* What is the course that you are trying to access? https://www.class-central.com/mooc/385/coursera-learn-to-program-the-fundamentals (code is programming1-002)
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched). ./coursera-dl -u ****** -p ****** musictheory-001 --clear-cache
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

root[main] coursera_dl version 0.5.2
root[main] Downloading class: musictheory-001
root[download_class] Downloading old style class musictheory-001
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file /var/folders/bt/7x1jgqy51dnb2lhy_0cbknv80000gn/T/celso_coursera_dl_cache/cookies/celso.mireles@gmail.com.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /musictheory-001 HTTP/1.1" 302 None
root[login] Forging cookie header: csrftoken=bvepjodqr1qVAx5OtHlj; csrf2_token_BujtouCi=v9HLK5r8gCvqwYmaTJEsJUYb.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /musictheory-001/auth/auth_redirector?type=login&subtype=normal HTTP/1.1" 302 None
requests.packages.urllib3.connectionpool[_make_request] "GET /course/musictheory HTTP/1.1" 200 None
root[down_the_wabbit_hole] Following https://class.coursera.org/musictheory-001/auth/auth_redirector?type=login&subtype=normal to authenticate on class.coursera.org.
root[down_the_wabbit_hole] Exiting "deep" authentication.
root[get_authentication_cookies] Found authentication cookies.
root[download_about] About file to be written to: musictheory-001-about.json
root[download_about] About url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=musictheory
root[download_about] Downloading about page from: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=musictheory
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=musictheory HTTP/1.1" 200 None
root[download_old_style_class] Subtitle unavailable in specified language
root[get_syllabus_url] Using index mode with page: https://class.coursera.org/musictheory-001/lecture/index
requests.packages.urllib3.connectionpool[_make_request] "GET /musictheory-001/lecture/index HTTP/1.1" 301 None
requests.packages.urllib3.connectionpool[_make_request] "GET /musictheory-001/lecture HTTP/1.1" 302 None
requests.packages.urllib3.connectionpool[_make_request] "GET /course/musictheory HTTP/1.1" 200 None
root[get_old_style_syllabus] Downloaded https://class.coursera.org/musictheory-001/lecture/index (1150397 bytes)
root[parse_old_style_syllabus] Found 0 sections and 0 lectures on this page
root[parse_old_style_syllabus] The cookies file may be invalid, please re-run with the `--clear-cache` option.

### Expected behaviour
Tell us what should happen.

The course should download.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

The course doesn't download. Here is the output with the --debug option:

root[main] coursera_dl version 0.5.2
root[main] Downloading class: musictheory-001
root[download_class] Downloading old style class musictheory-001
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file /var/folders/bt/7x1jgqy51dnb2lhy_0cbknv80000gn/T/celso_coursera_dl_cache/cookies/celso.mireles@gmail.com.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /musictheory-001 HTTP/1.1" 302 None
root[login] Forging cookie header: csrftoken=bvepjodqr1qVAx5OtHlj; csrf2_token_BujtouCi=v9HLK5r8gCvqwYmaTJEsJUYb.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /musictheory-001/auth/auth_redirector?type=login&subtype=normal HTTP/1.1" 302 None
requests.packages.urllib3.connectionpool[_make_request] "GET /course/musictheory HTTP/1.1" 200 None
root[down_the_wabbit_hole] Following https://class.coursera.org/musictheory-001/auth/auth_redirector?type=login&subtype=normal to authenticate on class.coursera.org.
root[down_the_wabbit_hole] Exiting "deep" authentication.
root[get_authentication_cookies] Found authentication cookies.
root[download_about] About file to be written to: musictheory-001-about.json
root[download_about] About url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=musictheory
root[download_about] Downloading about page from: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=musictheory
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=musictheory HTTP/1.1" 200 None
root[download_old_style_class] Subtitle unavailable in specified language
root[get_syllabus_url] Using index mode with page: https://class.coursera.org/musictheory-001/lecture/index
requests.packages.urllib3.connectionpool[_make_request] "GET /musictheory-001/lecture/index HTTP/1.1" 301 None
requests.packages.urllib3.connectionpool[_make_request] "GET /musictheory-001/lecture HTTP/1.1" 302 None
requests.packages.urllib3.connectionpool[_make_request] "GET /course/musictheory HTTP/1.1" 200 None
root[get_old_style_syllabus] Downloaded https://class.coursera.org/musictheory-001/lecture/index (1150397 bytes)
root[parse_old_style_syllabus] Found 0 sections and 0 lectures on this page
root[parse_old_style_syllabus] The cookies file may be invalid, please re-run with the `--clear-cache` option.

**Comment by balta2ar** [comment]
Are you sure you are enrolled to the old version of the course and you have accepted the term (you do that upon your first visit of the course)? I can download this course just fine.

**Comment by balta2ar** [comment]
Did you try this? https://github.com/coursera-dl/coursera-dl/issues/300#issuecomment-68147829

**Comment by rjcantrell** [comment]
I'm having the same issue, but only for courses not accepting new enrollments. For all those allowing enrollment, enrolling in the class (and signing the honor code) correctly pulls down the lecture list.

Should I expect the script to work for classes not allowing new enrollments? Class-central suggests that it can, but I don't think there's a way to pull down the list of lectures without enrollment.

**Comment by balta2ar** [comment]
I'm afraid, enrollment is requirement. At least with our current grabbing algorithm.

> Class-central suggests that it can

How? Could you share the link, please?

**Comment by rbrito** [comment]
As far as I remember, you can download the videos with the program if you have, at least, the index file that lists all the course materials and use the `--process_local_page` option.

You also have the option of not enrolling and grabbing the videos from courses that provide previews, with the `--preview` option.

**Comment by balta2ar** [comment]
@rbrito Thanks for the clarification! I haven't looked thoroughly at old-style parsing code, so you definitely know it better than I do.

**Comment by celsom3** [comment]
@balta2ar You are right, I just needed to enroll in the courses. Thanks so much for clarifying!

**Comment by celsom3** [comment]
Closing as this was just a matter of enrolling in the courses before running the script to download. A classic case of not carefully reading the [Troubleshooting](https://github.com/coursera-dl/coursera-dl/#troubleshooting) section. Sorry about that.

**Comment by rjcantrell** [comment]
@balta2ar 

> How? Could you share the link, please?

https://www.class-central.com/report/coursera-old-platform-shutdown-download-courses/

Sadly, I assume it's just outdated or misinformed.

> OPTION 2B: PYTHON SCRIPT
> 
> This option is a bit more complicated, but if you can get through the setup process is the best option as it allows you to download all the courses that are hosted on the old platform, and not just the ones currently open for enrollment.

**Comment by rbrito** [comment]
@rjcantrell, no it is not misinformed. Coursera actually disabled a bunch of old-style courses over the years. And some "classics" are going away soon, like all of Jeff Ullman's. :(

And, actually, the kind people on Class Central even gave John and me some credits. @balta2ar, do you have any Twitter account? If you have, I can ask them to give you the proper recognition. They are super nice!

**Comment by rjcantrell** [comment]
@rbrito So, is there a way to download the following classes that aren't accepting new enrollments (and, I'm assuming, will not do so before being deleted on 6/30)?

neurobio-002
bibrain-003
neuromarketing-001
sleep-005

I've never enrolled in any of these in the past, so I don't have a local version of the lecture list to work from. Even if not, thanks for your work on this neat script! This definitely saved me many hours of manual downloading!

**Comment by balta2ar** [comment]
> do you have any Twitter account? If you have, I can ask them to give you the proper recognition.

Thanks, @rbrito, I'm fine :)
