### ISSUE TITLE
Issue with Downloading. 

### ISSUE THREAD

**Issue by OkeepTooth** [coursera-dl/coursera-dl#507]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
I'm having issues setting up and downloading classes, in the end of the guide it also says you need to register for classes but it also says that the python script is good if you haven't registered. 

### Your environment
Windows 8.1
* Python version:3.5.1
* coursera-dl version: 4.0? I just entered the command pip install coursera

### Steps to reproduce
The first thing I did was open windows command prompt, then i typed" pip install coursera " after that i typed " coursera-dl -u <myusernamehere> -p <mypasswordhere> machlearning-001 "

* Is the problem happening with the latest version of the script? N/a
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. I did the command "pip install -r requirements txt" and the other version of it
* What is the course that you are trying to access? machlearning-001
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched). "coursera-dl -u <myusernamehere> -p <mypasswordhere> machlearning-001"
* What are the precise messages that you get? Please, use the `--debug` "The System cannot find the file specified"
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
The course is downloaded. 

### Actual behaviour
Nothing happened. Except the error message.

**Comment by balta2ar** [comment]
As suggested here https://github.com/coursera-dl/coursera-dl/issues/506#issuecomment-226838450, try using `--preview` option.

**Comment by OkeepTooth** [comment]
Balta2ar would i do --preview as one command then the other command?

**Comment by balta2ar** [comment]
@OkeepTooth As one command as follows:
```
coursera-dl --preview -u -p machlearning-001
```

**Comment by balta2ar** [comment]
Outdated. Old courses are not supported anymore.
