### ISSUE TITLE
html file name length problem with windows

### ISSUE THREAD

**Issue by rishabhgpt** [coursera-dl/coursera-dl#510]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
While downloading html file of enormous length like:
installing-octave-matlab-on-mac-os-x-10-10-yosemite-and-10-9-mavericks-and-later.html
windows doesn't allows to create file and download stops with No such file or directory exception
### Your environment
* Operating System (name/version): Windows 7, Pro
* Python version: 2.7
* coursera-dl version:

### Steps to reproduce
Try downloading Andrew Ng's ML class 
* Is the problem happening with the latest version of the script? yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. yes
* What is the course that you are trying to access?machine-leanrning
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
coursera-dl.bat -u -p machine-learning
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.
Should have modified max name length of windows before trying to create html
### Actual behaviour
script fails with no such file or directory exception

**Comment by balta2ar** [comment]
@rishabhgpt Try updating to the very latest version. I committed the fix 3 hours ago.

**Comment by rishabhgpt** [comment]
sure.. btw thanks for your effort. this has proven to be true savior when coursera is going for complete revamp

**Comment by rishabhgpt** [comment]
Closing issue as fix has been verified.!

**Comment by rbrito** [comment]
Yes, @balta2ar is doing an excellent work! Thanks a lot, Yuri.
