### ISSUE TITLE
Issue with downloading from active course!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [coursera-dl/coursera-dl#511]
http://hastebin.com/efukixuzab.tex

The course in question is:
https://www.coursera.org/learn/interactive-python-1/home/welcome

However, downloading https://www.coursera.org/learn/interactive-python-2/home/welcome works just fine.

**Comment by balta2ar** [comment]
You're using outdated version from "coursera" pip package. Please either use version from github or switch to "coursera-dl" pip package version 0.6.0.
