### ISSUE TITLE
Unable to find valid encrypted netrc file

### ISSUE THREAD

**Issue by amadib** [coursera-dl/coursera-dl#513]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.
### Subject of the issue

Unable to find valid netrc file (_netrc on windows)
### Your environment
- Operating System (name/version): Windows 10 (Preview)
- Python version: python3
- coursera-dl version: coursera-dl==0.6.0
### Steps to reproduce

```
>coursera-dl posa-002 -n
```
### Expected behaviour

Should be able to find the `_netrc` file
### Actual behaviour

```
Did not find valid netrc file:
[Errno 2] No such file or directory: 'C:\\Users\\username\\.netrc'
bad follower token 'protocol' (C:\Users\username\_netrc, line 12)
[Errno 2] No such file or directory: 'C:\\Users\\username\\.netrc'
bad follower token 'protocol' (C:\Users\username\_netrc, line 12)
[Errno 2] No such file or directory: 'C:\\Users\\username\\.netrc'
bad follower token 'protocol' (C:\Users\username\_netrc, line 12)
[Errno 2] No such file or directory: 'C:\\.netrc'
[Errno 2] No such file or directory: 'C:\\_netrc'
[Errno 2] No such file or directory: 'C:\\.netrc'
[Errno 2] No such file or directory: 'C:\\_netrc'
[Errno 2] No such file or directory: '\\.netrc'
[Errno 2] No such file or directory: '\\_netrc'
```

**Comment by deenjohn** [comment]
put the _netrc file under C:\Users\<username> path
