### ISSUE TITLE
--preview should continue in case of the error

### ISSUE THREAD

**Issue by sacherus** [coursera-dl/coursera-dl#517]
### Subject of the issue
With --preview option coursera-dl should continue downloading rest of the content.

### Your environment
* Operating System (name/version): ubuntu 14.04
* Python version: 2.7
* coursera-dl version: coursera_dl version 0.6.0

### Steps to reproduce
$ coursera-dl -n ~/.netrc --resume --video-resolution 720p -sl en -pl --preview intrologic

### Expected behaviour
Script should continue downloading content.

Without preview:
Downloading class: intrologic
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Found authentication cookies.
Downloaded https://class.coursera.org/intrologic/lecture/index (142557 bytes)
Week_1-_Introduction

### Actual behaviour
Downloading class: intrologic
Starting new HTTPS connection (1): class.coursera.org
Error 403 Client Error: Forbidden for url: https://class.coursera.org/intrologic/lecture/preview getting page https://class.coursera.org/intrologic/lecture/preview
HTTPError 403 Client Error: Forbidden for url: https://class.coursera.org/intrologic/lecture/preview

**Comment by balta2ar** [comment]
To workaround this issue enroll to the course.

**Comment by balta2ar** [comment]
Closing as not actual anymore. Old courses are not supported.
