### ISSUE TITLE
Fail to skip mailto link

### ISSUE THREAD

**Issue by hkic** [coursera-dl/coursera-dl#520]
### Subject of the issue
Fail to skip mailto link

### Your environment
* Python version: 3
* coursera-dl version: 0.6.0

### Steps to reproduce
> Download course with mailto: link in supplement notes

* Is the problem happening with the latest version of the script?
> Yes

* What is the course that you are trying to access?
> https://www.coursera.org/learn/professional-emails-english/supplement/RvOn9/get-more-from-the-georgia-tech-language-institute

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
> coursera-dl -n -- professional-emails-english

* What are the precise messages that you get?

===================================
Downloading mailto:eslinfo@pe.gatech.edu -> professional-emails-english/01_get-to-know-basic-email-writing-structures/03_punctuation-and-capitalization/04_get-more-from-the-georgia-tech-language-institute_mailto:eslinfo@pe.gatech.edu
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/coursera/cookies.py", line 91, in login
    r.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/professional-emails-english

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/coursera/coursera_dl.py", line 1031, in download_class

=========================================================

### Expected behaviour
Skip it

### Actual behaviour
Download aborted and subsequent files are not downloaded

### Way to workaround it
```python
        if "mailto:" not in url:

while loop stuff

        else:
        	logging.warn('Skipping, can\'t download file with mailto ...')
        	return True
```

**Comment by balta2ar** [comment]
I can't reproduce it locally. It skips just fine for me:
```
The following URLs (2) have been skipped and not downloaded:
(if you want to download these URLs anyway, please add "--disable-url-skipping" option)
--------------------------------------------------------------------------------
mailto:eslinfo@pe.gatech.edu
mailto:eslinfo@pe.gatech.edu
--------------------------------------------------------------------------------
```

Another option is to use `--ignore-http-errors` argument

**Comment by hkic** [comment]
Ater re-run `pip install --upgrade coursera-dl`, it seems work for me for another course.
Thank you.
