### ISSUE TITLE
trouble installing on mac

### ISSUE THREAD

**Issue by eprezhdo** [coursera-dl/coursera-dl#521]
### Subject of the issue
I tried installing coursera-dl by typing 'pip install coursera-dl' into my command line, and got an error (posted below). I then tried 'apt-get install python3 python3-pip      pip3 install coursera-dl' but 'apt' was not a recognized command.

### Your environment
* Operating System (name/version): OS X 10.9.5
* Python version: 3.5
* The error messages include 'python 2.7' in them, but my python launcher says I'm in the 3.5 version. Am I making a mistake here?
* coursera-dl version: downloaded on 06/19/2016

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* The problem is happening with the latest version of the script
* I've downloaded pip
* What is the precise command line that you are using?  "pip install coursera-dl".

### Expected behaviour
no red error messages, or a statement saying coursera-dl was successfully installed.

### Actual behaviour
copied from terminal window:

Last login: Sun Jun 19 16:19:45 on ttys000
eugenias-mbp-2:~ Zhenya$ pip install coursera-dl
Collecting coursera-dl
/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached coursera-dl-0.6.0.tar.gz
Collecting beautifulsoup4>=4.1.3 (from coursera-dl)
  Using cached beautifulsoup4-4.4.1-py2-none-any.whl
Collecting html5lib>=1.0b2 (from coursera-dl)
  Using cached html5lib-1.0b8.tar.gz
Collecting requests>=2.4.3 (from coursera-dl)
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting six>=1.5.0 (from coursera-dl)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting urllib3>=1.10 (from coursera-dl)
  Using cached urllib3-1.16-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from coursera-dl)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting keyring>=4.0 (from coursera-dl)
  Using cached keyring-9.0-py2.py3-none-any.whl
Installing collected packages: beautifulsoup4, six, html5lib, requests, urllib3, pyasn1, keyring, coursera-dl
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/beautifulsoup4-4.4.1.dist-info'
eugenias-mbp-2:~ Zhenya$

**Comment by balta2ar** [comment]
@eprezhdo `apt` command is for Ubuntu OS only, it's not relevant for MacOS systems.

Instead of `pip install coursera-dl` try this: `pip3 install --user coursera-dl` or this `sudo pip3 install coursera-dl`. Notice the change: pip => pip3.

**Comment by balta2ar** [comment]
Closing.
