### ISSUE TITLE
Package name discrepancy or recent change?

### ISSUE THREAD

**Issue by GlowingCrystallineEntity** [coursera-dl/coursera-dl#525]
### Subject of the issue
Package name discrepancy or recent change?

### Your environment
* Windows 7
* pip 1.5.6 from C:\Python34\lib\site-packages (python 3.4)
* 0.6.1

### Steps to reproduce

It appears that if you type "pip install coursera"  -- you'll get version 0.5.2 installed (and upgrading won't get beyond that).  But if you uninstall that and type "pip install coursera-dl" … you'll get the (current) 0.6.1 version installed.

This isn't a current or urgent problem for me right now, but I mention it as it might mess other people up....

**Comment by balta2ar** [comment]
Yes, this is recent change. pip package name is "coursera-dl" now, the same as repository name. I breezed through README.md and changed all occurrences. If you see any leftovers of the old package name, please report.

**Comment by GlowingCrystallineEntity** [comment]
Would it be possible to remove the old name so that an attempt to install the old name will fail?

**Comment by balta2ar** [comment]
That's for @rbrito to decide. My position on this is to support both package names, which should not be a huge PITA.

**Comment by GlowingCrystallineEntity** [comment]
Well, it was confusing to me, because I expected to be able to just execute the install/upgrade command that I used previously and have it work... but it didn't.... so I had to dig for a while to figure out why.

**Comment by balta2ar** [comment]
This is unfortunate and I totally feel your pain. The fact is that I don't have access to "coursera" pip package so there is nothing I can do about it.

**Comment by GlowingCrystallineEntity** [comment]
It's an engineering concept called "fail-fast," and my note was intended for whomever does have the ability to make that change.  Ok, no more replies, it's not that big of a deal.

**Comment by rbrito** [comment]
I will look at how to kill the repository named coursera on PyPI or create some kind of redirection (if this is possible---we don't want to loose users that come to the previous URL).

**Comment by balta2ar** [comment]
Redirection would be the best option. I wonder whether it's possible to do that.
