### ISSUE TITLE
Unable to run command coursera-dl. ImportError: No module named requests.

### ISSUE THREAD

**Issue by joaquinalcerro** [coursera-dl/coursera-dl#528]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Unable to run command coursera-dl. ImportError: No module named requests.

### Your environment
* Operating System (name/version): Mac OSX El Capitan 10.11.5
* Python version: 3.5.1
* coursera-dl version: 0.6.1

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
**yes**

* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
**yes all of them installed correctly in folder: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages**

* What is the course that you are trying to access?
**ruby-on-rails-web-services-mongo-db**

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
**./coursera-dl -u myemail -p mypassword ruby-on-rails-web-services-mongodb**

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

Traceback (most recent call last):
  File "./coursera-dl", line 4, in <module>
    from coursera import coursera_dl
  File "/Users/jalcerro/Documents/coursera-master/coursera/coursera_dl.py", line 56, in <module>
    import requests
ImportError: No module named requests

### Expected behaviour
The Ruby on Rails Web Services Mongodb videos should download

### Actual behaviour

coursera-master ./coursera-dl --debug -u myemail -p mypassword ruby-on-rails-web-services-mongodb
Traceback (most recent call last):
  File "./coursera-dl", line 4, in <module>
    from coursera import coursera_dl
  File "/Users/jalcerro/Documents/coursera-master/coursera/coursera_dl.py", line 56, in <module>
    import requests
ImportError: No module named requests

**Comment by balta2ar** [comment]
Try installing `coursera-dl` from pip: `sudo pip install --upgrade coursera-dl`

**Comment by joaquinalcerro** [comment]
Thanks,

I tried the command and got the following output:

~ sudo pip install --upgrade coursera-dl
Password:
The directory '/Users/jalcerro/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/jalcerro/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting coursera-dl
Collecting six>=1.5.0 (from coursera-dl)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting urllib3>=1.10 (from coursera-dl)
  Downloading urllib3-1.16-py2.py3-none-any.whl (98kB)
    100% |████████████████████████████████| 102kB 778kB/s
Collecting pyasn1>=0.1.7 (from coursera-dl)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting keyring>=4.0 (from coursera-dl)
  Downloading keyring-9.1-py2.py3-none-any.whl
Collecting html5lib>=1.0b2 (from coursera-dl)
Collecting requests>=2.4.3 (from coursera-dl)
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 925kB/s
Collecting beautifulsoup4>=4.1.3 (from coursera-dl)
  Downloading beautifulsoup4-4.4.1-py2-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 1.4MB/s
Installing collected packages: six, urllib3, pyasn1, keyring, html5lib, requests, beautifulsoup4, coursera-dl
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-Ym0JX4-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

Thanks again.

**Comment by balta2ar** [comment]
Okay, then try installing it locally: `pip install --user coursera-dl`.
If it still doesn't work, try installing into virtualenv according to this instruction: https://github.com/coursera-dl/coursera-dl#alternative-installation-method-for-unix-systems

**Comment by joaquinalcerro** [comment]
@balta2ar Thanks for the help. Looks like it installation works perfectly but I now get this error:

Downloading class: ruby-on-rails-web-services-mongodb
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/ruby-on-rails-web-services-mongodb
Could not find class: ruby-on-rails-web-services-mongodb

I followed the documentation instructions:

If you get an error like Could not find class: <CLASS_NAME>, then:

Verify that the name of the course is correct. Current class names in coursera are composed by a short course name e.g. class and the current version of the course (a number). For example, for a class named class, you would have to use class-001, class-002 etc.

**I extracted the name of the course from the browser URL**

Second, verify that you are enrolled in the course. You won't be able to access the course materials if you are not officially enrolled and agreed to the honor course via the website.

**I already finished this course.**

---------

I think this is because the URL it is calling:
https://class.coursera.org/ruby-on-rails-web-services-mongodb

The class is actually located in:
https://class.coursera.org/learn/ruby-on-rails-web-services-mongodb

Please note the "learn" in the last URL.

Thanks for your comments.

**Comment by balta2ar** [comment]
Did you install `coursera-dl` package? Can you see it prints version 0.6.1 in the beginning? Can you show me the whole output and command-line arguments (except username & password)?

**Comment by joaquinalcerro** [comment]
➜  coursera-master ./coursera-dl -u myemail -p mypassword ruby-on-rails-web-services-mongodb
Downloading class: ruby-on-rails-web-services-mongodb
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/ruby-on-rails-web-services-mongodb
Could not find class: ruby-on-rails-web-services-mongodb
➜  coursera-master

**Comment by balta2ar** [comment]
If you installed version 0.6.1 from pip, do not run previously downloaded version with a dot: `./coursera-dl`. Just run `coursera-dl` and make sure it prints 0.6.1 version as the first line of its output.

**Comment by joaquinalcerro** [comment]
Thanks. This is what i have done:

1. Tried running the command (coursera-dl -u myemail -p mypassword ruby-on-rails-web-services-mongodb) without "./" but: zsh: command not found: coursera-dl
2. Uninstalled coursera-dl
3. Install coursera-dl

➜  ~ pip install --user coursera-dl
Collecting coursera-dl
Collecting six>=1.5.0 (from coursera-dl)
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): urllib3>=1.10 in ./Library/Python/2.7/lib/python/site-packages (from coursera-dl)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in ./Library/Python/2.7/lib/python/site-packages (from coursera-dl)
Requirement already satisfied (use --upgrade to upgrade): keyring>=4.0 in ./Library/Python/2.7/lib/python/site-packages (from coursera-dl)
Requirement already satisfied (use --upgrade to upgrade): html5lib>=1.0b2 in ./Library/Python/2.7/lib/python/site-packages (from coursera-dl)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.4.3 in ./Library/Python/2.7/lib/python/site-packages (from coursera-dl)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4>=4.1.3 in ./Library/Python/2.7/lib/python/site-packages (from coursera-dl)
Installing collected packages: six, coursera-dl
Successfully installed coursera-dl-0.6.1 six-1.4.1
➜  ~

4. Check the folder ./Library/Python/2.7/lib/python/site-packages:

➜  site-packages ls
beautifulsoup4-4.4.1.dist-info pyasn1-0.1.9.dist-info
bs4                            requests
coursera                       requests-2.10.0.dist-info
coursera_dl-0.6.1.dist-info    six-1.10.0.dist-info
html5lib                       six.py
html5lib-1.0b8.dist-info       six.pyc
keyring                        urllib3
keyring-9.1.dist-info          urllib3-1.16.dist-info
pyasn1
➜  site-packages

5. This is my PATH

➜  ~ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/sbin:/Applications/Postgres.app/Contents/Versions/9.4/bin:/Users/jalcerro/.rvm/bin:/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5:/Users/jalcerro/Library/Python/2.7/lib/python/site-packages/coursera

**Comment by balta2ar** [comment]
Sorry, I'm not an expert in Python tree hierarchy on MacOS. On Linux if I had run `pip install --user coursera-dl`, it would have created a binary in `~/.local/bin/coursera-dl` and the library in `~/.local/lib/python3.5/site-packages`. Ideally, you need to figure our where your Python's `local/bin` is and add it to the `$PATH`.

Alternatively you may want to try this hack:
``` zsh
cd /Users/jalcerro/Library/Python/2.7/lib/python/site-packages
PYTHONPATH=. python2 -c 'from coursera.coursera_dl import main; main()' -u myemail -p mypassword ruby-on-rails-web-services-mongodb
```

**Comment by joaquinalcerro** [comment]
Thanks for the help, I finally installed a Ubuntu image and works perfectly. I am not sure what is happening. I am not a python expert too.

**Comment by balta2ar** [comment]
Closing.

**Comment by wengzilla** [comment]
FYI, the bin file ends up getting installed in here on Mac OS computers: /Users/USERNAME/Library/Python/2.7/bin
