### ISSUE TITLE
importerror cannot import name 'get-page-and-url'

### ISSUE THREAD

**Issue by marcosorapis** [coursera-dl/coursera-dl#529]
Hello,
I try to download the "Managing Employee Compensation" course material using the command    `coursera-dl -u xxx -p yyy compensation-management `   but I get the error: 

> importerror cannot import name 'get-page-and-url'

This is all I get using the above command line:

> Traceback (most recent call last):
>   File "C:\Users\Silla\AppData\Local\Programs\Python\Python35-32\Scripts\courser
> a-dl-script.py", line 9, in <module>
>     load_entry_point('coursera-dl==0.6.1', 'console_scripts', 'coursera-dl')()
>   File "c:\users\silla\appdata\local\programs\python\python35-32\lib\site-packag
> es\pkg_resources\__init__.py", line 558, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "c:\users\silla\appdata\local\programs\python\python35-32\lib\site-packag
> es\pkg_resources\__init__.py", line 2682, in load_entry_point
>     return ep.load()
>   File "c:\users\silla\appdata\local\programs\python\python35-32\lib\site-packag
> es\pkg_resources\__init__.py", line 2355, in load
>     return self.resolve()
>   File "c:\users\silla\appdata\local\programs\python\python35-32\lib\site-packag
> es\pkg_resources\__init__.py", line 2361, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "c:\users\silla\appdata\local\programs\python\python35-32\lib\site-packag
> es\coursera\coursera_dl.py", line 80, in <module>
>     from .network import get_page, get_page_and_url
> ImportError: cannot import name 'get_page_and_url'

My environment is:
* Operating System: Windows 7 service pack 1 64 bit
* Python version: 3.5.1
* coursera-dl version: coursera-dl-0.6.1

May you help me finding a way to overcome the issue? 
Thank you very much!

**Comment by balta2ar** [comment]
Could you start from scratch? Remove all coursera packages and install them again?
It it does not help, consider this: https://github.com/coursera-dl/coursera-dl#alternative-installation-method-for-unix-systems

**Comment by marcosorapis** [comment]
Removing coursera packages and installing them again solved the issue.
Thank you very much!
