### ISSUE TITLE
download video from the URL  like that "https://www.coursera.org/learn/<CLASS_NAME>/home/welcome

### ISSUE THREAD

**Issue by love-xiaoyi** [coursera-dl/coursera-dl#530]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Hello.I want to download the coursera video from the URL  like that "https://www.coursera.org/learn/<CLASS_NAME>/home/welcome"  which isn't the same as URL " https://class.coursera.org/<CLASS_NAME>/class/index".  I can  use the Firefox Plugins "DownThemAll"  to download the video  I want  but that approach is time-consuming .is there any possible for you to update  coursera-dl script  so that  the script can be used to download video from uRL I mentioned above . thanks a lot.

### Your environment
* Operating System (name/version): windows 7
* Python version: 3.4
* coursera-dl version:0.6.1

**Comment by balta2ar** [comment]
This functionality has been supported for a very long time. Please read the README carefully.

**Comment by love-xiaoyi** [comment]
ha-ha.Thanks for your help . I have solved the problem

**Comment by love-xiaoyi** [comment]
@balta2ar Haha.I has solved that problem.Thanks for your help .
