### ISSUE TITLE
Document how to run the script under Windows

### ISSUE THREAD

**Issue by rbrito** [coursera-dl/coursera-dl#538]
To test this darned long-names thing under Windows, I went through the trouble of:

1. selling my soul :grinning:
2. downloading a Windows 10 ISO image directly from Microsoft
3. installing it on a virtual machine
4. installing Python 3.5

And everything was fine.

Using `pip` was super easy. But I have no idea where/how to actually *run* coursera-dl, after installing it with `--user`. All I got was something like "command not found" and the oficial Python documentation is less than stellar here.

If I install ipython the same way, I *can* run an ipython console, which means that something is being done differently between the two projects.

Since I'm not that motivated to go further, It would help a lot if our Windows users could document what they did, so that we can have an appropriate section in our manual on how to use Windows.

Please, help spread the word to whomever can help with the documentation (twitter, facebook, mailing lists etc.). All the credits will be given with pull requests.

**Comment by rbrito** [comment]
@victorwestmann, @GlowingCrystallineEntity, can you help here? Any comments are more than welcome.

**Comment by balta2ar** [comment]
We may also consider adding Vagrantfile with Windows guest. That would make it easier for developers to run tests locally, I hope. I've never done that personally, but I think it's possible.

**Comment by rbrito** [comment]
@balta2ar, excellent idea. Actually, any kind of help would be welcome here.

**Comment by balta2ar** [comment]
By the way, is there any free service like Travis but with Windows?

**Comment by rbrito** [comment]
Not that I know about. It would make things so much easier to see if they are working.

That's one of the reasons why I've just created a windows label for our bug reports. We will, for the moment, have to rely on our users to help us with such expertise.

**Comment by GlowingCrystallineEntity** [comment]
I *think*, that when I installed Python itself a long time ago.... I put "C:\Python34\;C:\Python34\Scripts" in the path.  Indeed -- the coursera-dl exe is in that scripts directory for me, and it ran at the command line for me after a pip install.

FYI, on Windows 7, you can get to the path as Start Menu -> Control Panel -> System and then Advanced system settings -> Advanced (tab) and the Environment Variables button at the bottom.

(nice, huh?)

**Comment by marmleite** [comment]
Hi, I used pip with --user to install the coursera-dl after installing python 3.5 and I found the file exe in "c:\users\username\appdata\roaming\python\python35\scripts", on Windows 7. I run the program in this folder that I found and it worked fine.

**Comment by balta2ar** [comment]
Documentation has been added in #566. Thanks to @CBickel87.
