### ISSUE TITLE
SyntaxError: Invalid Token

### ISSUE THREAD

**Issue by moatasemtaher** [coursera-dl/coursera-dl#540]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
whenever I try to download a course I always get this error: "SyntaxError: invalid token" with the number at the end of the course name being highlighted.
For instance, if I'm trying to download the course "pgm-003", the 003 gets highlighted.

### Your environment
* Operating System (name/version): Windows 10
* Python version: 3.5.1
* coursera-dl version:

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
coursera-dl -u <**********@******.com> -p <******> modelthinking-004

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.
SyntaxError: invalid syntax

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

**Comment by rbrito** [comment]
Please, give us the complete output (it can be a screenshot) of what happens when you try to download the course **with** the `--debug` option specified.

We need that to understand what the problem is.

**Comment by balta2ar** [comment]
No response from the topic starter. Closing. Feel free to comment if still actual.
