### ISSUE TITLE
Error Downloading Coursera Course: datasci-002

### ISSUE THREAD

**Issue by dbl001** [coursera-dl/coursera-dl#541]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Downloading about page from: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci
Starting new HTTPS connection (1): api.coursera.org
Error 404 Client Error: Not Found for url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci getting page https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci
HTTPError 404 Client Error: Not Found for url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci
### Your environment
* Operating System (name/version): OS X 10.11.5
* Python version:Python 2.7.10

* coursera-dl version: 0.6.0

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

coursera-dl -u davidl@softintel.com -p blahblabla datasci-002

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access? datasci-002
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Download Course

### Actual behaviour
$ coursera-dl -u davidl@softintel.com -p blahblahblah datasci-002
coursera_dl version 0.6.0
Downloading class: datasci-002
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Found authentication cookies.
Downloading about page from: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci
Starting new HTTPS connection (1): api.coursera.org
Error 404 Client Error: Not Found for url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci getting page https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci
HTTPError 404 Client Error: Not Found for url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci

**Comment by balta2ar** [comment]
I can't access it either. But I can download datasci-001. Can you try it? If it does not work, then I have attached a syllabus file ([datasci-001.txt](https://github.com/coursera-dl/coursera-dl/files/339270/datasci-001.txt)) which you should use as follows: `--process_local_page datasci-001.txt`.

**Comment by dbl001** [comment]
$ coursera-dl -u davidl@softintel.com -p blahblahblah --process_local_page datasci-001.txt
usage: coursera-dl [-h] [-u USERNAME] [-p PASSWORD] [--on-demand] [-b]
                   [--path PATH] [-sl SUBTITLE_LANGUAGE] [--about]
                   [-f FILE_FORMATS] [--ignore-formats IGNORE_FORMATS]
                   [-sf SECTION_FILTER] [-lf LECTURE_FILTER]
                   [-rf RESOURCE_FILTER] [--video-resolution VIDEO_RESOLUTION]
                   [--ignore-http-errors] [--disable-url-skipping]
                   [--wget [WGET]] [--curl [CURL]] [--aria2 [ARIA2]]
                   [--axel [AXEL]]
                   [--downloader-arguments DOWNLOADER_ARGUMENTS] [--resume]
                   [-o] [--verbose-dirs] [--quiet] [-r]
                   [--combined-section-lectures-nums]
                   [--unrestricted-filenames] [-c COOKIES_FILE] [-n [NETRC]]
                   [-k] [--clear-cache] [--hook HOOKS] [-pl] [--skip-download]
                   [--debug] [--version] [-l LOCAL_PAGE]
                   class_names [class_names ...]
coursera-dl: error: too few arguments
David-Laxers-MacBook-Pro:DataScience davidlaxer$ pwd
/Users/davidlaxer/coursera/DataScience
David-Laxers-MacBook-Pro:DataScience davidlaxer$ ls
datasci-001.txt

**Comment by balta2ar** [comment]
> coursera-dl: error: too few arguments

You should still specify course name.

**Comment by dbl001** [comment]
$ coursera-dl -u davidl@softintel.com -p bla-bla-bla datasci-001 --process_local_page datasci-001.txt
coursera_dl version 0.6.0
Downloading class: datasci-001
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Found authentication cookies.
Downloading about page from: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci
Starting new HTTPS connection (1): api.coursera.org
Error 404 Client Error: Not Found for url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci getting page https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci
HTTPError 404 Client Error: Not Found for url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci

David-Laxers-MacBook-Pro:DataScience davidlaxer$ coursera-dl -u davidl@softintel.com -p blahblahblah datasci-002 --process_local_page datasci-001.txt
coursera_dl version 0.6.0
Downloading class: datasci-002
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Found authentication cookies.
Downloading about page from: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci
Starting new HTTPS connection (1): api.coursera.org
Error 404 Client Error: Not Found for url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci getting page https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci
HTTPError 404 Client Error: Not Found for url: https://api.coursera.org/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=datasci
David-Laxers-MacBook-Pro:DataScience davidlaxer$

**Comment by dbl001** [comment]
Is there a way to ‘run’ the courses I’ve downloaded with coursera-dl (in browser), or do I just play the .mp4 files, review slides, etc.

**Comment by balta2ar** [comment]
Try updating to 0.6.1 version. There was an issue with this option in 0.6.0 version.

**Comment by balta2ar** [comment]
> Is there a way to ‘run’ the courses I’ve downloaded

Run? You mean to make them interactive and view in a browser? If so, no, there is no way to do that now. Yes, you need to play files, view slides, etc.

**Comment by dbl001** [comment]
Ok.  It’s working now with 0.6.1.  Do you know why they couldn’t ‘migrate’ the old courses to the new Coursera platform?

Thank You!

**Comment by balta2ar** [comment]
Who knows. It's business and they need to make money.
