### ISSUE TITLE
error during "pip install coursera --upgrade" command

### ISSUE THREAD

**Issue by jnowe** [coursera-dl/coursera-dl#542]
* Operating System (name/version): OpenSuse Leap 42.1 x64
* Python version: Python 3.4

At the end of the command pip install coursera --upgrade, here is what I get:

warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
    building 'Crypto.Hash._MD2' extension
    creating build/temp.linux-x86_64-3.4
    creating build/temp.linux-x86_64-3.4/src
    gcc -pthread -Wno-unused-result -Werror=declaration-after-statement -fmessage-length=0 -grecord-gcc-switches -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -DOPENSSL_LOAD_CONF -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/MD2.c -o build/temp.linux-x86_64-3.4/src/MD2.o
    src/MD2.c:31:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

GMP and MPIR  libraries are installed or maybe I have the bad ones?

What can I do to solve this issue?

Thanks for feedback.

**Comment by balta2ar** [comment]
> Python.h: No such file or directory

@jnowe Perhaps you need some kind of python-dev package?

**Comment by jnowe** [comment]
First time, I get this error. Well, I will install this package to see the behaviour.

**Comment by jnowe** [comment]
Same issue with python-dev installed. Before, I could upgrade coursera and coursera-dl without any problem. Something has changed in the process?

**Comment by balta2ar** [comment]
@jnowe We only updated requests dependency, it shouldn't be relevant. Maybe something changed in python-crypto. Try specifying exact version: `pip install coursera==0.6.1` to update only coursera-dl without updating crypto.

**Comment by rbrito** [comment]
First of all, @jnowe, please, use the `coursera-dl` package when installing from `pip`. Uninstall `coursera` and then install `coursera-dl`, please.

OK, now to the core of the issue: many packages in the dependency chain of `python-ndg-httpsclient` and Co. need compilation with many libraries. I don't know the directory/package structure of an (Open)SuSE system, but I guess that, as a quick fix, you can install the packages listed in the requirements.txt file from your distribution, grab the tarball (or clone) of the master branch of the repo and try to use that instead.

In fact, that's the way that I run the script myself, with the difference that I'm using Debian's testing distribution.

**Comment by balta2ar** [comment]
No response from the topic starter. Closing. Feel free to comment if still actual.
