### ISSUE TITLE
Failed to find csrf cookie

### ISSUE THREAD

**Issue by gubertoli** [coursera-dl/coursera-dl#552]
* Operating System (name/version): Windows 10
* Python version: Python 2.7
* coursera-dl version: 3.1.1

### Steps to reproduce
**> coursera-dl -u XXXXX@gmail.com -p XXXXXX robotics-flight**

* Is the problem happening with the latest version of the script? 
**Yes, I executed pip --upgrade for coursera-dl before that**

* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. **Yes**

* What is the course that you are trying to access? **robotics-flight, tried machine-learning also**

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
> **coursera-dl -u XXXXX@gmail.com -p XXXXXX robotics-flight**

* What are the precise messages that you get? 

```
Coursera-dl` v3.1.1 (html.parser)
Logging in as 'XXXXXX@gmail.com'...
Traceback (most recent call last):
  File "C:\Python27\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()
  File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py", line 648, in main
    d.login(args.course_names[0])
  File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py", line 140, in login
    if not csrfcookie: raise Exception("Failed to find csrf cookie")
Exception: Failed to find csrf cookie

```

**Comment by balta2ar** [comment]
You're using something different. We don't have version `3.1.1`. Our latest version is `0.6.1`. Try to `pip uninstall coursera-dl` and install it again.

**Comment by gubertoli** [comment]
@balta2ar thank you for your fast answer, but it seems to keep the issue:

> C:\Coursera>coursera-dl -u XXXXXXX@gmail.com -p XXXXXX robotics-flight
> coursera_dl version 0.6.1
> Downloading class: robotics-flight
> Starting new HTTPS connection (1): class.coursera.org
> Starting new HTTPS connection (1): www.coursera.org
> Logged in on coursera.org.
> Starting new HTTPS connection (1): class.coursera.org
> Could not authenticate: Did not find necessary cookies.

**Comment by balta2ar** [comment]
@gubertoli Could you try this https://github.com/coursera-dl/coursera-dl/issues/508#issuecomment-226842459?

**Comment by gubertoli** [comment]
@balta2ar 

I modified **coursera_dl.py** from:

> try:
>             logging.info('Downloading class: %s', class_name)
>             if **download_class**(args, class_name):
> 

To

> try:
>             logging.info('Downloading class: %s', class_name)
>             if **download_on_demand_class**(args, class_name):
> 


And now it works! Thank you.

**Comment by BabluKumar17** [comment]
I am having the same issue as @gubertoli had. 

But I am not able to find any file called coursera-dl.py as he did. Please see my script folder:  
![image](https://cloud.githubusercontent.com/assets/14871809/20245531/758c1e48-a9c9-11e6-8383-31474c95db90.png)

What should I do? Which file should I modify?
Operating System: Windows 8.1
coursera-dl version: 3.1.1 (downloaded from github).

**Comment by balta2ar** [comment]
Our latest version is 0.8.0. Please check what you have downloaded.
