### ISSUE TITLE
TreeBuilderForHtml5lib 'module' object has no attribute '_base'

### ISSUE THREAD

**Issue by wengzilla** [coursera-dl/coursera-dl#554]
### Subject of the issue

I am unable to download the course 'build-a-computer' and am receiving this stack trace. Any ideas on how to fix? I've already upgraded all of my scripts/libraries and am not quite sure what to do next.

```
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 7, in <module>
    from coursera.coursera_dl import main
  File "/usr/local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 63, in <module>
    import bs4
  File "/usr/local/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

### Your environment
* Operating System (name/version): Mac OSX 10.11.5
* Python version: 2.7.11
* coursera-dl version: 0.6.1

### Steps to reproduce
coursera-dl -u MY_USERNAME -p MY_PASSWORD build-a-computer

### Course
https://www.coursera.org/learn/build-a-computer

**Comment by balta2ar** [comment]
This is an issue with upstream package html5lib: https://bugs.launchpad.net/beautifulsoup/+bug/1603299
To fix, force downgrade to an older version:
``` bash
pip install --upgrade html5lib==1.0b8
```

**Comment by neoyukito** [comment]
Same error,

<img width="581" alt="screenshot 2016-07-18 13 23 46" src="https://cloud.githubusercontent.com/assets/5897215/16923904/9af5ce86-4cea-11e6-930c-6f9f2bb7ea41.png">
<img width="578" alt="screenshot 2016-07-18 13 23 32" src="https://cloud.githubusercontent.com/assets/5897215/16923905/9af7995a-4cea-11e6-8968-cdc75d78e520.png">

**Comment by balta2ar** [comment]
This should be fixed in 0.7.0. Besides, we don't use html5lib anymore.

**Comment by EvaldoAraujo** [comment]
Isso resolveu meu problema.
sudo pip3 install html5lib==0.9999999
Link: https://bugs.launchpad.net/beautifulsoup/+bug/1603299
:)

**Comment by rbrito** [comment]
@EvaldoAraujo, você está usando a última versão do coursera-dl? O que ocorre se você remover a html5lib (não lembro se outros pacotes serão removidos)...

Se você conseguir escrever em inglês, isso facilita para o resto do pessoal que mantém o programa, já que nós temos um que é colombiano, um russo e um brasileiro (eu). Mas, se você não souber, tudo bem também.

**Comment by EvaldoAraujo** [comment]
rbrito, não escrevo em inglês, outros pacotes dependem dessa lib, eu atualizei essa lib para poder usar o Spyder3 python que usa ela. flw
