### ISSUE TITLE
403 Client Error When trying to download a new platform course

### ISSUE THREAD

**Issue by lewisKit** [coursera-dl/coursera-dl#556]
### Subject of the issue
I am trying to download a new platform course, probabilistic graphical models, but get Error 403 Client Error.

### Your environment
* Operating System (name/version):  Mac OSX 10.11.5 and CentOS 6
* Python version: 2.7.12
* coursera-dl version: 0.6.1

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
> yes. 

* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
> yes. I get the same problem with [issue#554,](https://github.com/coursera-dl/coursera-dl/issues/554) but fixed it with the suggestion.
* What is the course that you are trying to access?

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
> I tried two methods. The first with coursera-dl commands as
` coursera-dl -u 'XXX' -p 'XXX' probabilistic-graphical-models` in Centos System.
> And the second with the code command as 
`./coursera-dl -u 'XXX' -p 'XXX' probabilistic-graphical-models` both in Centos and Mac OSX.

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

```
root[main] coursera_dl version 0.6.1
root[main] Downloading class: probabilistic-graphical-models
root[download_class] Downloading new style (on demand) class probabilistic-graphical-models
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[login] Forging cookie header: csrftoken=MJ0zJc6GUGsqU8q4gNgl; csrf2_token_amPYcnOO=6l8qFEcl4itfmj7IK78OOccz.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/course/probabilistic-graphical-models?showLockedItems=true HTTP/1.1" 403 None
root[get_page] Error 403 Client Error: Forbidden for url: https://www.coursera.org/api/opencourse.v1/course/probabilistic-graphical-models?showLockedItems=true getting page https://www.coursera.org/api/opencourse.v1/course/probabilistic-graphical-models?showLockedItems=true
root[main] HTTPError 403 Client Error: Forbidden for url: https://www.coursera.org/api/opencourse.v1/course/probabilistic-graphical-models?showLockedItems=true
```

### Expected behaviour
It should download the course.

### Actual behaviour

Here is the log when I trying to download the course probabilistic-graphical-models.
```
coursera_dl version 0.6.1
Downloading class: probabilistic-graphical-models
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Error 403 Client Error: Forbidden for url: https://www.coursera.org/api/opencourse.v1/course/probabilistic-graphical-models?showLockedItems=true getting page https://www.coursera.org/api/opencourse.v1/course/probabilistic-graphical-models?showLockedItems=true
HTTPError 403 Client Error: Forbidden for url: https://www.coursera.org/api/opencourse.v1/course/probabilistic-graphical-models?showLockedItems=true
```

----
I got the same issue with a new platform course [neural networks](https://www.coursera.org/learn/neural-networks). But I have successfully downloaded another course called [Build a Modern Computer](https://www.coursera.org/learn/build-a-computer)

**Comment by balta2ar** [comment]
@lewisKit If you look at the front page of the problematic courses that you've reported, they are only available for enrollment, but you can't see their content until they have actually started, which is August and September 2016. Please come back in September if the issue remains.

**Comment by lewisKit** [comment]
Ok, sure, I understand now. 

Thanks,
Lewis

**Comment by lewisKit** [comment]
Problem has been solved.
