### ISSUE TITLE
Error when "pip install coursera-dl --upgrade"

### ISSUE THREAD

**Issue by Takehashi** [coursera-dl/coursera-dl#558]
I use cousera-dl to download course have error : 
https://github.com/coursera-dl/coursera-dl/issues/547
And I use upgrade.

--------------------------------------
Collecting coursera-dl
Requirement already up-to-date: urllib3>=1.10 in /usr/local/lib/python2.7/dist-packages (from coursera-dl)
Collecting beautifulsoup4>=4.1.3 (from coursera-dl)
  Using cached beautifulsoup4-4.5.0-py2-none-any.whl
Requirement already up-to-date: six>=1.5.0 in /usr/local/lib/python2.7/dist-packages (from coursera-dl)
Requirement already up-to-date: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from coursera-dl)
Collecting html5lib>=1.0b2 (from coursera-dl)
  Using cached html5lib-1.0b10.tar.gz
    Complete output from command python setup.py egg_info:
    html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 3.3)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-66QTsf/html5lib/

**Comment by balta2ar** [comment]
Install html5lib==1.0b8 first, then repeat:
``` bash
pip install html5lib==1.0b8
pip install --upgrade coursera-dl
```

Do not install html5lib==1.0b10, it has issues.

**Comment by Takehashi** [comment]
@balta2ar I try it, but not work.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-PjaDd1/html5lib/

**Comment by VikasMaheshwari** [comment]
@Takehashi try `pip install --upgrade setuptools`

**Comment by Takehashi** [comment]
@VikasMaheshwari Thanks. It's work.
