### ISSUE TITLE
Error: coursera-dl: command not found on Ubuntu Linux 16.04 LTS

### ISSUE THREAD

**Issue by etsnyman** [coursera-dl/coursera-dl#560]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

Couldn't find anything that has anything to do with my problem.
### Subject of the issue

I installed coursera-dl with the pip command, and when I try to run it, I get the error coursera-dl: command not found

I tried the pip3 way, and still nothing.
### Your environment
- Operating System (name/version): Ubuntu 16.04 64-bit
- Python version: 2.7.12
- coursera-dl version: Don't know, as I can't seem to install it.
### Steps to reproduce

Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you: pip3 install coursera-dl

**Comment by balta2ar** [comment]
Check your PATH and PYTHONPATH.

**Comment by etsnyman** [comment]
I'm sorry, but I don't know what that means or how to do it :-(

**Comment by P3trur0** [comment]
I had the same problem. Fixed by running the pip3 install command together with the flag --upgrade.

**Comment by pradhanshrijal** [comment]
I tried running the --upgrade flag, but its not working.

Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_pradhanshrijal/coursera-dl/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-m81i2tl3-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_pradhanshrijal/coursera-dl

This is the error I get

I tried changing the python path with

$export PYTHONPATH=/usr/bin/python3

but when I execute $echo PYTHONPATH, it only outputs "PYTHONPATH"

I'm using Ubuntu14.04, 64 bit system

**Comment by gurjit03** [comment]
Facing same issue

**Comment by vossad01** [comment]
The error,
> coursera-dl: command not found

says that either `coursera-dl` is not installed or that the location it was installed is not on `PATH` (the environment variable that indicates where to look for programs).

I am on a Ubuntu 16.04 derivative (Mint 18/18.1) and have never needed to manually configure path for pip-installed packages after installing pip with the package manger. Information about the particulars of your setup would be needed to troubleshoot this.

For example,
- How did you [try to] install coursera-dl? What was the output?
- How did you install pip?
- What version of pip are you using?
- What is your PATH?
- Are you trying to install `coursera-dl` for python2 or python3?

**Comment by rbawaskar** [comment]
Check following directory 
`~/.local/bin/ `
Add above directory to PATH or use coursera-dl from there

**Comment by balta2ar** [comment]
This thread has many valid suggestions to troubleshoot the problem, so I'm closing this issue. Feel free to comment if you're still having problems. But usually reports like this one indicate that there's something not right with the user's environment.
