### ISSUE TITLE
how to force download the highest quality video available?

### ISSUE THREAD

**Issue by ee7klt** [coursera-dl/coursera-dl#561]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### coursera-dl downloads the medium quality video
There are low medium and high options available in the player but coursera-dl seems to randomly download the medium quality as far as I can tell. I tested this randomly using a few videos using the Chrome video downloader extension and compared the file sizes

### Your environment
* Operating System (name/version): OS X 10.10.5
* Python version: 3.5.1
* coursera-dl version: not sure. installed a few days ago

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you: coursera-dl -u XXX -p XXX progfun2

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
should download the highest quality video available

### Actual behaviour
downloads the less than highest quality video available.

**Comment by balta2ar** [comment]
If you had tried reading coursera-dl help output (`coursera-dl --help`), you would have found `--video-resolution` option that does exactly what you want.
