### ISSUE TITLE
`class_names` argument should be required only in combination with certain options

### ISSUE THREAD

**Issue by andersonvom** [coursera-dl/coursera-dl#562]
### `class_names` argument should be required only in combination with certain options
Some options do not require `class_names` to be performed, such as `--version` or the newly added `--list-courses`. In such cases, `class_names` should be optional

### Your environment
* Operating System (name/version): OSX
* Python version: 3.5.2
* coursera-dl version: 0.7.0

### Steps to reproduce
```
coursera-dl --version
coursera-dl --list-courses
```

### Expected behaviour
These actions should be performed

### Actual behaviour
The following error message is displayed:
    
```
usage: coursera-dl [-h] [-u USERNAME] [-p PASSWORD] [--jobs JOBS] [-b]
                   [--path PATH] [-sl SUBTITLE_LANGUAGE] [--download-quizzes]
                   [--about] [-f FILE_FORMATS]
                   [--ignore-formats IGNORE_FORMATS] [-sf SECTION_FILTER]
                   [-lf LECTURE_FILTER] [-rf RESOURCE_FILTER]
                   [--video-resolution VIDEO_RESOLUTION]
                   [--disable-url-skipping] [--wget [WGET]] [--curl [CURL]]
                   [--aria2 [ARIA2]] [--axel [AXEL]]
                   [--downloader-arguments DOWNLOADER_ARGUMENTS]
                   [--list-courses] [--resume] [-o] [--verbose-dirs] [--quiet]
                   [-r] [--combined-section-lectures-nums]
                   [--unrestricted-filenames] [-c COOKIES_FILE] [-n [NETRC]]
                   [-k] [--clear-cache] [--hook HOOKS] [-pl] [--skip-download]
                   [--debug] [--cache-syllabus] [--version] [-l LOCAL_PAGE]
                   class_names [class_names ...]
coursera-dl: error: the following arguments are required: class_names
```

**Comment by balta2ar** [comment]
Yeah, I know about that. This behavior is surprising and inconvenient. Pull request is welcome.

**Comment by andersonvom** [comment]
I can submit a PR to fix it. Are there any other flags that don't need class_names? I can only see `--list-courses` and `--version`, but I may be missing something.
