### ISSUE TITLE
The server replied: {"errorCode":"auth.perms","message":"Item is locked","details":null}

### ISSUE THREAD

**Issue by pippocode** [coursera-dl/coursera-dl#565]
### Subject of the issue
Can't download course https://www.coursera.org/learn/progfun2

### Your environment
* Operating System (name/version):
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Intel Core i5
  Processor Speed:	2,9 GHz
  System Version:	OS X 10.11.6
  Kernel Version:	Darwin 15.6.0

* Python version: 3.5.2
* coursera-dl version: 0.7.0

### Steps to reproduce
It is possible the course is protected in some way?

error message:
```
...
...
Processing lecture   example-assignment (ungradedProgramming)
Error 403 Client Error: Forbidden for url: https://www.coursera.org
api/onDemandProgrammingLearnerAssignments.v1/PeZYFz-zEeWB_AoW1KYI4Q~AYDPu?fields=submissionLearnerSchema getting page https://www.coursera.org
api/onDemandProgrammingLearnerAssignments.v1/PeZYFz-zEeWB_AoW1KYI4Q~AYDPu?fields=submissionLearnerSchema
The server replied: {"errorCode":"auth.perms","message":"Item is locked","details":null}
HTTPError 403 Client Error: Forbidden for url: https://www.coursera.org/api/onDemandProgrammingLearnerAssignments.v1/PeZYFz-zEeWB_AoW1KYI4Q~AYDPu?fields=submissionLearnerSchema
```
With some other courses all is fine.

thank you.

**Comment by balta2ar** [comment]
@pippocode Can you open that very assignment in the browser? If you can't, there is nothing I can do. Please check.

**Comment by pippocode** [comment]
Sure, I can.

**Comment by pippocode** [comment]
I can see the videos and all other stuff except assignments.

**Comment by balta2ar** [comment]
It's either because your session has already ended, or has not started yet. Please check that and if it is the case, close the issue because we can't extract such locked items anyway.

**Comment by pippocode** [comment]
Ok, sorry.
I tried some other closed courses and it worked...

**Comment by lordloh** [comment]
I have the same problem. My course has ended. How do I download just the videos? I cant figure out what switches to use to do this?

**Comment by balta2ar** [comment]
@lordloh If you can't access your course in your browser, you can't download it either. There is no magic here.

**Comment by lordloh** [comment]
@balta2ar I understand that. I can access course videos in the browser. The page that is giving me the problem is -  https://www.coursera.org/api/onDemandProgrammingLearnerAssignments.v1/yOZEQ3lwEeWb-BLhFdaGww~0mg6B?fields=submissionLearnerSchema - which looks like it is a programming assignment. I would like to skip those and the `--skip-download` is not doing that.

**Comment by balta2ar** [comment]
You must be experiencing this issue: #568. It will be addressed in the next release.
