### ISSUE TITLE
Skip locked assignments in the schedule and continue downloading

### ISSUE THREAD

**Issue by MoHD20** [coursera-dl/coursera-dl#568]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

**Subject of the issue**
I was downloading a course that have it's assignment locked so in the processing phase the program stopped  and I got this message {"errorCode":"auth.perms","message":"Item is locked","details":null}.. I want just to download the course without this locked assignment. is there away to skip this locked assignment and download the rest of the course? 

### Your environment
* Operating System (name/version):fedora 23
* Python version: 3.5
* coursera-dl version: coursera_dl version 0.7.0

### Actual behaviour
here is the output with a registered fake email So you can try the same course.
"
[root@localhost hamza]# coursera-dl -u xae@g.gtvtech.com -p 123456qwert   "cloud-computing"
coursera_dl version 0.7.0
Downloading class: cloud-computing
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/cloud-computing?showLockedItems=true (37982 bytes)
Parsing syllabus of on-demand course. This may take some time, please be patient ...
Processing module  week-1-orientation-introduction-to-clouds-mapreduce
Processing section     orientation
Processing lecture         orientation-overview (supplement)
Processing lecture         introduction-to-cloud-computing-concepts-part-1 (lecture)
Processing lecture         syllabus (supplement)
Processing lecture         about-the-discussion-forums (supplement)
Processing lecture         orientation-quiz (quiz)
Processing section     basic-computer-science-fundamentals
Processing lecture         orientation-towards-cloud-computing-concepts-some-basic-computer-science (lecture)
Processing lecture         instructions-for-taking-the-prerequisite-quiz (supplement)
Processing lecture         prerequisite-quiz (quiz)
Processing section     know-your-classmates
Processing lecture         getting-to-know-your-classmates (discussionPrompt)
Processing lecture         course-learning-community-and-social-media (supplement)
Processing section     week-1-overview-introduction-to-clouds-mapreduce
Processing lecture         week-1-overview (supplement)
Processing lecture         week-1-introduction (lecture)
Processing section     lesson-1-introduction-to-clouds
Processing lecture         1-1-why-clouds (lecture)
Processing lecture         1-2-what-is-a-cloud (lecture)
Processing lecture         1-3-introduction-to-clouds-history (lecture)
Processing lecture         1-4-introduction-to-clouds-whats-new-in-todays-clouds (lecture)
Processing lecture         1-5-introduction-to-clouds-new-aspects-of-clouds (lecture)
Processing lecture         1-6-introduction-to-clouds-economics-of-clouds (lecture)
Processing section     lesson-2-clouds-are-distributed-systems
Processing lecture         2-1-a-cloud-is-a-distributed-system (lecture)
Processing lecture         2-2-what-is-a-distributed-system (lecture)
Processing section     lesson-3-mapreduce
Processing lecture         3-1-mapreduce-paradigm (lecture)
Processing lecture         3-2-mapreduce-examples (lecture)
Processing lecture         3-3-mapreduce-scheduling (lecture)
Processing lecture         3-4-mapreduce-fault-tolerance (lecture)
Processing section     interview
Processing lecture         interview-with-sumeet-singh (lecture)
Processing section     homework
Processing lecture         homework-1-instructions (supplement)
Processing lecture         homework-1 (exam)
Processing lecture         homework-1-discussion (discussionPrompt)
Processing section     programming-assignment
Processing lecture         programming-assignment-instructions (supplement)
Processing module  week-2-gossip-membership-and-grids
Processing section     overview
Processing lecture         week-2-overview (supplement)
Processing lecture         week-2-introduction (lecture)
Processing section     lesson-1-gossip
Processing lecture         1-1-multicast-problem (lecture)
Processing lecture         1-2-the-gossip-protocol (lecture)
Processing lecture         1-3-gossip-analysis (lecture)
Processing lecture         1-4-gossip-implementations (lecture)
Processing section     lesson-2-membership
Processing lecture         2-1-what-is-group-membership-list (lecture)
Processing lecture         2-2-failure-detectors (lecture)
Processing lecture         2-3-gossip-style-membership (lecture)
Processing lecture         2-4-which-is-the-best-failure-detector (lecture)
Processing lecture         2-5-another-probabilistic-failure-detector (lecture)
Processing lecture         2-6-dissemination-and-suspicion (lecture)
Processing section     lesson-3-grids
Processing lecture         3-1-grid-applications (lecture)
Processing lecture         3-2-grid-infrastucture (lecture)
Processing section     interview
Processing lecture         interview-with-william-gropp (lecture)
Processing section     homework
Processing lecture         homework-2-instructions (supplement)
Processing lecture         homework-2 (exam)
Processing lecture         homework-2-discussion (discussionPrompt)
Processing module  week-3-p2p-systems
Processing section     overview
Processing lecture         week-3-overview (supplement)
Processing lecture         week-3-introduction (lecture)
Processing section     lesson-p2p-systems
Processing lecture         1-p2p-systems-introduction (lecture)
Resetting dropped connection: www.coursera.org
Processing lecture         2-napster (lecture)
Processing lecture         3-gnutella (lecture)
Processing lecture         4-fasttrack-and-bittorrent (lecture)
Processing lecture         5-chord (lecture)
Processing lecture         6-failures-in-chord (lecture)
Processing lecture         7-pastry (lecture)
Processing lecture         8-kelips (lecture)
Processing section     interview
Processing lecture         blue-waters-supercomputer (lecture)
Processing section     homework
Processing lecture         homework-3-instructions (supplement)
Processing lecture         homework-3 (exam)
Processing lecture         homework-3-discussion (discussionPrompt)
Processing module  week-4-key-value-stores-time-and-ordering
Processing section     overview
Processing lecture         week-4-overview (supplement)
Processing lecture         week-4-introduction (lecture)
Processing section     lesson-1-key-value-stores
Processing lecture         1-1-why-key-value-nosql (lecture)
Processing lecture         1-2-cassandra (lecture)
Processing lecture         1-3-the-mystery-of-x-the-cap-theorem (lecture)
Processing lecture         1-4-the-consistency-spectrum (lecture)
Processing lecture         1-5-hbase (lecture)
Processing section     lesson-2-time-and-ordering
Processing lecture         2-1-introduction-and-basics (lecture)
Processing lecture         2-2-cristians-algorithm (lecture)
Processing lecture         2-3-ntp (lecture)
Processing lecture         2-4-lamport-timestamps (lecture)
Processing lecture         2-5-vector-clocks (lecture)
Processing section     interview
Processing lecture         interview-with-marcos-aguilera (lecture)
Processing lecture         optional-lamport-timestamps-ukulele-version (supplement)
Processing section     homework
Processing lecture         homework-4-instructions (supplement)
Processing lecture         homework-4 (exam)
Processing lecture         homework-4-discussion (discussionPrompt)
Processing module  week-5-classical-distributed-algorithms
Processing section     overview
Processing lecture         week-5-overview (supplement)
Processing lecture         week-5-introduction (lecture)
Processing section     lesson-1-snapshots
Processing lecture         1-1-what-is-global-snapshot (lecture)
Processing lecture         1-2-global-snapshot-algorithm (lecture)
Processing lecture         1-3-consistent-cuts (lecture)
Processing lecture         1-4-safety-and-liveness (lecture)
Processing section     lesson-2-multicast
Processing lecture         2-1-multicast-ordering (lecture)
Processing lecture         2-2-implementing-multicast-ordering-1 (lecture)
Processing lecture         2-3-implementing-multicast-ordering-2 (lecture)
Processing lecture         2-4-reliable-multicast (lecture)
Processing lecture         2-5-virtual-synchrony (lecture)
Processing section     lesson-3-paxos
Processing lecture         3-1-the-consensus-problem (lecture)
Processing lecture         3-2-consensus-in-synchronous-systems (lecture)
Processing lecture         3-3-paxos-simply (lecture)
Processing lecture         3-4-the-flp-proof-optional (lecture)
Processing section     interview
Processing lecture         interview-with-tushar-chandra (lecture)
Resetting dropped connection: www.coursera.org
Processing section     homework
Processing lecture         homework-5-instructions (supplement)
Processing lecture         homework-5 (exam)
Processing lecture         homework-5-discussion (discussionPrompt)
Processing section     programming-assignment
Processing lecture         gossip-protocol (gradedProgramming)
Error 403 Client Error: Forbidden for url: https://www.coursera.org/api/onDemandProgrammingLearnerAssignments.v1/op_vMOGiEeWr4g7T_DyXNw~O4lWE?fields=submissionLearnerSchema getting page https://www.coursera.org/api/onDemandProgrammingLearnerAssignments.v1/op_vMOGiEeWr4g7T_DyXNw~O4lWE?fields=submissionLearnerSchema
The server replied: {"errorCode":"auth.perms","message":"Item is locked","details":null}
HTTPError 403 Client Error: Forbidden for url: https://www.coursera.org/api/onDemandProgrammingLearnerAssignments.v1/op_vMOGiEeWr4g7T_DyXNw~O4lWE?fields=submissionLearnerSchema"

**Comment by balta2ar** [comment]
@MoHD20 Confirming. I'm afraid no, there is no way to skip this at the moment. This needs to be fixed. On the other hand, when the course starts at Aug 29, you should be able to download that.

**Comment by partobs-mdp** [comment]
@MoHD20 I have fixed your issue. See my fork of cousera-dl (hope it will be merged soon :)
