### ISSUE TITLE
Error on downloading completed course.

### ISSUE THREAD

**Issue by rnaby** [coursera-dl/coursera-dl#570]
I can't download the courses I've completed and got certificate. So is there any way those courses can be downloaded ?

Thanks in advance.

**Comment by balta2ar** [comment]
Your report is absolutely uninformative. I can't help you if you give me no details about your problem. Please read this section that explains how to do issue reports properly: https://github.com/coursera-dl/coursera-dl#filing-an-issuereporting-a-bug

**Comment by rnaby** [comment]
Sorry, I figured it out later. :+1: Actually there was nothing informative to report. Coursera is locking the exam after completion of the course. So the `coursera-dl` was rejected by Coursera.
