### ISSUE TITLE
course url structure doesn't match

### ISSUE THREAD

**Issue by madhawa-se** [coursera-dl/coursera-dl#571]
url format has changed.

i want to download this electronic course https://www.coursera.org/learn/electronics/home/

what should i type in to command line ?
i cannot type  something like coursera-dl -u <user> -p <pass> modelthinking-004
because there is no specific id like modelthinking-004 in that electronic course

**Comment by balta2ar** [comment]
```
coursera-dl -u -p electronics
```
```
https://www.coursera.org/learn/electronics/home/
                               ^^^^^^^^^^^
```
