### ISSUE TITLE
coursera-dl does not download quizzes 

### ISSUE THREAD

**Issue by educoursera** [coursera-dl/coursera-dl#576]
### Subject of the issue
downloading quizzes 

### Your environment
* Operating System (name/version):windows 10
* Python version:2.7
* coursera-dl version:0.8.0

### Steps to reproduce
I use following command to download courses but non of downloaded courses includes quizzes.
`coursera-dl -u ******@gmail.com -p ***** game-theory-1`

### Expected behaviour
Does coursera-dl download quizzes?
How can i download quizzes?

**Comment by balta2ar** [comment]
@educoursera use this option:
```
--download-quizzes    download quiz and exam questions. (Default: False).
```
