### ISSUE TITLE
401 Client Error: Unauthorized for url: https://www.coursera.org/api/login/v3

### ISSUE THREAD

**Issue by bjconlan** [coursera-dl/coursera-dl#580]
I'm getting a `Cannot login on coursera.org: 401 Client Error: Unauthorized for url: https://www.coursera.org/api/login/v3` when attempting to login using both the .netrc and -u/-p options.

* OS: Linux x86_64 (Ubuntu 16.04.1 (elementary)):
* Python version: 3.5
* coursera-dl version: 0.8.0

the problem can be seen simply by attempting to call `coursera-dl -n --list-courses` or `coursera-dl -p <user> -p <pass> --list-courses`

The output
```
root[authenticate_through_netrc] Trying netrc file /home/bjc/.netrc
root[main] coursera_dl version 0.8.0
root[main] Listing enrolled courses
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepape_auth_headers] Forging cookie header: csrftoken=WvlFctWgYTebdacCBOW6; csrf2_token_1utj9AWZ=mJkVi4WioN228NQv3F5idMLv.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 401 None
Traceback (most recent call last):
  File "/home/bjc/.local/lib/python3.5/site-packages/coursera/cookies.py", line 147, in login
    r.raise_for_status()
  File "/home/bjc/.local/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjc/.local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/home/bjc/.local/lib/python3.5/site-packages/coursera/coursera_dl.py", line 228, in main
    list_courses(args)
  File "/home/bjc/.local/lib/python3.5/site-packages/coursera/coursera_dl.py", line 106, in list_courses
    extractor = CourseraExtractor(session, args.username, args.password)
  File "/home/bjc/.local/lib/python3.5/site-packages/coursera/extractors.py", line 31, in __init__
    login(session, username, password)
  File "/home/bjc/.local/lib/python3.5/site-packages/coursera/cookies.py", line 154, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 401 Client Error: Unauthorized for url: https://www.coursera.org/api/login/v3
```

I've also attempted this using the cookie method (passing -c) with the dumped cookie details but still no dice.

It looks like coursera has changed there authentication endpoint?

**Comment by balta2ar** [comment]
I've just checked both `--list-courses` and the usual course download, with and without `--clear-cache` option and it's working fine. Maybe you should check your name/password?

**Comment by bjconlan** [comment]
Yes, you are correct balta2ar, I've stupidly managed to incorrectly type my password (multiple times). My apologies for wasting your time.

**Comment by mattrudo** [comment]
I also received the error. My password was correct, but the issue might have been due to a "$" in my password. I passed the following instead and manually typed the same password. It worked. 

./coursera-dl -u username --list-courses

**Comment by kartiknifm** [comment]
I study your blog and discover it quite appealing and useful. Moreover, I would propose you to keep on updating and posting such relevant articles from time to time. Keep doing the good work!!!!!
<a href="http://www.onlinenifm.com/">online course stock market</a>

**Comment by torresmateo** [comment]
I also had trouble due to a special character in my password

**Comment by barkerd427** [comment]
Surround your password with single quotes and it will work with a `$` in it.
