### ISSUE TITLE
Future Suggestion:

### ISSUE THREAD

**Issue by RohitLad** [coursera-dl/coursera-dl#584]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
A course had a broken link and coursera-dl kept on trying to make a new http connection. I'd suggest something like try making an http connection for twice at maximum, if not possible, SKIP the link.

### Your environment
* Operating System (name/version): Ubuntu 16.04
* Python version: 2.7
* coursera-dl version: The latest

**Comment by balta2ar** [comment]
Well, this is arguable whether two times is enough. Some users may have worse connections where it takes more attempts to download materials. The number of retries is not configurable for built-in downloader. However, you can use external downloader and configure it there. Related: https://github.com/coursera-dl/coursera-dl/issues/518
