### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by KOLANICH** [coursera-dl/coursera-dl#585]
### Subject of the issue
```command not found``` when executing coursera-dl

### Your environment
* Kubuntu 16.10
* Python version: 3.5.2+
* coursera-dl version: the one from pip

### Steps to reproduce
1 install pip3
```sudo apt install python3-pip```
2 ```pip3 install --user coursera-dl```
3 enter ```coursera-dl``` and get an error
4 enter ```python3 -m coursera``` and get an error
5 enter ```python3 -m coursera.coursera_dl``` and be happy that at least this way it works

### Expected behaviour
1 ```coursera-dl``` should work as expected
2 ```python3 -m coursera``` should work as expected

**Comment by balta2ar** [comment]
This is because your PYTHONPATH does not include your user directory (~/.local). Three options:
1. Manually adjust PYTHONPATH to include ~/.local.
2. Use sudo pip3 install
3. Install in a virtualenv.

**Comment by KOLANICH** [comment]
Thank you for the answer.
