### ISSUE TITLE
having trouble downloading

### ISSUE THREAD

**Issue by yeilho** [coursera-dl/coursera-dl#587]
I am getting 'Did not recieve csrf_token cookie'
I looked at other similar posts but none worked. One thing that I am not clear is the course name. 
https://class.coursera.org/<CLASS_NAME>/class/index

From what I can tell, here is what I see when I log in to coursera
https://www.coursera.org/learn/<CLASS_NAME>

Could you tell me what I am missing here?

./coursera-dl -u <> -p <> --debug -- cloud-computing
root[main] Downloading class: cloud-computing
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] https://class.coursera.org:443 "GET /cloud-computing HTTP/1.1" 200 None
root[main] Could not authenticate: **Did not recieve csrf_token cookie.**

**Comment by balta2ar** [comment]
Yes, you got the name of the class right, if you mean this class: https://www.coursera.org/learn/cloud-computing/home/welcome

For me it works fine. The log looks as follows:
```
→ coursera-dl --download-quizzes -n --path . --overwrite cloud-computing
coursera_dl version 0.8.0
Downloading class: cloud-computing (1 / 1)
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/cloud-computing?showLockedItems=true
 (38026 bytes)
Parsing syllabus of on-demand course. This may take some time, please be patient ...
Processing module  week-1-orientation-introduction-to-clouds-mapreduce
Processing section     orientation
```

Try upgrading to the latest version and using `--clear-cache` option.

**Comment by yeilho** [comment]
Thank you very much. I was able to resolve the issue.
