### ISSUE TITLE
Problem with "Could not authenticate: Did not find necessary cookies."

### ISSUE THREAD

**Issue by Atozzio** [coursera-dl/coursera-dl#590]
### Subject of the issue
I wanted to download some Coursera online courses using Coursera-dl but it came to  'Could not authenticate: Did not find necessary cookies.'

### Your environment
* Operating System (name/version): Win10 x64
* Python version: 2.7.13
* coursera-dl version: 0.8.0

### Steps to reproduce
* Is the problem happening with the latest version of the script?
I think so.
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
All of the six packages are up-to-date by March 6, 2017.
* What is the course that you are trying to access?
machine-learning, cyber-security-domain, and so on.
* What is the precise command line that you are using.
coursera-dl -u myemail@163.com -p ****** machine-learning
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.
root[main] Downloading class: machine-learning
root[download_class] Downloading old style class machine-learning
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file c:\users\winzz\appdata\local\temp\winzz_coursera_dl_cache\cookies\myemail@163.com.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] https://class.coursera.org:443 "GET /machine-learning HTTP/1.1" 200 None
root[login] Forging cookie header: csrftoken=hBgtBC1CsJ0alVozYzS2; csrf2_token_uhS7oWLu=G7B5u99g5ln7986nLpvYsn0s.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] https://www.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] https://class.coursera.org:443 "GET /machine-learning/auth/auth_redirector?type=login&subtype=normal HTTP/1.1" 200 None
root[down_the_wabbit_hole] Following https://class.coursera.org/machine-learning/auth/auth_redirector?type=login&subtype=normal to authenticate on class.coursera.org.
root[down_the_wabbit_hole] Exiting "deep" authentication.
root[main] Could not authenticate: Did not find necessary cookies.

### Expected behaviour
I've tried all method that I could googled including similar issues raised by other two users.
I've also modified this download_on_demand_class thing in coursera-dl.py but the situation was also not changed.
I expected the result should be started downloading or something like that.

### Actual behaviour
If "--debug" is not added to the end of command, the result would come to:
Downloading class: machine-learning
Logged in on coursera.org.
Could not authenticate: Did not find necessary cookies.

**Comment by balta2ar** [comment]
The course downloaded fine on my machine. Are you still having issues with that?

**Comment by Atozzio** [comment]
@balta2ar Thank you very much for your reply.
It is been to days since you replied me and I am so sorry about that I have not checked my email. The answer of your question is yes, and I am quite confused about why this could not work on my computer.
It would be very kind if you could send me a copy of the course if you would happy to.
My email address is winzzhhzzhh@163.com

**Comment by balta2ar** [comment]
@Atozzio Wow, that's weird. I clearly remember downloading this course but now I went on to check it and I can't find it on my HDD. Besides, your link redirects to something else. Could you please check whether the course URL is correct and that it opens in your browser and you can access its materials online? Maybe they renamed it or something.

**Comment by Atozzio** [comment]
@balta2ar Hi there, I'm sure that the course URL is: https://www.coursera.org/learn/machine-learning , which is machine learning classes by Stanford University.  Thank you again for doing this. :)

**Comment by KnolBee** [comment]
This course too has same issue,

https://www.coursera.org/learn/big-data-introduction

=====================================================
coursera_dl version 0.6.1
Downloading class: big-data-introduction
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Could not authenticate: Did not find necessary cookies.
======================================================

**Comment by rbrito** [comment]
Please, update your version of the application first.

You are using a very old version of the script.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br
