### ISSUE TITLE
I can't download only English subtitles

### ISSUE THREAD

**Issue by yejunsun** [coursera-dl/coursera-dl#592]
I found I can't specify a certain subtitle to download. so correct it. and send a pull request

**Comment by balta2ar** [comment]
Your pull request makes some tests fail. Please make sure they pass. Also, please provide an example where your fix helps, I'd like to reproduce the problem locally.

**Comment by yejunsun** [comment]
I fix the bugs. how can my pull request be merged?

**Comment by balta2ar** [comment]
Merged. Thanks for the contribution.
