### ISSUE TITLE
Can't download videos with proxy

### ISSUE THREAD

**Issue by banmoy** [coursera-dl/coursera-dl#594]
I can download videos with the command:
    coursera-dl --curl -u <username> -p <password> --downloader-arguments=<proxy> < classname>
but can't download the same video without using --curl. The error message is "Failed to establish a new connection : [Errno 110] Connection timed out".  Please give me some advice.

**Comment by balta2ar** [comment]
If you can download it with curl then what's the problem? I don't think there is native support for proxy in this downloader, so it's not unusual that you see the timeouts.

**Comment by banmoy** [comment]
@balta2ar That's if I use coursera-dl on windows without installing downloaders such as curl and wget, I can't download videos via proxy, is it right?

**Comment by balta2ar** [comment]
@banmoy Take a look at the suggestions in this issue: https://github.com/coursera-dl/coursera-dl/issues/205. I have an impression that if variables are set up correctly, the script should work behind proxy in Window.

**Comment by banmoy** [comment]
@balta2ar After I set the HTTPS_PROXY environment variable as mentioned in #205, it works. Thanks very much.
