### ISSUE TITLE
Materials in a separate "Resources" section

### ISSUE THREAD

**Issue by thomasmktong** [coursera-dl/coursera-dl#597]
### Materials in a separate "Resources" section

For some courses (e.g. uva-darden-agile-testing), a new section "Resources" is used to place lecture notes and other reference materials. It would be great if this tool can crawl that as well.

![screen shot 2017-03-26 at 10 34 34 pm](https://cloud.githubusercontent.com/assets/7279232/24332175/99086e94-1274-11e7-8c0b-92235ed033b6.png)

**Comment by dzhuang** [comment]
I also found this issue.

**Comment by dzhuang** [comment]
Please use the git version with the latest commit. I think it can now be closed. @balta2ar

**Comment by thomasmktong** [comment]
thanks very much!!

**Comment by balta2ar** [comment]
For the record, this is available since version 0.9.0.
