### ISSUE TITLE
Can not download video

### ISSUE THREAD

**Issue by suoigwg** [coursera-dl/coursera-dl#598]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Describe your issue here.
Bug report
### Your environment
* Operating System (name/version):Mac OS 10.12.4
* Python version:3.6
* coursera-dl version: 0.8.0

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:
coursera-dl [course name]
* Is the problem happening with the latest version of the script?
Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
Yes
* What is the course that you are trying to access?
https://www.coursera.org/learn/microeconomics
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched)
I run it as a shell script, it used to work with python 3.6
coursera-dl "$1" -u  -p 

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.
The terminal did not show the progress when downloading video, neither does it download it
### Expected behaviour
Tell us what should happen.
It should show the download progress in percentage
### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.
It halts for a while and then skips the video

**Comment by balta2ar** [comment]
@suoigwg From your report I have no idea what might be wrong (and it works for me). Show me a screenshot or record a video of your console (don't forget to cover your credentials).

**Comment by suoigwg** [comment]
@balta2ar  Thanks for your reply. You may check this video here
It halts as in the first screenshot and then changes to screenshot2

![screen shot 2017-03-30 at 5 59 53 pm](https://cloud.githubusercontent.com/assets/15700090/24499499/86252364-1574-11e7-857f-f24a5cde5342.jpg)
![screen shot 2017-03-30 at 6 00 02 pm](https://cloud.githubusercontent.com/assets/15700090/24499564/b4ee4270-1574-11e7-8e5b-d8d9fcba523a.jpg)

**Comment by balta2ar** [comment]
@suoigwg Sorry, from this information (`No route to host` message) I can only presume it's something with your connection and your Internet provider. Can you access materials in your web browser? I can only suggest trying to download again, or trying to download over TOR or any other proxy.

**Comment by suoigwg** [comment]
@balta2ar 
Thanks, I think I've figured it out.
**It is blocked by the fucking GFW here in CHINA**, I try with a VPN in HK and it works
Thanks for your help!
