### ISSUE TITLE
Could not authenticate: Cannot login on coursera.org

### ISSUE THREAD

**Issue by educoursera** [coursera-dl/coursera-dl#604]
### Subject of the issue
Could not authenticate: Cannot login on coursera.org

### Your environment
Could not authenticate: Cannot login on coursera.org
    Operating System (name/version):windows 10
    Python version:2.7
    coursera-dl version:0.8.0

### Steps to reproduce
P:\coursera>coursera-dl -u ****@gmail.com -p *** --download-quizzes --debug systems-thinking

### Expected behaviour
Tell us what should happen.

### Actual behaviour
P:\coursera>coursera-dl -u ***@gmail.com -p *** --download-quizzes --debug systems-thinking
root[main] coursera_dl version 0.8.0
root[main] Downloading class: systems-thinking (1 / 1)
root[download_class] Downloading new style (on demand) class systems-thinking
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepape_auth_headers] Forging cookie header: csrftoken=*******************************************************.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 401 None
root[main] Could not authenticate: Cannot login on coursera.org: 401 Client Error: Unauthorized for url: https://www.coursera.org/api/login/v3

**Comment by rbrito** [comment]
I just tested and it works fine for me.

When you signed up for Coursera, did you use something like Facebook or any similar method or did you use a user and password?

**Comment by educoursera** [comment]
It is working now. I don't know why :(

**Comment by rbrito** [comment]
Thanks for the confirmation.

**Comment by nawaz123** [comment]
i am facing facing following problem  @rbrito kindly help?
coursera-dl -u username -p password modelthinking-004

coursera_dl version 0.11.4
Traceback (most recent call last):
  File "D:\courses\coursera-dl\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\courses\coursera-dl\\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "D:\courses\coursera-dl\coursera\coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "D:\courses\coursera-dl\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by rbrito** [comment]
I'm unable to help at this moment... Everything bad that can happen in my life during this past 30 days has happened so far:

* death in family, creating a huge void that left everybody both emotionally and also bureaucratically lost
* fire at home (suspected of being a arson)
* health problems
* material problems

Life sucks so bad right now and I am barely standing up...

Sorry...

**Comment by padrian** [comment]
@rbrito Hey man sorry for your situation.
just hang in there.
i hope it all works out for you sir.

**Comment by padrian** [comment]
@nawaz123 check this out > https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-462163921 hope it helps
