### ISSUE TITLE
I can't download the video ~ 

### ISSUE THREAD

**Issue by jenkey2011** [coursera-dl/coursera-dl#606]
# I can't download the video ~ 

### Your environment
* win10
* Python version : 3.6
* coursera-dl version:0.8
* PS：I'm from China…… 
### Steps to reproduce
> coursera-dl -u xxx -p xxxx -b html-css-javascript

Then it works , but only the subtitles were downloaded ; And the cmd shows "The following URLs (64) could not be downloaded:" , they're all video links;

**Comment by wanghoppe** [comment]
Me too have the issue.... Could someone help??

**Comment by lvhuiyang** [comment]
I met the same problem yesterday.

I use the command `coursera-dl -u xx@xxx.com -p xxx os-pku --wget` to solve it. 
 (env: Mac OS, wget, python3.6)

**Comment by balta2ar** [comment]
Are you guys all from China? Did you try downloading over a VPN or Tor? If it's your government's firewall, we can't do anything about it, use proxies, VPNs and Tor.

**Comment by jenkey2011** [comment]
I guess so…… What a pity.

**Comment by FBryce** [comment]
Hi, If you are from China, adding  "52.84.246.72  d3c33hcgiwev3.cloudfront.net" in the host file sand fresh dns with " ipconfig/flushdns"  may work

**Comment by wanghoppe** [comment]
@FBryce It worked! Thank you so much.

**Comment by XiangBicheng** [comment]
@FBryce Nice! Thank you for useful information.

**Comment by techlarry** [comment]
Good job @FBryce, I downloaded several courses manually because of the issue. It wasted me at least half day to download files....

**Comment by balta2ar** [comment]
> Hi, If you are from China, adding "52.84.246.72 d3c33hcgiwev3.cloudfront.net" in the host file and fresh dns with " ipconfig/flushdns" may work

I've added your comment to the readme. Thanks! Closing.

**Comment by wenxingxing** [comment]
It works, thanks~~

**Comment by shuoooo** [comment]
> Hi, If you are from China, adding "52.84.246.72 d3c33hcgiwev3.cloudfront.net" in the host file and fresh dns with " ipconfig/flushdns" may work

Works beautifully, thanks a lot

**Comment by senmonster** [comment]
windows :fresh dns with " ipconfig/flushdns"
linux: sudo /etc/init.d/networking restart

**Comment by senmonster** [comment]
sudo /etc/init.d/dns-clean restart

**Comment by senmonster** [comment]
> I met the same problem yesterday.
> 
> I use the command `coursera-dl -u xx@xxx.com -p xxx course_name --wget` to solve it.
> (env: Mac OS, wget, python3.6)

THIS works!!!Thanks a lot!

**Comment by holyodin776** [comment]
Thanks，still working

**Comment by zhangxiann** [comment]
In 2020, it doesn`t work.

**Comment by zhangxiann** [comment]
I found several new ips that can work.
```
52.84.246.90    d3c33hcgiwev3.cloudfront.net
52.84.246.252    d3c33hcgiwev3.cloudfront.net
52.84.246.144    d3c33hcgiwev3.cloudfront.net
52.84.246.72    d3c33hcgiwev3.cloudfront.net
52.84.246.106    d3c33hcgiwev3.cloudfront.net
52.84.246.135    d3c33hcgiwev3.cloudfront.net
52.84.246.114    d3c33hcgiwev3.cloudfront.net
52.84.246.90    d3c33hcgiwev3.cloudfront.net
52.84.246.227    d3c33hcgiwev3.cloudfront.net
```

**Comment by hopkings2008** [comment]
thanks @zhangxiann , it works now.

**Comment by ppue** [comment]
thanks @zhangxiann , it still works now.
