### ISSUE TITLE
How to download Coursera Old Stack Courses

### ISSUE THREAD

**Issue by acbetter** [coursera-dl/coursera-dl#608]
You know Coursera has shuted down their old stack on Jun 30th 2016. 
I wanna to download the one of that called `nlangp-001` but has `Error 404 Client Error: Not Found for url:`. 
So is there anyway for me to download the due videos?

Here is a Coursera Old Stack Courses sheet, it may be helpful.
[Coursera Old Stack Courses (List Organized by Class Central)](https://docs.google.com/spreadsheets/d/1kaWxZG3krI83WfdzlExWL-_S5UBai-CYuofGR5DZcd0/edit#gid=1433118913)

### Your environment
* Operating System (name/version): macOS/10.12.4
* Python version: 3.6.0
* coursera-dl version: lastest (0.8.0)

**Comment by balta2ar** [comment]
Unfortunately, no. At least their old API is not working any more and I don't know any other way to retrieve that data from Coursera site.
Try searching for this course on torrents, I think there were people who saved many of those old courses.

**Comment by balta2ar** [comment]
@acbetter It looks like here is the course you want: http://academictorrents.com/details/8a8f93e18dd6c46c48ee2936ed500b1ff4cc9175/tech&filelist=1

**Comment by acbetter** [comment]
Thank You !!! It's I need !!! 
I'm sorry to hear that Coursera close old video...
