### ISSUE TITLE
How to use proxy in Linux?

### ISSUE THREAD

**Issue by Visitant0226** [coursera-dl/coursera-dl#613]
### Subject of the issue
I can‘t download the video directly from the Coursera, I need proxy to download, but I didn't find how to use the proxy on Linux.I tried to set up the system proxy, but it doesn't seem to use the system proxy.

### Your environment
* Operating System (name/version):Ubuntu 16.04 LTS
* Python version: 3.5.2
* coursera-dl version: 0.9.0

**Comment by balta2ar** [comment]
Like this: https://github.com/coursera-dl/coursera-dl/issues/205#issuecomment-28878434
