### ISSUE TITLE
[SOLVED]: Coursera-dl v0.9.0 still errors to "Could not authenticate: Did not find necessary cookies."!

### ISSUE THREAD

**Issue by zenny** [coursera-dl/coursera-dl#614]
### Subject of the issue
coursera-dl outputs "Could not authenticate: Did not find necessary cookies." This has been reported with previous versions (https://github.com/coursera-dl/coursera-dl/issues?utf8=%E2%9C%93&q=%20Could%20not%20authenticate%3A%20Did%20not%20find%20necessary%20cookies.), but none of them reportedly has provided solution. Therefore, reporting this again.

### Your environment
* Operating System (name/version): Ubuntu 14.04
* Python version: 3.4
* coursera-dl version: 0.9.0

###Command line output
```
$ coursera-dl -n /home/zenny/.netrc clinical-trials
Downloading class: clinical-trials
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): class.coursera.org
**Could not authenticate: Did not find necessary cookies.**
```
and disconnects.

Any input? Thanks!

Cheers,
/z

**Comment by zenny** [comment]
The culprit is the 'pip install coursera-dl'.

The best way to avoid this error is to compile coursera-dl from github as follows:

```
mkdir /path/to/destination/my-coursera
virtualenv -p python3 my-coursera
cd my-coursera
source bin/activate
git clone https://github.com/coursera-dl/coursera
cd coursera
pip install -r requirements.txt
./coursera-dl -n ~/.netrc <course_name>
```

Hope this helps!

**Comment by balta2ar** [comment]
Closing then.

**Comment by ashupednekar** [comment]
Not working
