### ISSUE TITLE
how to skip 404 error ,just nobreak download all matrials except unnessary  but 404 error

### ISSUE THREAD

**Issue by landscape-ooo** [coursera-dl/coursera-dl#615]
### Subject of the issue
my target is nobreak download, evenif some 404 matrials  occured  
###relate work 
exclude format issue  
 -f "mp4, pdf" etc ，didn't satisfied my expect , some error matrials' format ,unknown 
regular filter 
-rf "expression" , i'm a freshman for regular expression ,sorry 

### Your environment
* Operating System (name/version):
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty

* Python version:
python --version 
Python 2.7.13
* coursera-dl version:
git show 
commit 154ef8dfef287bd6a276953bb4382f999b56a0af
Author: Yuri Bochkarev <baltazar.bz@gmail.com>
Date:   Mon May 29 19:50:34 2017 +0300

    Bump version (0.8.0 -> 0.9.0)

### Steps to reproduce

* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
   my execute file just download from github.com ,by command "git clone 'xxxx' && cd coursera_dl && ./coursera-dl ......" 

* What is the course that you are trying to access?
  machine-learning   (Andrew Ng)
   @see https://www.coursera.org/learn/machine-learning/home/welcome

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).

./coursera-dl  -u xxx  -p xxxx --resume  machine-learning  --disable-url-skipping  --clear-cache    --verbose --debug --path=/tmp/myc --aria2 

with or without  --disable-url-skipping , not working for nobreak 
 with or without  --aria2 , not working for nobreak 

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

===================================================

root[main] coursera_dl version 0.9.0
root[main] Downloading class: machine-learning (1 / 1)
root[download_class] Downloading new style (on demand) class machine-learning
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepape_auth_headers] Forging cookie header: csrftoken=dPwBPz1dqlUWVDd7PZEj; csrf2_token_fZHSofFi=rUcpSyS6HO9dVyrPAam06Qgj.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/opencourse.v1/course/machine-learning?showLockedItems=true HTTP/1.1" 200 None
root[_get_on_demand_syllabus] Downloaded https://www.coursera.org/api/opencourse.v1/course/machine-learning?showLockedItems=true (76758 bytes)
root[_parse_on_demand_syllabus] Parsing syllabus of on-demand course. This may take some time, please be patient ...
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled HTTP/1.1" 200 None
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/onDemandCourseMaterials.v1/?q=slug&slug=machine-learning&includes=moduleIds%2ClessonIds%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2CitemIds%2Ctracks&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight)%2ConDemandCourseMaterialItems.v1(name%2Cslug%2CtimeCommitment%2Ccontent%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true HTTP/1.1" 200 None
root[_parse_on_demand_syllabus] Processing module  introduction
root[_parse_on_demand_syllabus] Processing section     welcome
root[_parse_on_demand_syllabus] Processing lecture         welcome-to-machine-learning (lecture)
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/opencourse.v1/video/rKsjlA4fEeW7HSIACy8Jxg HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <rKsjlA4fEeW7HSIACy8Jxg>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <rKsjlA4fEeW7HSIACy8Jxg>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 540p of <rKsjlA4fEeW7HSIACy8Jxg>.
root[_extract_subtitles_from_video_dom] Gathering subtitle URLs for video_id <rKsjlA4fEeW7HSIACy8Jxg>.
root[_extract_subtitles_from_video_dom] Gathering transcript URLs for video_id <rKsjlA4fEeW7HSIACy8Jxg>.
root[_parse_on_demand_syllabus] Processing lecture         machine-learning-honor-code (supplement)
root[extract_links_from_supplement] Gathering supplement URLs for element_id <nh65Z>.
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/onDemandSupplements.v1/Gtv4Xb1-EeS-ViIACwYKVQ~nh65Z?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
root[_parse_on_demand_syllabus] Processing section     introduction
root[_parse_on_demand_syllabus] Processing lecture         welcome (lecture)
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/opencourse.v1/video/Iq7-fL1-EeSqHiIAC2idzw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <Iq7-fL1-EeSqHiIAC2idzw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <Iq7-fL1-EeSqHiIAC2idzw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 540p of <Iq7-fL1-EeSqHiIAC2idzw>.
root[_extract_subtitles_from_video_dom] Gathering subtitle URLs for video_id <Iq7-fL1-EeSqHiIAC2idzw>.
root[_extract_subtitles_from_video_dom] Gathering transcript URLs for video_id <Iq7-fL1-EeSqHiIAC2idzw>.
root[_parse_on_demand_syllabus] Processing lecture         what-is-machine-learning (lecture)
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/opencourse.v1/video/6Ypr1hQ-EeeFZBJX5mIoyg HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <6Ypr1hQ-EeeFZBJX5mIoyg>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <6Ypr1hQ-EeeFZBJX5mIoyg>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 540p of <6Ypr1hQ-EeeFZBJX5mIoyg>.
root[_extract_subtitles_from_video_dom] Gathering subtitle URLs for video_id <6Ypr1hQ-EeeFZBJX5mIoyg>.
root[_extract_subtitles_from_video_dom] Gathering transcript URLs for video_id <6Ypr1hQ-EeeFZBJX5mIoyg>.
root[_parse_on_demand_syllabus] Processing lecture         what-is-machine-learning (supplement)
root[extract_links_from_supplement] Gathering supplement URLs for element_id <aAgxl>.
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/onDemandSupplements.v1/Gtv4Xb1-EeS-ViIACwYKVQ~aAgxl?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
root[_parse_on_demand_syllabus] Processing lecture         how-to-use-discussion-forums (supplement)
root[extract_links_from_supplement] Gathering supplement URLs for element_id <66jBd>.
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/onDemandSupplements.v1/Gtv4Xb1-EeS-ViIACwYKVQ~66jBd?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
root[_parse_on_demand_syllabus] Processing lecture         supervised-learning (lecture)
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/opencourse.v1/video/IrD6Tb1-EeSqHiIAC2idzw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <IrD6Tb1-EeSqHiIAC2idzw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <IrD6Tb1-EeSqHiIAC2idzw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 540p of <IrD6Tb1-EeSqHiIAC2idzw>.
root[_extract_subtitles_from_video_dom] Gathering subtitle URLs for video_id <IrD6Tb1-EeSqHiIAC2idzw>.
root[_extract_subtitles_from_video_dom] Gathering transcript URLs for video_id <IrD6Tb1-EeSqHiIAC2idzw>.
root[_parse_on_demand_syllabus] Processing lecture         supervised-learning (supplement)
root[extract_links_from_supplement] Gathering supplement URLs for element_id <NKVJ0>.
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/onDemandSupplements.v1/Gtv4Xb1-EeS-ViIACwYKVQ~NKVJ0?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
root[_parse_on_demand_syllabus] Processing lecture         unsupervised-learning (lecture)
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/opencourse.v1/video/IrFvfr1-EeSqHiIAC2idzw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <IrFvfr1-EeSqHiIAC2idzw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <IrFvfr1-EeSqHiIAC2idzw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 540p of <IrFvfr1-EeSqHiIAC2idzw>.
root[_extract_subtitles_from_video_dom] Gathering subtitle URLs for video_id <IrFvfr1-EeSqHiIAC2idzw>.
root[_extract_subtitles_from_video_dom] Gathering transcript URLs for video_id <IrFvfr1-EeSqHiIAC2idzw>.
root[_parse_on_demand_syllabus] Processing lecture         unsupervised-learning (supplement)
root[extract_links_from_supplement] Gathering supplement URLs for element_id <1O0Bk>.
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/onDemandSupplements.v1/Gtv4Xb1-EeS-ViIACwYKVQ~1O0Bk?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
root[_parse_on_demand_syllabus] Processing lecture         who-are-mentors (supplement)
root[extract_links_from_supplement] Gathering supplement URLs for element_id <JBzFm>.
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/onDemandSupplements.v1/Gtv4Xb1-EeS-ViIACwYKVQ~JBzFm?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
root[_parse_on_demand_syllabus] Processing lecture         get-to-know-your-classmates (supplement)
root[extract_links_from_supplement] Gathering supplement URLs for element_id <dJCBb>.
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/onDemandSupplements.v1/Gtv4Xb1-EeS-ViIACwYKVQ~dJCBb?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
root[_parse_on_demand_syllabus] Processing lecture         frequently-asked-questions (supplement)
root[extract_links_from_supplement] Gathering supplement URLs for element_id <gBboB>.
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/onDemandSupplements.v1/Gtv4Xb1-EeS-ViIACwYKVQ~gBboB?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
root[_parse_on_demand_syllabus] Processing section     review
root[_parse_on_demand_syllabus] Processing lecture         lecture-slides (supplement)
root[extract_links_from_supplement] Gathering supplement URLs for element_id <d5Pt1>.
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/onDemandSupplements.v1/Gtv4Xb1-EeS-ViIACwYKVQ~d5Pt1?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/assetUrls.v1?ids=hWubsZSCEeaMjBKAx0HcyA HTTP/1.1" 200 None
root[_parse_on_demand_syllabus] Processing lecture         introduction (exam)
root[_parse_on_demand_syllabus] Processing module  linear-regression-with-one-variable
root[_parse_on_demand_syllabus] Processing section     model-and-cost-function
root[_parse_on_demand_syllabus] Processing lecture         model-representation (lecture)
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/opencourse.v1/video/IrILv71-EeSqHiIAC2idzw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <IrILv71-EeSqHiIAC2idzw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <IrILv71-EeSqHiIAC2idzw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 540p of <IrILv71-EeSqHiIAC2idzw>.
root[_extract_subtitles_from_video_dom] Gathering subtitle URLs for video_id <IrILv71-EeSqHiIAC2idzw>.
root[_extract_subtitles_from_video_dom] Gathering transcript URLs for video_id <IrILv71-EeSqHiIAC2idzw>.
root[_parse_on_demand_syllabus] Processing lecture         model-representation (supplement)
root[extract_links_from_supplement] Gathering supplement URLs for element_id <cRa2m>.
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/onDemandSupplements.v1/Gtv4Xb1-EeS-ViIACwYKVQ~cRa2m?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "GET /api/assets.v1?ids=H6qTdZmYEeaagxL7xdFKxA HTTP/1.1" 200 None
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): d3c33hcgiwev3.cloudfront.net

===================================================

Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/landscape/Documents/ebook/course_dl_src/coursera/coursera_dl.py", line 237, in main
    error_occured, completed = download_class(args, class_name)
  File "/home/landscape/Documents/ebook/course_dl_src/coursera/coursera_dl.py", line 212, in download_class
    return download_on_demand_class(args, class_name)
  File "/home/landscape/Documents/ebook/course_dl_src/coursera/coursera_dl.py", line 139, in download_on_demand_class
    args.mathjax_cdn_url
  File "/home/landscape/Documents/ebook/course_dl_src/coursera/extractors.py", line 56, in get_modules
    download_quizzes, mathjax_cdn_url)
  File "/home/landscape/Documents/ebook/course_dl_src/coursera/extractors.py", line 149, in _parse_on_demand_syllabus
    lecture['id'])
  File "/home/landscape/Documents/ebook/course_dl_src/coursera/api.py", line 910, in extract_links_from_supplement
    instructions = (IN_MEMORY_MARKER + self._markup_to_html(value),
  File "/home/landscape/Documents/ebook/course_dl_src/coursera/api.py", line 165, in __call__
    self._convert_markup_images(soup)
  File "/home/landscape/Documents/ebook/course_dl_src/coursera/api.py", line 224, in _convert_markup_images
    self._asset_retriever(asset_ids)
  File "/home/landscape/Documents/ebook/course_dl_src/coursera/api.py", line 375, in __call__
    reply = get_reply(self._session, url)
  File "/home/landscape/Documents/ebook/course_dl_src/coursera/network.py", line 44, in get_reply
    reply = session.send(prepared_request)
  File "/home/landscape/Documents/ebook/course_dl/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/landscape/Documents/ebook/course_dl/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='d3c33hcgiwev3.cloudfront.net', port=443): Max retries exceeded with url: /imageAssetProxy.v1/H6qTdZmYEeaagxL7xdFKxA_2f0f671110e8f7446bb2b5b2f75a8874_Screenshot-2016-10-23-20.14.58.png?expiry=1502496000000&hmac=bWRkD0bCqEdyPLI3_0p1sKkKLvuZEhb_yyQVeK3VRvg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f98e6dbf490>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by landscape-ooo** [comment]
[solved_by_other_issue](https://github.com/coursera-dl/coursera-dl/issues/606#issuecomment-305698809)

I edited my hosts file ,it is solved .

**Comment by gitdeepr** [comment]
--disable-url-skipping option on coursera-dl ? any idea
