### ISSUE TITLE
ImportError: cannot import name 'HTMLParseError'

### ISSUE THREAD

**Issue by a-eid** [coursera-dl/coursera-dl#616]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
ImportError: cannot import name 'HTMLParseError'
![](https://i.imgur.com/wd9Cam1.png)

### Your environment
* Operating System (name/version): ubuntu 17.04
* Python version: 3.6.0
* coursera-dl version: error occurs when `coursera-dl --version` but I have just installed it 

steps to reproduce is: 
1- type `coursera-dl` .
2- that is it.

**Comment by balta2ar** [comment]
Try this suggestion: https://stackoverflow.com/questions/28745153/importing-bs4-in-python-3-5
Feel free to comment if it doesn't help.

**Comment by egyshell** [comment]
pip install --upgrade beautifulsoup4
