### ISSUE TITLE
coursera-dl.conf settings?

### ISSUE THREAD

**Issue by zenny** [coursera-dl/coursera-dl#617]
Hi,

Can anyone point to detailed setting options for `coursera-dl.conf` besides a few lines at https://github.com/coursera-dl/coursera-dl#running-the-script? Or any man pages?

Cheers,
/z

**Comment by balta2ar** [comment]
I think they are exactly the same as the command-line options, that was the point. Instead of specifying everything in the command line, you put some of the options into the file.

**Comment by Issam9973** [comment]
This worked for me:

`username = user@email.com
password = xxxxx
subtitle-language = en
playlist = true
overwrite = true`

File name _coursera-dl.conf_ located at the same folder where command line is used.

A different issue related to the unavailable api server is solved by "keep trying". Here is [link to the resolution note](https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-459727078).

Hope this helps :)
