### ISSUE TITLE
Installing issues

### ISSUE THREAD

**Issue by yusufnb** [coursera-dl/coursera-dl#623]
Could you please have a Vagrant image made available with coursera-dl? Trying to install on mac with python3 pip3 is quite a mess.

Thanks

**Comment by balta2ar** [comment]
You mean Vagrant + Ansible, right?

**Comment by rbrito** [comment]
I don't really know what is meant by "Vagrant image", since vagrant is meant to create images... OTOH, doesn't the docker stuff that we already have in our repo help?

**Comment by yusufnb** [comment]
Sorry for being bit vague. I meant a Vagrant box. Something such as

1. `vagrant init cousera-dl` 
2. `vagrant up`
would be a nice alternative to getting this up and running.

This is a great tool btw and super helpful.
