### ISSUE TITLE
Skip exact files

### ISSUE THREAD

**Issue by RomanVolkov** [coursera-dl/coursera-dl#626]
How it's possible to skip exact files? Process sometimes "sleeps" on some files outside of Coursera that aren't accessible any more. Or is there any way to add download timeout for files, not whole course?

**Comment by balta2ar** [comment]
Presently there is no way to do that, but you can use external donwloader and configure timeouts there as I described in the README: https://github.com/coursera-dl/coursera-dl#download-timeouts
Tell me if that helps.

**Comment by RomanVolkov** [comment]
@balta2ar  thanks, will try
