### ISSUE TITLE
Not getting URL

### ISSUE THREAD

**Issue by satishdesh** [coursera-dl/coursera-dl#627]
Hello Balta

Thanks for the wonderful script though not working for me. I got the my course list at coursera but having an error not getting url. Please go through the error below.. I can download the videos singularly if i log into the course but unable to have bulk download via dl.

See this copy paste error 

C:\Users\satish>coursera-dl -u satishdesh@outlook.com -p ………..--list-courses
coursera_dl version 0.9.0
Listing enrolled courses
Logged in on coursera.org.
Found 12 courses
duke-programming-web
responsivedesign
javascript
introcss
html
nand2tetris2
learn-to-program
python
intro-programming
communication
learning-how-to-learn
public-speaking-deprecated

C:\Users\satish>coursera-dl -u satishdesh@outlook.com -p ……….. https://www.coursera.org/learn/du
ke-programming-web/home/welcome
coursera_dl version 0.9.0
Downloading class: https://www.coursera.org/learn/duke-programming-web/home/welcome (1 / 1)
Logged in on coursera.org.
Error 404 Client Error: Not Found for url: https://www.coursera.org/api/opencourse.v1/course/https:/
/www.coursera.org/learn/duke-programming-web/home/welcome?showLockedItems=true getting page https://
www.coursera.org/api/opencourse.v1/course/https://www.coursera.org/learn/duke-programming-web/home/w
elcome?showLockedItems=true
The server replied: {"message":"","statusCode":404}
HTTPError 404 Client Error: Not Found for url: https://www.coursera.org/api/opencourse.v1/course/htt
ps://www.coursera.org/learn/duke-programming-web/home/welcome?showLockedItems=true
 Regards
satish

**Comment by rbrito** [comment]
Hi.

On Fri, Oct 20, 2017 at 11:36 AM, satishdesh <notifications@github.com> wrote:
> C:\Users\satish>coursera-dl -u satishdesh@outlook.com -p ……….. https://www.coursera.org/learn/du
> ke-programming-web/home/welcome
(...)

Please, use only the course name, not the URL.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by satishdesh** [comment]
Hello 

Great. It worked just like charm.Thanks.

**Comment by satishdesh** [comment]
Hello


Great. It worked just like charm. Thanks.




                    Thanks & Regards.

                    Yours sincerely
                             Satish



________________________________

**Comment by nhohung** [comment]
Hello,

I have similar issue, some courses can be downloaded a couple of days before but yesterday it started not working.

Course listing is fine:
`coursera-dl -u <my_email> -p <my_password> --list-courses`
coursera_dl version 0.11.2
Listing enrolled courses
Logged in on coursera.org.
Found 6 courses
data-science-project
convolutional-neural-networks
deep-neural-networks
nlp-sequence-models
neural-networks-deep-learning
machine-learning-projects

but when I try downloading any of them, a 404 error shows up:
`coursera-dl -u <my_email> -p <my_password> deep-neural-network`
coursera_dl version 0.11.2
Downloading class: deep-neural-network (1 / 1)
Logged in on coursera.org.
Error 404 Client Error: Not Found for url: https://www.coursera.org/api/opencourse.v1/course/deep-neural-network?showLockedItems=true getting page https://api.coursera.org/api/opencourse.v1/course/deep-neural-network?showLockedItems=true
The server replied: {"message":"","statusCode":404}
HTTPError 404 Client Error: Not Found for url: https://api.coursera.org/api/opencourse.v1/course/deep-neural-network?showLockedItems=true

It just worked before and now none of them is working (I use windows 7). Any help is appreciated.

Thank,
Hung

**Comment by balta2ar** [comment]
This is a known problem: https://github.com/coursera-dl/coursera-dl/issues/673
