### ISSUE TITLE
Failed to establish a new connection: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by phoenix198425** [coursera-dl/coursera-dl#628]
🚨
### Subject of the issue
File download failed with error "Failed to establish a new connection: [Errno 101] Network is unreachable"

### Your environment
* Operating System (name/version): Ubuntu 16.04
* Python version:  3.5.2
* coursera-dl version: 0.9.0

### Steps to reproduce
```
coursera-dl -u username -p password --path /home/epcc/coursera-lessons/  machine-learning --debug
```

* Is the problem happening with the latest version of the script? Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. Yes
* What is the course that you are trying to access? machine-learning
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Download completed successfully.

### Actual behaviour
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fd0dbb5ec18>: Failed to establish a new connection: [Errno 101] Network is unreachable
```

(Edit by rbrito: Fix formatting.)

**Comment by rbrito** [comment]
Is your Internet connection working OK? Are you using a proxy? Do you need to use a proxy? We need more information.

**Comment by rbrito** [comment]
Any further information?

**Comment by 142ayushkumar** [comment]
@rbito I am having same problems. Yes, I am using proxy and yes my internet connection is working OK.

**Comment by hyyfrank** [comment]
i got the same issue , i use proxy, so you mean i need to setup the proxy when downloading the coursera?

**Comment by balta2ar** [comment]
Judging by the error message, there is little we can do on our side, as it looks like a networking issue. Users from China are known to have issue downloading from Coursera servers, but maybe this helps: https://github.com/coursera-dl/coursera-dl#china-issues.

**Comment by phoenix198425** [comment]
I changed my computer OS to be windows, but I believe it's the issue that @balta2ar refers to. Thanks a lot!

**Comment by 1907150961** [comment]
i have used proxy,and it sent the same error,and i do not know how to solve it @rbrito
