### ISSUE TITLE
Could not authenticate: Cannot login on coursera.org

### ISSUE THREAD

**Issue by MR-T77** [coursera-dl/coursera-dl#630]
### Subject of the issue
Can't connect with the above message: coursera_dl version 0.9.0
Downloading class: machine-learning (1 / 1)
Could not authenticate: Cannot login on coursera.org: 401 Client Error: Unauthorized for url: https://www.coursera.org/api/login/v3

### Your environment
* Operating System (name/version): MacOs Sierra
* Python version: 3.5
* coursera-dl version: 0.9

### Steps to reproduce
Just trying to run

**Comment by rbrito** [comment]
Please, let us know the entire command line that you used. Otherwise, we will not be able to help.

**Comment by dnharry** [comment]
Sorry to bother.
I have resolve the problem.

Rogério Brito wrote:

**Comment by MR-T77** [comment]
Entire line (without private info is):
coursera-dl -u <email> -p <password> machine-learning
(<email> and <password> substituted by correspondent values (without < or >)

**Comment by rbrito** [comment]
@MR-T77,

Please, include the full output of running coursera-dl with the `--debug` option specified. Otherwise, it is hard to know what is going on.

**Comment by MR-T77** [comment]
Hi: here goes the full output:
root[main] coursera_dl version 0.9.0
root[main] Downloading class: machine-learning (1 / 1)
root[download_class] Downloading new style (on demand) class machine-learning
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepape_auth_headers] Forging cookie header: csrftoken=7rQ1cF7mHxhHis5nSusu; csrf2_token_2CoridyT=EMYHDfTve5l7wPRgNdEsvHK2.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 401 None
root[main] Could not authenticate: Cannot login on coursera.org: 401 Client Error: Unauthorized for url: https://www.coursera.org/api/login/v3

**Comment by evgeny-sobol** [comment]
Same problem:

```
(env) X:\Users\evgeny\Downloads\coursera-dl>python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> print(platform.platform())
Windows-10-10.0.15063-SP0
>>> exit()

(env) X:\Users\evgeny\Downloads\coursera-dl>coursera-dl --debug programming-in-python
root[main] coursera_dl version 0.9.0
root[main] Downloading class: programming-in-python (1 / 1)
root[download_class] Downloading new style (on demand) class programming-in-python
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepape_auth_headers] Forging cookie header: csrftoken=9p8fdRm2XQykoAyZdiHL; csrf2_token_NdQZeoyi=Ka2AMt1cuOGNpjhcaEduKFvs.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 401 None
root[main] Could not authenticate: Cannot login on coursera.org: 401 Client Error: Unauthorized for url: https://www.coursera.org/api/login/v3
```

**Comment by rbrito** [comment]
@evgeny-sobol, Does your password contain non-ascii characters? I think that that's the most likely cause of the problem that you are seeing.

**Comment by evgeny-sobol** [comment]
@rbrito, Indeed, it helped. Thank you!

**Comment by rbrito** [comment]
@evgeny-sobol, thank you very much.

Can you send a pull request with a few notes to our README for users that face the same problem?

We already have a small note at the end of https://github.com/coursera-dl/coursera-dl#resuming-downloads, but it would be better to have the note moved to the troubleshooting section, together with a solution that works.

**Comment by MR-T77** [comment]
Hi @rbrito, do you have any idea why I can't download? (no non-ascii characters in pass)
Thx in advance

**Comment by rbrito** [comment]
@MR-T77, you didn't tell me if your password or username/email contain non-ascii characters. Does it?

**Comment by ahah43** [comment]
Hello @rbrito. I have the same problem..... my password has nothing other than numbers and letters

**Comment by ahah43** [comment]
it has been solved 👍  :-)
use double quotes for the user email and the password

**Comment by MR-T77** [comment]
Well, first sorry for the delay but I've been away from computer...
I must be doing something really wrong here...
First, I already changed user as I had non-ascii characters.
Now, I continue to be unable to run anything:
```
(coursera) ???:www-coursera-downloader mactobe$ coursera-dl -u "???" -p "???" machine-learning --debug
root[main] coursera_dl version 0.9.0
root[main] Downloading class: machine-learning (1 / 1)
root[download_class] Downloading new style (on demand) class machine-learning
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepape_auth_headers] Forging cookie header: csrftoken=8fCwN9hc8NfI2EOlyQZs; csrf2_token_WUZpmRPR=1MyaOowUAHzj0K2YvLz1UXl0.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 401 None
root[main] Could not authenticate: Cannot login on coursera.org: 401 Client Error: Unauthorized for url: https://www.coursera.org/api/login/v3
```

Btw, is there any chance to choose the courses to download (or we must submit the name of the course in the cmd line)?
Thx in advance

**Comment by balta2ar** [comment]
> Btw, is there any chance to choose the courses to download (or we must submit the name of the course in the cmd line)?

There is no interactive menu or GUI that can help your choose courses and download them, but there is an option `--list-courses` that will list courses available to you. Then you still need to copy those course names into the command line.
