### ISSUE TITLE
Investigate why TravisCI fails only with Python 3.3

### ISSUE THREAD

**Issue by rbrito** [coursera-dl/coursera-dl#632]
It seems that TravisCI is failing our tests with Python 3.3 for some reason. All other versions seem to work fine and the problem with Python 3.3 is only during installation of dependencies.

Of course, failing the installation abort the real tests, but I think that we would have the test suite working fine if this problem went away.

https://travis-ci.org/coursera-dl/coursera-dl

If anybody has any idea of how to fix this, it would be nice.

**Comment by PrabhanshuAttri** [comment]
The `cryptography` package is not compatible with Python 3.3 which breaks the requirement installation. On [Travis CI](https://travis-ci.org/coursera-dl/coursera-dl/jobs/304690474), while installing `cryptography-2.1.3.tar.gz` it says `error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'`.

On [PyPi](https://pypi.python.org/pypi/cryptography), it says that `cryptography` supports Python 2.6-2.7, Python 3.4+, and PyPy 5.3+.

We can remove python 3.3 support from Travis CI.

**Comment by rbrito** [comment]
Excellent. Thanks. I will remove it, then, from the Travis configuration.

Super thanks.


-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

Em 25 de nov de 2017 14:59, "Prabhanshu Attri" <notifications@github.com>
escreveu:
