### ISSUE TITLE
Unsupported typename "phasedPeer" in lecture "XXX"

### ISSUE THREAD

**Issue by ansmirnov** [coursera-dl/coursera-dl#650]
### Subject of the issue
I had a problem with downloading the course [mathematics-and-python](https://www.coursera.org/learn/mathematics-and-python/). 

All course in specification have a `Peer-graded Assignment` task. Example task is https://www.coursera.org/learn/mathematics-and-python/peer/2yTvX/ustanovka-python .

Such tasks are not downloaded with error "Unsupported typename "phasedPeer" in lecture "XXX""

It is possible to fix it?

### Your environment
* Operating System (name/version): Debian buster
* Python version: Python 3.6.4 :: Anaconda, Inc.
* coursera-dl version: 0.10.0 (from git)

### Steps to reproduce

1. Subscribe course https://www.coursera.org/learn/mathematics-and-python/ as free listener

2. Try to download it with `coursera-dl --only-syllabus -u**** -p**** mathematics-and-python` command

* Is the problem happening with the latest version of the script? 

**yes**

* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. 

**yes**

* What is the course that you are trying to access? 

**mathematics-and-python**

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).

```
coursera-dl --only-syllabus -u**** -p**** mathematics-and-python 
```

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

```
...
root[_parse_on_demand_syllabus] Processing lecture         ustanovka-python (phasedPeer)
root[_parse_on_demand_syllabus] Unsupported typename "phasedPeer" in lecture "ustanovka-python"
...
```

### Expected behaviour

Tasks with typename "phasedPeer" downloads correctly.

### Actual behaviour

Tasks with typename "phasedPeer" not downloads.

**Comment by rbrito** [comment]
Hi.

On Thu, Mar 22, 2018 at 7:26 AM, Andrey S <notifications@github.com> wrote:
> All course in specification have a Peer-graded Assignment task. Example task is https://www.coursera.org/learn/mathematics-and-python/peer/2yTvX/ustanovka-python .
>
> Such tasks are not downloaded with error "Unsupported typename "phasedPeer" in lecture "XXX""
>
> It is possible to fix it?

I think that Yuri is the person most familiar with this part of the
code, but I would venture to say that download of some parts of the
courses depend on 2 items:

1 - Coursera allowing you to download/submit things (this depends on
you being formally enrolled as a paying student)
2 - Some resources may not be "downloadable"... What exactly is a
"phasedPeer" resource? Is that peer-reviewed homework to be submitted?


Regards,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by ansmirnov** [comment]
Hello!

This is а programming task that is reviewed by other course participants.

I made a screenshot with the subject. Sorry for Russian.

![coursera](https://user-images.githubusercontent.com/5292994/37818762-608cf2ee-2e8c-11e8-8563-63d59d69841c.png)

It consists of two parts. The first part is an HTML page (maybe with links to useful attachments). This page is available for free, without paid subscription. But I need to login to see it. I want to download this page and make the exersise offline. This page also includes HTML-forms for attach solutions.

The second part is result of reviewing my solution. I don't need to download it.

**Comment by balta2ar** [comment]
@ansmirnov Take a look at my first attempt at the "phasedPeer" support in this pull request: #651:

```bash
$ git fetch origin pull/651/head:phasedPeer
$ git checkout phasedPeer
```

Please give it a try and tell us how it works for you. If you know any other courses with this feature, please report them too, we may test them as well.

**Comment by ansmirnov** [comment]
@balta2ar It works great! Thanks for fixing!

Such tasks are used in each specialization course: https://www.coursera.org/specializations/machine-learning-data-analysis

I will check them all.

**Comment by rbrito** [comment]
Super duper thanks!

Life got in the way and I couldn't read your patch yet...


Thanks once again,

Rogério Brito

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

Em dom, 8 de abr de 2018 14:53, Yuri Bochkarev <notifications@github.com>
escreveu:

**Comment by RonyR21** [comment]
![Screenshot 2020-10-13 094345](https://user-images.githubusercontent.com/64828647/95825447-89bb9100-0d39-11eb-9e93-f4664035b4d1.png)
hi there, 
can anyone help me with this, please?
