### ISSUE TITLE
How do I download course json file

### ISSUE THREAD

**Issue by ga243** [coursera-dl/coursera-dl#653]
Earlier when I downloaded courses, it also used to download correspoding json file containing description of the course outside the download folder. For example, I have machine-learning-projects-syllabus-parsed.json downloaded with machine-learning-projects course folder (outside that folder).

But today it was not the case. It only downloaded course folder but not json.
Did I miss some parameter? Can I download json explicitly? 

Also this seems to be syllabus json. Earlier I used to get description json containing instructor name, course short / full name, course description etc. Can I download such and any other json too?

**Comment by balta2ar** [comment]
You can use `--cache-syllabus` option to do exactly that. `--debug` option would make the script save even more internal JSON files (and print more information on the screen), just for you information if you need that.

**Comment by ga243** [comment]
I just ran 

    coursera-dl -u myemail@gmail.com -p mypassword --cache-syllabus --debug -sl en -pl --path C:\Users\user\Downloads\coursera course1 course2 course3

It printed bunch of

    root [_handle_resource] xyz already download

But it did not download anything, not even download jsons which it did not, download when I ran command first time without `--cache-syllabus` and `--debug`. When I ran command first time (without `--cache-syllabus` and `--debug`), it downloaded only course content but not jsons. Now, I want to download jsons for those downloaded courses.

**Comment by balta2ar** [comment]
I guess you can rename the folders with your already downloaded courses and run downloading again. After syllabus is downloaded in the very beginning, you can terminate the script (`Ctrl-C`) to avoid downloading all the material and JSON should be there.

**Comment by ga243** [comment]
Earlier (when it did not download jsons) I ran:

    coursera-dl -u myemail@gmail.com -p mypassword -sl en -pl --path C:\Users\me\Downloads\coursera  algorithms-divide-conquer algorithms-graphs-data-structures algorithms-greedy algorithms-npcomplete

Now, I renamed the folders and ran:

    coursera-dl -u myemail@gmail.com -p mypassword --cache-syllabus --debug -sl en -pl --path C:\Users\me\Downloads\coursera  algorithms-divide-conquer algorithms-graphs-data-structures algorithms-greedy algorithms-npcomplete

It created new course folder and started downloading course content without first downloading jsons. I waited for a while, but json did not simply download. So I did Ctrl+C. 

I tried again only with single course. But same happenned.

I dont remember myself explicitly specifying `--cache-syllabus` option earlier. In fact I had the command copy pasted in my notepad which I always used to run changing only course name. Earlier it used to download json on itself, now its only downloading course content.

**Comment by balta2ar** [comment]
That's weird. Make sure you're using the latest version. Also, when do you abort the script? You should abort it after it has parsed the whole syllabus (it takes a while), e.g.:
```
python coursera/coursera-dl -n --path . --aria2 --cache-syllabus -- mathematics-and-python
coursera_dl version 0.10.0
Downloading class: mathematics-and-python (1 / 1)
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/mathematics-and-python?showLockedItems=true (42908 bytes)
Parsing syllabus of on-demand course. This may take some time, please be patient ...
Processing module  vviedieniie
Processing section     znakomstvo-s-kursom
Processing lecture         kak-priekrasny-mashinnoie-obuchieniie-i-analiz-dannykh (lecture)

<skipped>

Downloaded resource poll (3 bytes)
Processing resources
Processing resource  spisok-litieratury
Processing resource  konspiekty
Processing resource  intieriesnyie-riesursy

<-- SYLLABUS SHOULD BE SAVED INTO JSON AT THIS POINT -->

Downloading: ./mathematics-and-python/01_vviedieniie/01_znakomstvo-s-kursom/01_kak-priekrasny-mashinnoie-obuchieniie-i-analiz-dannykh.mp4
```

> I dont remember myself explicitly specifying --cache-syllabus option earlier

That must have been a long ago. Syllabus JSON is a rarely needed data for a regular user so there is an option to save it. It could have been that syllabus had been saved unconditionally, and then the option was introduced, but I don't remember such changes within the last year.

If you feed like hacking it yourself, syllabus is saved at the following point in the code:
https://github.com/coursera-dl/coursera-dl/blob/master/coursera/coursera_dl.py#L143
But I'm confirming that syllabus is saved with the latest github version in my environment.

**Comment by gitdeepr** [comment]
What I should do with JSON file should I delete it or just chill or it has something to do with courses because json file just so heavy like 18 MB.

**Comment by balta2ar** [comment]
@gitdeepr Why is the file size bothering you? :) There is no harm that it's so big, I think. The reason is that during the parsing some syllabus elements are kept in memory (such as HTML and embedded encoded images). I bet it's the encoded images that take the most space in your JSON. In summary, just chill :)

**Comment by rbrito** [comment]
Yes, there's little that we can do... The courses supply a lot of information there... It's like saying that a given course supplies too many videos... :-)

BTW, can this be closed?

**Comment by gitdeepr** [comment]
Got it.Thanks a lot.
