### ISSUE TITLE
Redundantly showing progress bar

### ISSUE THREAD

**Issue by oracleyue** [coursera-dl/coursera-dl#656]
### Subject of the issue
It shows the download progress redundantly, as show in Figure. I remember, if correctly, the previous versions didn't have such a issue, and only updates one progress bar.

![screen shot 2018-05-17 at 11 03 19](https://user-images.githubusercontent.com/5046605/40167821-4c1bd18e-59c2-11e8-93b9-74c782730314.png)

### Your environment
* Operating System (name/version): OS X 10.12.6
* Python version: 3.6
* coursera-dl version: 0.10.0

### Steps to reproduce

Download any file that is not too small to be done instantly, and you will see this issue. 

### Expected behaviour

Update the same progress bar, instead of redrawing so much for large files.

Please let me know if this is the way `coursera-dl` is supposed to work. Many thanks!

### Actual behaviour
See the attached figure above.

**Comment by rbrito** [comment]
What happens if you just increase the size of your window? Do you still have this problem?

**Comment by oracleyue** [comment]
@rbrito Thanks! It has been fixed since recent update. Cheers~
