### ISSUE TITLE
Update README.md to include feature to enter password after script intitaion 

### ISSUE THREAD

**Issue by dharmanshu24** [coursera-dl/coursera-dl#657]
### Subject of the issue
Not everyone is comfortable in typing their passwords in plain text in command line. Coursera-dl has a feature where you can enter username in command line and password in entered when script is run using getpass lib.

### Your environment
* Operating System (name/version): Linux Mint 18.3 XFCE
* Python version: 3.5.2
* coursera-dl version: 0.10.0

### Steps to reproduce
In your normal command just don't use -p option only use -u for username. 
Example:
`coursera-dl -u <user>  --resume sdn1-001`

under `Running the script` section also add that this option is also available.

**Comment by balta2ar** [comment]
@dharmanshu24 Could you send a pull request with that change?

**Comment by balta2ar** [comment]
Merged. Thanks!
