### ISSUE TITLE
How to skip downloading *.txt subtitle files

### ISSUE THREAD

**Issue by lahcene47** [coursera-dl/coursera-dl#659]
For every downloaded video, I will get 2 subtitle file: *.srt and a *.txt file

what is the command that would help me skip downloading the *.txt subtitle files?

**Comment by Moulick** [comment]
you can use `--ignore-formats txt` to ignore txt files

**Comment by balta2ar** [comment]
I hope the last message answered your question. If not, feel free to comment.
Closing.
