### ISSUE TITLE
Subtitles not downloading while using default downloader

### ISSUE THREAD

**Issue by Moulick** [coursera-dl/coursera-dl#663]
### Subject of the issue
Subtitles are not downloaded if I use the built-in default downloader.

### Your environment
* Ubuntu 17.10
* Python version: 3.6.5 (virtualenv)
* coursera-dl version: latest from github after #660  

### Steps to reproduce
Install the all the requirements. Just download a course like `google-machine-learning` or `launching-machine-learning` without `--aria2`

### Expected behaviour
Subtitles should be downloaded either way

### Actual behaviour
If I use `--aria2`, the subtitles are downloaded just fine, I get both the txt and srt file. but if I don't use it, it says

The following URLs (68) could not be downloaded:
--------------------------------------------------------------------------------
https://www.coursera.org/api/subtitleAssetProxy.v1/4lMQ87EFScWTEPOxBWnFbg?expiry=1528156800000&hmac=4ND89QWl1uavFKRaa---hjhRucvfZ8-NrBe9SMRPDVA&fileExtension=srlaunching-machine-learningt
https://www.coursera.org/api/subtitleAssetProxy.v1/4lMQ87EFScWTEPOxBWnFbg?expiry=1528156800000&hmac=YShzhKqIyTkJMQlBRb5_gqKQVeN8htsQvVIzK2zQvG8&fileExtension=txt
https://www.coursera.org/api/subtitleAssetProxy.v1/2ys9-vGARuerPfrxgIbn_Q?expiry=1528156800000&hmac=mXX0nKjYzDkxZFQ4XD3KB_8MMbORL6GJLkeSBZf3WKM&fileExtension=srt

If you want I'll paste the entire log with `--debug` here or on pastebin

**Comment by balta2ar** [comment]
Try version 0.11.2.

**Comment by balta2ar** [comment]
Should be fixed by now.
