### ISSUE TITLE
How to use coursera-dl.conf

### ISSUE THREAD

**Issue by MR-T77** [coursera-dl/coursera-dl#668]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Tried to use a coursera-dl.conf (in the same path as coursera-dl, with the exact writing as your example) but without success: 
Get the error 

> Did not find valid netrc file:
[Errno 2] No such file or directory: '/Users/mactobe/.netrc'

### Your environment
* Operating System (name/version): Maos High Sierra
* Python version:3.5
* coursera-dl version: 0.11.2

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

After the following command line:

> coursera-dl -n --list-courses --debug

I get the following: 

> root[authenticate_through_netrc] Trying netrc file None
> root[parse_args] Did not find valid netrc file:
> [Errno 2] No such file or directory: '/Users/mactobe/.netrc'
> 

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

**Comment by balta2ar** [comment]
`-n` option tries to read netrc. Could you try removing it?

**Comment by MR-T77** [comment]
Yes, but it still doesn't read anything from coursera-dl.conf file.
`coursera-dl --list-courses`
outputs 

> Please provide a username with the -u option, or a .netrc file with the -n option.

**Comment by balta2ar** [comment]
How exactly are you specifying username and password? I've tried two formats and both worked:
```
--username EMAIL
--password PASSWORD
```
```
username = EMAIL
password = PASSWORD
```

**Comment by MR-T77** [comment]
I was using the first option, but now I've tried both (without success in any).
It seems that he never reads coursera-dl.conf file, although it's in the same folder as coursera-dl...
If I use user and password on command line, it works
Any ideas on this?

**Comment by balta2ar** [comment]
Could you modify one python file? After this line: https://github.com/coursera-dl/coursera-dl/blob/master/coursera/commandline.py#L44

Add this (inside of `if`):
``` python
        print(conf_file_path)
        print(open(conf_file_path).read())
```
Maybe the file is not available to the script, no access to it or it's not in the folder where you think it is...

**Comment by MR-T77** [comment]
I edited that file, but output remains the same...so I believe you're right, but I don't know how to correct this
> Please provide a username with the -u option, or a .netrc file with the -n option

Here is some additional information, I'm working inside an conda environment ("coursera"), and the location of `commandline.py` is `/Users/mactobe/anaconda/envs/coursera/lib/python3.5/site-packages/coursera`, and the location of both `coursera-dl` and `coursera-dl.conf` is  `/Users/mactobe/anaconda/envs/coursera/bin`

**Comment by balta2ar** [comment]
What's the folder that you're running coursera-dl from? You can see it by executing `pwd` command.
coursera-dl.conf is supposed to be in the same directory where you run the script, not in the `/Users/mactobe/anaconda/envs/coursera/bin` (unless you're running the script from there, which is possible, but not really convenient to do).

**Comment by balta2ar** [comment]
Hey, the solution has been found! Please see the following issue: https://github.com/coursera-dl/coursera-dl/issues/686

**Comment by kalonya** [comment]
@MR-T77 Just place the coursera-dl.conf file into the folder that you run the terminal window. For ex., if it's /Users/your_name/Downloads/coursera, place the file into that folder.
