### ISSUE TITLE
Could not authenticate: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

### ISSUE THREAD

**Issue by jeet-parekh** [coursera-dl/coursera-dl#670]
### Subject of the issue
Running coursera-dl gives an error 400.

### Your environment
* Operating System (name/version): Windows 8.1
* Python version: 3.6.5
* coursera-dl version: 0.11.2

### Steps to reproduce
I ran the command `coursera-dl -u myusername -p mypassword machine-learning`.

* Is the problem happening with the latest version of the script?
    Yes.

* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
    Yes. I did a `pip install`.

* What is the course that you are trying to access?
    machine-learning

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
    `coursera-dl -u myusername -p mypassword machine-learning`

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

```
root[main] coursera_dl version 0.11.2
root[main] Downloading class: machine-learning (1 / 1)
root[download_class] Downloading new style (on demand) class machine-learning
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepape_auth_headers] Forging cookie header: csrftoken=rgrpC7s9fPPIdLTaWeGA; csrf2_token_doUFgKoj=G39Y5Rvw4XFBwlb8W8cN5SEM.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 400 None
root[main] Could not authenticate: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
```

### Expected behaviour
There would be no errors and the course would download.

### Actual behaviour
The output given above.

**Comment by jeet-parekh** [comment]
It worked when I used my email id as the user name.

**Comment by shyamsukhamit** [comment]
> ### Subject of the issue
> Running coursera-dl gives an error 400.
> 
> ### Your environment
> * Operating System (name/version): Windows 8.1
> * Python version: 3.6.5
> * coursera-dl version: 0.11.2
> 
> ### Steps to reproduce
> I ran the command `coursera-dl -u myusername -p mypassword machine-learning`.
> 
> * Is the problem happening with the latest version of the script?
>   Yes.
> * Do you have all the recommended versions of the modules? See them in the
>   file `requirements.txt`.
>   Yes. I did a `pip install`.
> * What is the course that you are trying to access?
>   machine-learning
> * What is the precise command line that you are using (don't forget to obfuscate
>   your username and password, but leave all other information untouched).
>   `coursera-dl -u myusername -p mypassword machine-learning`
> * What are the precise messages that you get? Please, use the `--debug`
>   option before posting the messages as a bug report. Please, copy and paste
>   them.  Don't reword/paraphrase the messages.
> 
> ```
> root[main] coursera_dl version 0.11.2
> root[main] Downloading class: machine-learning (1 / 1)
> root[download_class] Downloading new style (on demand) class machine-learning
> root[login] Initiating login.
> root[login] There were no .coursera.org cookies to be cleared.
> root[prepape_auth_headers] Forging cookie header: csrftoken=rgrpC7s9fPPIdLTaWeGA; csrf2_token_doUFgKoj=G39Y5Rvw4XFBwlb8W8cN5SEM.
> urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org
> urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 400 None
> root[main] Could not authenticate: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
> ```
> ### Expected behaviour
> There would be no errors and the course would download.
> 
> ### Actual behaviour
> The output given above.

Does not work for me. It  seems that API is disabled by coursera!

**Comment by bookreader** [comment]
Same problem. Tried on Windows-10 and latest ubuntu. Not on python 3 nor python 2. I think it simply does not work on any system! Hope someone could fix it.

**Comment by ifigueroap** [comment]
It does not work for me neither, I'm on macOS 10.14.3, Python 3.6.4 from Anaconda...

**Comment by FanDML** [comment]
I tried multiply times (probably around 10 times ?). Sometimes it worked. Just entering that line of commend continuously

**Comment by pogurek** [comment]
So is the API disabled by Coursera? Does not work for me either for the same reason.

**Comment by shujarafi** [comment]
same problem

**Comment by kevinmackie** [comment]
Same issue

**Comment by wheleph** [comment]
The solution works for me on Windows 10 and Python 3: https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-462163921

**Comment by rich4rdmacwan** [comment]
The solution of @wheleph worked for me too! Thanks a lot.
I did have to save the cookies with a Notepad instead of sublime which kept messing up the tabs and spaces.

**Comment by ykb0** [comment]
🙃Worked for me.
If you are getting authentication failure then try this
Step 1 : Go to this link 
https://learner.coursera.help/hc/en-us
Login here & keep it logged in
Step 2 : Come to terminal 
Type pip install coursera-dl
Press Enter
Now Type 
coursera-dl -u username -p password deep-learning-neural-network

Bravo!!! You have achieved something that you wanted so badly.

**Comment by mararkeri** [comment]
Create a file coursera-dl.conf in the same directory of the coursera-dl with the text below:
--username <email_here>
--password <passwd_here>
--subtitle-language en
--cauth

cauth value will be available only if you login to coursera and then check in cookies.
You may check the following video:
https://youtu.be/xpy0H4T9zHU
