### ISSUE TITLE
404 NO Found URL

### ISSUE THREAD

**Issue by Zhijun166** [coursera-dl/coursera-dl#676]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### 404
coursera_dl version 0.10.0
Downloading class: global-financial-crisis (1 / 1)
Logged in on coursera.org.
Error 404 Client Error: Not Found for url: https://www.coursera.org/api/opencourse.v1/course/global-financial-crisis?showLockedItems=true getting page https://www.coursera.org/api/opencourse.v1/course/global-financial-crisis?showLockedItems=true
The server replied: {"message":"","statusCode":404}
HTTPError 404 Client Error: Not Found for url: https://www.coursera.org/api/opencourse.v1/course/global-financial-crisis?showLockedItems=true.

### Your environment
* windows 10  (name/version):
* Python 3.5.3:
* coursera-dl 0.10:

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

**Comment by balta2ar** [comment]
They changed the API, please update to 0.11.4.
