### ISSUE TITLE
Can't play videos after downloading the course

### ISSUE THREAD

**Issue by fahmitech** [coursera-dl/coursera-dl#678]
Hi there, i have some trouble. I have downloaded the course, from the introduction until the end of the course. But when i want to open the video, i can't open it. It says "encoding error". I am using Linux to download, and play videos with VLC and kmplayer in windows operating system. 

Would you mind to fix this? 

Thanks.

**Comment by balta2ar** [comment]
Could you confirm that you're still having this issue with the version 0.11.4 that has been released today?

**Comment by pahiwiw** [comment]
check this out, quite easy to setup and download
https://github.com/bcbcbcbcbcl/working-coursera-download-with-selenium
