### ISSUE TITLE
EDX-DL question ：urllib.error.URLError: <urlopen error Remote end closed connection without respo nse>

### ISSUE THREAD

**Issue by Zhijun166** [coursera-dl/coursera-dl#679]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget also to check the current issues to
avoid duplicates.

### Subject of the issue
I downloaded the MIT course. I am not talking about MITxpro. I am talking about the MIT course. Can be retrieved but cannot be downloaded

### Your environment
* win7 (name/version):
* Python 3.6.5:
* youtube-dl 20180625:
* edx-dl 0.1.9:

### Steps to reproduce
edx-dl -u user@qq.com url . https://courses.edx.org/courses/course-v1:MITx+8.01.1x+3T2017/course/,
all courses

### Expected behaviour
  File "c:\users\123\appdata\local\programs\python\python36\lib\urllib\request.p
y", line 544, in _open
    '_open', req)
  File "c:\users\123\appdata\local\programs\python\python36\lib\urllib\request.p
y", line 504, in _call_chain
    result = func(*args)
  File "c:\users\123\appdata\local\programs\python\python36\lib\urllib\request.p
y", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\users\123\appdata\local\programs\python\python36\lib\urllib\request.p
y", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Remote end closed connection without respo
nse>

### Actual behaviour
edx-dl -u user@qq.com https://courses.edx.org/courses/course-v1:MITx+8.01.1x+3T2017/course/

**Comment by balta2ar** [comment]
This is coursera-dl repo, not edx-dl. Please do not spam with multiple reports, maintainers can see your issue in edx-dl perfectly fine.

**Comment by Zhijun166** [comment]
Sorry, I'm too eager for the problem. I couldn’t find a solution
