### ISSUE TITLE
How can I add subtitle already downloaded. (QuickTime Player in Mac)

### ISSUE THREAD

**Issue by ShiqinHuo** [coursera-dl/coursera-dl#695]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
How can I add subtitle already downloaded. (QuickTime Player in Mac)

### Your environment
* Operating System (name/version): Mac OS
* Python version: 3.5
* coursera-dl version: lastest

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
Yes
* What is the course that you are trying to access?
neural-networks-deep-learning
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Hopefully, the subtitles will be automatically shown with the vedio

### Actual behaviour
I don't know how to load the .srt files with the lectures

**Comment by balta2ar** [comment]
Sorry, I have no idea how to do that. Besides, this repository is not really a good place to ask such questions. Please search for the answer in your favorite search engine. Alternatively, you can use VLC media player, I'm using it myself and it's possible to add custom srt files there.
