### ISSUE TITLE
Cannot download course

### ISSUE THREAD

**Issue by raffam** [coursera-dl/coursera-dl#698]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Cannot download course

### Your environment
* Operating System (name/version): Kubuntu 18.10
* Python version: 3.6.7
* coursera-dl version:

> $ coursera-dl --version
> 0.11.4

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

Run:

`coursera-dl https://www.coursera.org/learn/quantitative-methods -u USERNAME`

* Is the problem happening with the latest version of the script? Yes

* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.

Yes

* What is the course that you are trying to access?

[This one](https://www.coursera.org/learn/quantitative-methods/home/welcome)

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).

`coursera-dl https://www.coursera.org/learn/quantitative-methods -u USERNAME`

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

```
$ coursera-dl https://www.coursera.org/learn/quantitative-methods -u ********** --debug
Coursera password for ***********: 
root[main] coursera_dl version 0.11.4
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepare_auth_headers] Forging cookie header: csrftoken=eFr8WF82fhMBVYuyEtki; csrf2_token_Qc3Q4AuA=0MX7jhsn00jMhn5qivlq59Lt.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
root[main] Downloading class: https://www.coursera.org/learn/quantitative-methods (1 / 1)
root[download_class] Downloading new style (on demand) class https://www.coursera.org/learn/quantitative-methods
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "GET /api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/quantitative-methods&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true HTTP/1.1" 400 None
root[get_reply] Error 400 Client Error: Bad Request for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/quantitative-methods&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true getting page https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/quantitative-methods&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
root[get_reply] The server replied: {"msg":"Routing error: Improperly formatted value for parameter 'slug'"}
root[main] HTTPError 400 Client Error: Bad Request for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/quantitative-methods&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
root[main] HTTPError 400 Client Error: Bad Request for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/quantitative-methods&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/coursera_dl-0.11.4-py3.6.egg/coursera/coursera_dl.py", line 245, in main
    session, args, class_name)
  File "/usr/local/lib/python3.6/dist-packages/coursera_dl-0.11.4-py3.6.egg/coursera/coursera_dl.py", line 214, in download_class
    return download_on_demand_class(session, args, class_name)
  File "/usr/local/lib/python3.6/dist-packages/coursera_dl-0.11.4-py3.6.egg/coursera/coursera_dl.py", line 142, in download_on_demand_class
    args.download_notebooks
  File "/usr/local/lib/python3.6/dist-packages/coursera_dl-0.11.4-py3.6.egg/coursera/extractors.py", line 52, in get_modules
    page = self._get_on_demand_syllabus(class_name)
  File "/usr/local/lib/python3.6/dist-packages/coursera_dl-0.11.4-py3.6.egg/coursera/extractors.py", line 68, in _get_on_demand_syllabus
    page = get_page(self._session, url)
  File "/usr/local/lib/python3.6/dist-packages/coursera_dl-0.11.4-py3.6.egg/coursera/network.py", line 92, in get_page
    quiet=quiet)
  File "/usr/local/lib/python3.6/dist-packages/coursera_dl-0.11.4-py3.6.egg/coursera/network.py", line 51, in get_reply
    reply.raise_for_status()
  File "/home/raffaele/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/quantitative-methods&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
```

### Expected behaviour
The course is downloaded

### Actual behaviour
An error 400 is returned

**Comment by evexoio** [comment]
@raffam have you enrolled the course on coursera before trying to download it?

**Comment by raffam** [comment]
I still have this problem. The credentials are right (otherwise it says "401 Client Error: Unauthorized for url").

What additional informations do I have to provide?

**Comment by huangyu1996** [comment]
I'm meeting an error when downloading:
`Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/onDemandSupplements.v1/Mz1ninIDEeeWCg71xNIlJg~N5lPL?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 getting page https://api.coursera.org/api/onDemandSupplements.v1/Mz1ninIDEeeWCg71xNIlJg~N5lPL?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
Could not download supplement N5lPL: 403 Client Error: Forbidden for url: https://api.coursera.org/api/onDemandSupplements.v1/Mz1ninIDEeeWCg71xNIlJg~N5lPL?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29

`

**Comment by raffam** [comment]
@evexoio what can I do to solve the problem plese?

**Comment by sntdevco** [comment]
IDK, but I disconnected and reconnected and it worked!

**Comment by IbraamYounan** [comment]
please, i've 403 errowr #723 
i tiried either using -u or -ca 
and failled to download

**Comment by CharlesDerek** [comment]
Keeps failing:
- coursera-dl.conf
 `--username xxx
--password xxx
--subtitle-language en
--cauth xxx`

$ coursera-dl NameOfCourse

`Parsing syllabus of on-demand course (id=Dhb0X03GEeqXxwqxk3C7MQ). This may take some time, please be patient ...
Processing module  threat-intelligence
Processing section     threat-intelligence-and-cybersecurity
Processing lecture         threat-intelligence-overview (lecture)
Processing lecture         threat-intelligence-strategy-and-external-sources (lecture)
Processing lecture         threat-intelligence-platforms (lecture)
Processing lecture         threat-intelligence-sources (supplement)
Traceback (most recent call last):
  File "/home/charles/.local/bin/coursera-dl", line 8, in <module>
    sys.exit(main())
  File "/home/charles/.local/lib/python3.9/site-packages/coursera/coursera_dl.py", line 247, in main
    error_occurred, completed = download_class(
  File "/home/charles/.local/lib/python3.9/site-packages/coursera/coursera_dl.py", line 214, in download_class
    return download_on_demand_class(session, args, class_name)
  File "/home/charles/.local/lib/python3.9/site-packages/coursera/coursera_dl.py", line 134, in download_on_demand_class
    error_occurred, modules = extractor.get_modules(
  File "/home/charles/.local/lib/python3.9/site-packages/coursera/extractors.py", line 53, in get_modules
    error_occurred, modules = self._parse_on_demand_syllabus(
  File "/home/charles/.local/lib/python3.9/site-packages/coursera/extractors.py", line 161, in _parse_on_demand_syllabus
    links = course.extract_links_from_supplement(
  File "/home/charles/.local/lib/python3.9/site-packages/coursera/api.py", line 1268, in extract_links_from_supplement
    supplement_content, self._extract_links_from_text(value))
  File "/home/charles/.local/lib/python3.9/site-packages/coursera/api.py", line 1518, in _extract_links_from_text
    supplement_links = self._extract_links_from_a_tags_in_text(text)
  File "/home/charles/.local/lib/python3.9/site-packages/coursera/api.py", line 1597, in _extract_links_from_a_tags_in_text
    extension = clean_filename(
  File "/home/charles/.local/lib/python3.9/site-packages/coursera/utils.py", line 118, in clean_filename
    s = h.unescape(s)
AttributeError: 'HTMLParser' object has no attribute 'unescape'
`
