### ISSUE TITLE
Max retries exceeded with url: /api/workspaceSubmissions.v1

### ISSUE THREAD

**Issue by AVoss84** [coursera-dl/coursera-dl#705]
Hi,

I am getting this error, when trying to submit my assignment "Face+Recognition+for+the+Happy+House+-+v3.ipynb":

Failed to execute submission request: HTTPSConnectionPool(host='hub.coursera-apps.org', port=443): Max retries exceeded with url: /api/workspaceSubmissions.v1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe686874d30>, 'Connection to hub.coursera-apps.org timed out. (connect timeout=10)'))

Windows 10; using Google Chrome

**Comment by balta2ar** [comment]
coursera-dl doesn't use the API endpoint you mentioned, that's something new to me. Could you show in details what you're doing starting from the beginning? e.g. how you run the script, what arguments you provide, etc (don't forget to blank passwords or emails, if necessary).

**Comment by AVoss84** [comment]
Hi,
sorry for my late response. Today I have tried once again to submit using another computer and this time I could submit the assignement as usual. Thank you in any case.
