### ISSUE TITLE
Download only subtitles

### ISSUE THREAD

**Issue by GabrielLin** [coursera-dl/coursera-dl#717]
Can I only download subtitles without downloading videos? Thanks.

**Comment by felker** [comment]
Yes, try `--ignore-formats mp4` (or whatever format the videos are encoded in for the course). Should still get the `.txt` and/or `.srt` subtitle files.

**Comment by GabrielLin** [comment]
Really thanks.

**Comment by rbrito** [comment]
Should we document this as a FAQ?

**Comment by felker** [comment]
Done.

**Comment by rbrito** [comment]
On January 30, 2020 8:28:54 PM GMT-03:00, Kyle Gerard Felker <notifications@github.com> wrote:
>Done.

Thanks a lot!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
