### ISSUE TITLE
Error in entering password 

### ISSUE THREAD

**Issue by dachosen1** [coursera-dl/coursera-dl#721]
I'm having trouble with the user name and password installation in windows. I've installed python in my environment variable and when i run the following command. 

I'm trying to download this course: https://www.coursera.org/learn/bayesian/home/welcome

coursera-dl [ -u usernmae@gmail.com]

I get an error: 
c:\users\ander\appdata\local\programs\python\python37-32\lib\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

The system prompts me for a password: however, i can't type anything. 

I have tried  coursera-dl [ -u usernmae@gmail.com] [-p password],
oursera-dl: error: unrecognized arguments: [-p password]

coursera-dl <-u usernmae@gmail.com> <-p password> 
< was unexpected at this time.

### Your environment
* Operating System (name/version): Windows 10
* Python version: 3.7.3
* coursera-dl version: the latest version, i downloaded it on 4/27/19

any ideas on how to fix this?

**Comment by felker** [comment]
Reinstalling should fix this, now.
