### ISSUE TITLE
unable to download: Error 403, Error: Forbidden for url

### ISSUE THREAD

**Issue by IbraamNasif** [coursera-dl/coursera-dl#723]
i got the same errowr whether i use -u or -ca obtion...
i'm unable to download any course now, however, before i could able to download this course.

coursera-dl -ca 'CauthCoppiedFromBrowser ' --resume -sl en --disable-url-skipping six-sigma-principles
coursera_dl version 0.11.4
Downloading class: six-sigma-principles (1 / 1)
Parsing syllabus of on-demand course (id=jPWJXYC7Eea-WAqa1tl72w). 
This may take some time, please be patient ...
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrol led getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
The server replied: {"errorCode":"Not Authorized","message":null,"details":null} HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled

**Comment by IbraamYounan** [comment]
@jethar
@markbaas
@sollicitudin
@alexfmpe
@coiby
@aakuptsov

**Comment by dhruvip** [comment]
@here I think the issue is coursera has now incorporated the google recapcha, and the login api now takes the google recapchaToken in its payload. I tried looking into the google recapcha but couldn't figure out the logic of recapchaToken .

**Comment by samkitjain** [comment]
I was having similar problem. Try solution mentioned by @Mitdac01 in #702. If you are already using that, update your cookies.txt and that should fix it.

**Comment by aspiringguru** [comment]
I just had an error on first attempt to download. second attempt is working. weird but not surprised, I would expect Coursera to be deliberately obstructing this package from working. Even tho the app allows downloading courses.

**Comment by zenny** [comment]
Got the same problem, even with the solution provided by @sc268 at https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-568228372 and @BadWindShield at https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-568918178.

The output error looks like the following>

```
/shared/projects/my-coursera/local/lib/python3.4/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
coursera_dl version 0.11.5
Downloading class: contemporary-art (1 / 1)
Parsing syllabus of on-demand course (id=eIuy3sp7Eem_qg46ES4SQA). This may take some time, please be patient ...
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
```

Tried many a times if it works arbitrarily as @aspiringguru mentioned at https://github.com/coursera-dl/coursera-dl/issues/723#issuecomment-524112388, but no go in my case!

Any input?

Cheers,
