### ISSUE TITLE
Error in gradient descent algorithm

### ISSUE THREAD

**Issue by manoj21192** [coursera-dl/coursera-dl#730]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Describe your issue here.

### Your environment
* Operating System (name/version):
* Python version:
* coursera-dl version:

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.
I am writing the below code and trying to apply gradient descent algo for linear regression for two variables .I am getting an error(Not able to get the answer) .Can anyone help me in identifying the error
data=pd.read_csv('F:\python exercises\Book1.csv')
X=data['tu']
Y=data['ta']
plt.scatter(X,Y)
c=0
m=0
alpha=0.001
iteration=50
n=722
for i in range(iteration):
    Y_pred=m*X +c
    D_m = (1/n) * sum(X * (Y - Y_pred))  # Derivative wrt m
    D_c = (1/n) * sum(Y - Y_pred)  # Derivative wrt c 
    c=c-alpha*D_c
    m=m-alpha*D_m
print(m,c)

**Comment by raffam** [comment]
I think you posted on the wrong project

**Comment by balta2ar** [comment]
@manoj21192 You were almost right, but you made a mistake in derivative formula (both of them): you wrote `1/n`, but it should be `-(2/n)`. Here is full example:
```python
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


def test():
    xs = np.linspace(1, 10, 30)
    ys = 2*xs + 3 + np.random.normal(0, 2, len(xs))
    plt.scatter(xs, ys); plt.show()
    m, c = grad(xs, ys)
    print(m, c)
    y = m*xs+c
    plt.scatter(xs, ys); plt.plot(xs, y, '-r'); plt.show()


def grad(X, Y):
    c=0
    m=0
    alpha=0.0001
    iteration=1000
    n = len(X)
    for i in range(iteration):
        Y_pred=m*X +c
        D_m = -(2/n) * sum(X * (Y - Y_pred))  # Derivative wrt m
        D_c = -(2/n) * sum(Y - Y_pred)  # Derivative wrt c
        c=c-alpha*D_c
        m=m-alpha*D_m
    return m, c
```
Save into `grad.gy` and run as follows: `python -c 'from grad import test; test()'`

![grad-descrent](https://user-images.githubusercontent.com/340676/70945035-95282800-2054-11ea-9d15-d3012b1e8b74.png)
