### ISSUE TITLE
How do i download thse kind of courses

### ISSUE THREAD

**Issue by aswinproz** [coursera-dl/coursera-dl#733]
so i have enrolled into a course and it has 5 course inside it like this one
https://www.coursera.org/specializations/discrete-mathematics
how do i download these.whenever i try to download  it says
file could not be found

**Comment by felker** [comment]
Try adding `coursera-dl --specialization discrete-mathematics`:

```
Selection of material to download:
  --specialization      treat given class names as specialization names and
                        try to download its courses, if available. Note that
                        there are name clashes, e.g. "machine-learning" is
                        both a course and a specialization (Default: False)
```
