### ISSUE TITLE
I can not download coursera courses although I followed the steps 

### ISSUE THREAD

**Issue by samehsaad14** [coursera-dl/coursera-dl#734]
I can not download coursera courses although I followed the steps 
I installed anaconda python 3 and followed each step but it is failed to login why ..

**Comment by feng-lei** [comment]
It did not work for me either. So I made [dl_coursera](https://github.com/feng-lei/dl_coursera) several months ago, and it works fine. Give it a try :-)

**Comment by fangzheng-mediagamma** [comment]
I have the same problem.

**Comment by samehsaad14** [comment]
Please I did tried to use your dl_coursera but it did not work for me 

please explain to me step by step in detail how to use it to make it work
it is very important please respond as soon as possible

**Comment by samehsaad14** [comment]
it says that the cookies.txt is expired

**Comment by feng-lei** [comment]
> it says that the cookies.txt is expired

Can you post the content of your cookies.txt ?

**Comment by rbrito** [comment]
On December 24, 2019 11:52:59 PM GMT-03:00, feng-lei-zZZ <notifications@github.com> wrote:
>> it says that the cookies.txt is expired
>
>Can you post the content of your cookies.txt ?

Please, DON'T post the contents of your cookies, as it can be used to impersonate you.

I will read this issue report as I wake up (I'm in bed right now).
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by feng-lei** [comment]
> it says that the cookies.txt is expired

Yes. Don't post it here. Just to make sure it is the cookies.txt of **Coursera** after you **sign in**.

**Comment by samehsaad14** [comment]
the problem is solved thank you @feng-lei
