### ISSUE TITLE
Videos are downloading in 480p how do we Download them in HD?

### ISSUE THREAD

**Issue by HassanAbbas7357** [coursera-dl/coursera-dl#738]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Describe your issue here.

### Your environment
* Operating System (name/version):
* Python version:
* coursera-dl version:

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

**Comment by felker** [comment]
Use `--video-resolution 720p` if the course is On-Demand

**Comment by rbrito** [comment]
@felker, can you send a pull request to the README file with this sort of information? We seem to be starting to get more requests like this and, as people use devices with higher resolution, we may be seeing even more if we don't document this.

Even more, it would be useful to point users to run the `--help` option of the program, so that they can also see what we have available.

Thanks.

**Comment by felker** [comment]
Done. If you are willing to give me permissions to close some of these issues, I can help clear the backlog of duplicate/off-topic issues.

**Comment by rbrito** [comment]
@felker, welcome to the team! Any hand that you could lend me/us will help a lot!

**Comment by felker** [comment]
great, thanks @rbrito! It seems like I still dont have permissions to close Issues/PRs, however...

**Comment by rbrito** [comment]
I will take a look and try to see if I can figure what may be wrong... Please, bear with me for a while...

I hope to have done things correctly by now, but if you still can't do anything, please let me know.

**Comment by rbrito** [comment]
After adding a label to this issue, I'm letting this issue open so that you can test if your permissions are correct, @felker.

**Comment by felker** [comment]
works now, thanks @rbrito
