### ISSUE TITLE
ConnectionError(e, request=request)

### ISSUE THREAD

**Issue by LazzaroneS** [coursera-dl/coursera-dl#755]
I'm sorry english isn't my parent language,I'm learning it hardly.

### Environment
- Operating System: Windows 10 Pro
- Python version: 3.7
- coursera-dl version: 0.11.5

### The problem

1. At first I login coursera.org use my account , And then use the chrome extension named [EditThisCookie ](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg) get CAUTH

2. I type 
`coursera-dl -u xxx@xxx.com -p xxx the-science-of-well-being -ca <CookieCAUTH>`
(I got CookieCAUTH in the first step)

3. raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='d3c33hcgiwev3.cloudfront.net', port=443): Max retries exceeded with url: /imageAssetProxy.v1/V0o7cyYDEei3OArly3DAPA_3b9557d41c3d92abd48c7d51199f6919_Santos_Headshot_Cropped_Small.jpg?expiry=1585612800000&hmac=PvDI8WCxX32QvV4Gch7X_2yfc0USwDdf4HEs0puZb7Y (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000024E03B117C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Thanks for your help.

**Comment by zhangxiann** [comment]
I have this problem too
