### ISSUE TITLE
i am unable to find the coursera authentication helper extension? how can i resolve this or any alternative

### ISSUE THREAD

**Issue by mak472** [coursera-dl/coursera-dl#768]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Describe your issue here.

### Your environment
* Operating System (name/version):
* Python version:
* coursera-dl version:

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

**Comment by GREATNESS1504** [comment]
i am also experincing the same the problem. i tried using the technique i found from a youtube video yet it still failed.
This is the youtube link https://www.youtube.com/watch?v=AjdhvKQV5xk

**Comment by GREATNESS1504** [comment]
hey, have you been able to solve the issue

**Comment by mak472** [comment]
I couldn't resolve it.@GREATNESS1504

**Comment by KarWar16** [comment]
Hi Guys, I was able to resolve this issue by doing this:
1) Went to the browser settings and looked for cookies and site data.
2) Searched for coursera.org 
3) Found a section called "CAUTH" and found a large alpha-numeric code in the content.
4) Used that as the Authentication key. 
5) Pasted that in the coursera-dl conf file that looks like this: 

--username < your username of coursera>
--password < your password of coursera>
--subtitle-language en
--download-quizzes
--cauth <copied authentication code>

6) Pasted the above found code into the "cauth" section of the conf file.
It works!

**Comment by vdj05** [comment]
Traceback (most recent call last):
  File "c:\users\dave\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,


I have this everytime i start to download a course, can anybody help me what error is this?

**Comment by vdj05** [comment]
Traceback (most recent call last):
  File "c:\users\dave\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,


I have this everytime i start to download a course, can anybody help me what error is this?

**Comment by sebastien15** [comment]
> Hi Guys, I was able to resolve this issue by doing this:
> 
> 1. Went to the browser settings and looked for cookies and site data.
 1.1 scroll down to see all cookies and site data and continue the next step
> 2. Searched for coursera.org
> 3. Found a section called "CAUTH" and found a large alpha-numeric code in the content.
> 4. Used that as the Authentication key.
> 5. Pasted that in the coursera-dl conf file that looks like this:
> 
> --username < your username of coursera>
> --password < your password of coursera>
> --subtitle-language en
> --download-quizzes
> --cauth
> 
> 1. Pasted the above found code into the "cauth" section of the conf file.
>    It works!

**Comment by BlckBob** [comment]
Hi.
Everything works perfectly but with python 3.8.8(and probably 3.8.5 etc...). With 3.9.2 don't work-It is caused by removing unescape from HTMLParser in python3.9, which seems to break setuptools. Maybe work with 3.9.x with some hack (link: https://github.com/coursera-dl/edx-dl/commit/5490a99a98b56f544661c131229ef640ace2b064#diff-82f22bd01f2b15c2b337ee2c879e859442cae20271d145c831cf7483fc05a5d9

**Comment by mak472** [comment]
the issue has been resolved
