### ISSUE TITLE
Coursera-dl Issue Error 403 Client Error

### ISSUE THREAD

**Issue by nasima908** [coursera-dl/coursera-dl#769]
I have literally been trying to download my videos from coursera for the past three days and nothing works. Im on a windows 10 and this is my first time using python, I have installed gitpython and tried to use that. I tried to use -cauth it also didnt work.. but this is the error it gave me

**This is what I ran:** 

coursera-dl -u xxxxx@xx -p xxxxxx -ca xxxxxxxxxxx system-administration-it-infrastructure-services

**This is what I got**

Downloading class: system-administration-it-infrastructure-services (1 / 1)
Parsing syllabus of on-demand course (id=hBmmv1drEeerkQ5vdwUqtA). This may take some time, please be patient ...
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled

Pleaseeeeeeeeeee help me like I have tried almost everything, even the thread #702 which didnt help at all. Everything I try is another dead end, I even ran a virtualenv in cmd and that still didnt work. Yes I have tried putting the password after

**Comment by Endone** [comment]
same error with u, did u pay for this course or just for trial?

**Comment by annan92419** [comment]
https://www.youtube.com/watch?v=xRk7TPobFvg&t=104s

this helped me, try it

**Comment by princepelumiogunmokun** [comment]
Hi everyone. who is can help out please, I'm currently having this issue too...

**Comment by princepelumiogunmokun** [comment]
I just solved the problem. If you are still experiencing it, go to your chrome settings and then go to privacy and securities. Click on cookies. then click on Coursera. The only thing you need here is to copy your "cauth" and input it into the coursera-dl file on your pc. then save it. Try using the command prompt again and you see it working powerfully. 

Enjoy

**Comment by yaljaber2014-jpg** [comment]
> https://www.youtube.com/watch?v=xRk7TPobFvg&t=104s
> 
> this helped me, try it

give me this video had deleted from youtube
