### ISSUE TITLE
Problem while running coursera-dl command

### ISSUE THREAD

**Issue by shresthajenis46** [coursera-dl/coursera-dl#771]
My environment:

*Operating System :( Windows/10 )

*Python version: 3.8.5

*coursera-dl version: unknown

Steps to reproduce:

*Is the problem happening with the latest version of the script? =YES

*Do you have all the recommended versions of the modules? See them in the file requirements.txt. =YES

What is the course that you are trying to access? = python-data

What is the precise command line that you are using (don't forget to obfuscate your username and password, but leave all other information untouched).

`pip install coursera-dl`

What are the precise messages that you get?

--debug:

```
ERROR: Could not find a version that satisfies the requirement coursera-dl (from versions: none)
ERROR: No matching distribution found for coursera-dl
```

Expected behaviour =coursera-dl should start performing.

Actual behaviour:

Please help, when I try to run the coursera-dl commands same message occurs in all of them:

```
C:\Download>pip install coursera-dl

     python -m pip install coursera-dl

     pip install --upgrade coursera-dl
    
        WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x039F5538>, 'Connection to 192.168.49.1 timed out. (connect timeout=15)')': /simple/coursera-dl/
        WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x039F56E8>, 'Connection to 192.168.49.1 timed out. (connect timeout=15)')': /simple/coursera-dl/
        WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x039F5658>, 'Connection to 192.168.49.1 timed out. (connect timeout=15)')': /simple/coursera-dl/
        WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x039F5640>, 'Connection to 192.168.49.1 timed out. (connect timeout=15)')': /simple/coursera-dl/
        WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x039F5490>, 'Connection to 192.168.49.1 timed out. (connect timeout=15)')': /simple/coursera-dl/
        
        ERROR: Could not find a version that satisfies the requirement coursera-dl (from versions: none)
        
        ERROR: No matching distribution found for coursera-dl
```

**Comment by SerJoG** [comment]
Have you tried to upgrade pip? The command should be:
`python -m pip install -upgrade pip`, then retry.
Tell me if it resolve the issue.

**Comment by shresthajenis46** [comment]
> python -m pip install -upgrade pip

Hey @SerJoG Thankyou for your help but No It didn't help. It says that 


Requirement already up-to-date: pip in c:\users\myname\appdata\local\programs\python\python38-32\lib\site-packages (20.1.1)



![p3](https://user-images.githubusercontent.com/59916981/91325532-08d52400-e7e3-11ea-9b99-3de161ddfd56.PNG)

**Comment by shresthajenis46** [comment]
There was my proxy error. It's fixed now. So I'm closing this issue. Happy Coding !!!!!
