### ISSUE TITLE
[FULLY SOLVED] HTTPError 403: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled

### ISSUE THREAD

**Issue by SerJoG** [coursera-dl/coursera-dl#772]
I'm on Windows 10, but I think this work on every systems because it's not a os issue. The original issue is:
```
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
```

The issue can be resolved by modifing `define.py`
The problem is in the link to the api, change every occurrences of:
`includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled`
to this:
`includes=courseId,courses.v1&q=me&showHidden=true`

i.e line 63. I changed only this but if you want to see courses list just search `&filter=current,preEnrolled` and delete it.

**Comment by wangzhankun** [comment]
I have changed the url as you described, but I also have the problem:
```bash
coursera_dl version 0.11.5
Downloading class: os-virtsecurity (1 / 1)
Parsing syllabus of on-demand course (id=tMxMyvC2EeWZ5A7KPp5tzw). This may take some time, please be patient ...
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true
```

**Comment by NightMachinery** [comment]
```
> command coursera-dl -u x -p 'x' -ca x -n -pl --aria2 --video-resolution 720p --specialization --download-quizzes --download-notebooks -sl en,fa --resume --aria2 aria2c --playlist progfun2

coursera_dl version 0.11.5
Downloading class: progfun2 (1 / 1)
Parsing syllabus of on-demand course (id=PeZYFz-zEeWB_AoW1KYI4Q). This may take some time, please be patient ...
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
```

**Comment by zenny** [comment]
> I'm on Windows 10, but I think this work on every systems because it's not a os issue. The original issue is:
> 
> ```
> Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
> The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
> HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
> ```
> 
> The issue can be resolved by modifing `define.py`
> The problem is in the link to the api, change every occurrences of:
> `includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled`
> to this:
> `includes=courseId,courses.v1&q=me&showHidden=true`
> 
> i.e line 63. I changed only this but if you want to see courses list just search `&filter=current,preEnrolled` and delete it.

Does not work! Also see #800
