### ISSUE TITLE
On-demand course: HTTPError 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by SNAnalyst** [coursera-dl/coursera-dl#774]
Windows 10, x64

I am getting the following error when trying to download the course analytic-combinatorics:

>>>
coursera_dl version 0.11.5
Traceback (most recent call last):
  File "c:\python\python38-32\lib\site-packages\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "c:\python\python38-32\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python38-32\Scripts\coursera-dl.exe\__main__.py", line 9, in <module>
  File "c:\python\python38-32\lib\site-packages\coursera\coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "c:\python\python38-32\lib\site-packages\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
<<<

When I add the cookie to the function call, the error changes to:

>>>
coursera_dl version 0.11.5
Downloading class: analytic-combinatorics (1 / 1)
Parsing syllabus of on-demand course (id=S9QaleohEeWa-RJ17vNpzw). This may take some time, please be patient ...
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/
api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
<<<

Could this be connected to the course being an on-demand course? I have tried several other (on-demand) courses, and keep getting the same error. The courses can be opened in the web browser, I am enrolled in them.

Anyway, any thoughts on how to make the downloads work?

**Comment by SNAnalyst** [comment]
forget it, after creating a conf file it all works.

**Comment by wangzhankun** [comment]
> forget it, after creating a conf file it all works.

Hi, could you give more detail about the conf file? I have the same problem and I don't know how to solve it.

**Comment by zenny** [comment]
> forget it, after creating a conf file it all works.

@SNAnalyst I have been using coursera-dl.conf file all the time. Yet this is not an issue. See #800

**Comment by zenny** [comment]
> > forget it, after creating a conf file it all works.
> 
> Hi, could you give more detail about the conf file? I have the same problem and I don't know how to solve it.

@wangzhankun I have included the `coursera-dl.conf` file which you can use, but recently the 403 error is popping up as I discussed in #800. Hope this throws some light on conf file.
