### ISSUE TITLE
Cookies file not found: a

### ISSUE THREAD

**Issue by cahyoardhi** [coursera-dl/coursera-dl#776]
### Subject of the issue
Hello, i have problem when using this tools, here the screenshot that i can provide 
![image](https://user-images.githubusercontent.com/47904651/94371015-e27a0f80-0125-11eb-8a0d-5f4d24d8a9a8.png)

### Your environment
* Operating System (name/version): Mac OS Catalina 10.15.7
* Python version: 3.7.9

is there anyone ever had this issue?

when i tries to download with --cauth parameter inside coursera-dl.conf, this error happen 
![image](https://user-images.githubusercontent.com/47904651/94371080-53b9c280-0126-11eb-90d4-69d72caaac3a.png)
![image](https://user-images.githubusercontent.com/47904651/94371091-6af8b000-0126-11eb-9e08-ce478f4c5254.png)

because of this issue, i tried to download by using -ca parameter on terminal , but didn't work (first question)

**Comment by yolia** [comment]
I have exactly the same issue, does anyone know how to fix it?
