### ISSUE TITLE
When I try to download it brings this, i don't know what to do 

### ISSUE THREAD

**Issue by nshimiyeemmy** [coursera-dl/coursera-dl#793]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.
Ys i have reviewed

### Subject of the issue
I just cloned the coursera-dl 
then created the coursera-dl.conf file inside the coursera-dl folder 
but when i run  coursera-dl it shows the error below:
coursera-dl: error: ambiguous option: --=subtitle-language en could match --help, --username, --password, --jobs, --download-delay, --preview, --path, --subtitle-language, --specialization, --only-syllabus, --download-quizzes, --download-notebooks, --about, --formats, --ignore-formats, --section_filter, --lecture_filter, --resource_filter, --video-resolution, --disable-url-skipping, --wget, --curl, --aria2, --axel, --downloader-arguments, --list-courses, --resume, --overwrite, --verbose-dirs, --quiet, --reverse, --combined-section-lectures-nums, --unrestricted-filenames, --cauth, --cookies_file, --netrc, --keyring, --clear-cache, --hook, --playlist, --mathjax-cdn, --skip-download, --debug, --cache-syllabus, --version, --process_local_page

### Your environment
* Operating System (name/version): Windows
* Python version:3.9
* coursera-dl version:

### Actual behaviour
C:\Users\nshim\OneDrive\Documents\my-coursera\coursera-dl>coursera-dl --wget -u my-email -p my-password python
usage: coursera-dl [-h] [-u USERNAME] [-p PASSWORD] [--jobs JOBS] [--download-delay DOWNLOAD_DELAY] [-b] [--path PATH] [-sl SUBTITLE_LANGUAGE] [--specialization]
                   [--only-syllabus] [--download-quizzes] [--download-notebooks] [--about] [-f FILE_FORMATS] [--ignore-formats IGNORE_FORMATS] [-sf SECTION_FILTER]
                   [-lf LECTURE_FILTER] [-rf RESOURCE_FILTER] [--video-resolution VIDEO_RESOLUTION] [--disable-url-skipping] [--wget [WGET]] [--curl [CURL]]
                   [--aria2 [ARIA2]] [--axel [AXEL]] [--downloader-arguments DOWNLOADER_ARGUMENTS] [--list-courses] [--resume] [-o] [--verbose-dirs] [--quiet] [-r]
                   [--combined-section-lectures-nums] [--unrestricted-filenames] [-ca COOKIES_CAUTH] [-c COOKIES_FILE] [-n [NETRC]] [-k] [--clear-cache]
                   [--hook HOOKS] [-pl] [--mathjax-cdn MATHJAX_CDN_URL] [--skip-download] [--debug] [--cache-syllabus] [--version] [-l LOCAL_PAGE]
                   [class_names ...]
coursera-dl: error: ambiguous option: --=subtitle-language en could match --help, --username, --password, --jobs, --download-delay, --preview, --path, --subtitle-language, --specialization, --only-syllabus, --download-quizzes, --download-notebooks, --about, --formats, --ignore-formats, --section_filter, --lecture_filter, --resource_filter, --video-resolution, --disable-url-skipping, --wget, --curl, --aria2, --axel, --downloader-arguments, --list-courses, --resume, --overwrite, --verbose-dirs, --quiet, --reverse, --combined-section-lectures-nums, --unrestricted-filenames, --cauth, --cookies_file, --netrc, --keyring, --clear-cache, --hook, --playlist, --mathjax-cdn, --skip-download, --debug, --cache-syllabus, --version, --process_local_page

**Comment by lehaas** [comment]
I encounter the same issue. Do you remember how you solved it?
