### ISSUE TITLE
HTTPError 403 Client Error: Forbidden for url:

### ISSUE THREAD

**Issue by 1l6r5d** [coursera-dl/coursera-dl#802]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
HTTPError 403 Client Error: Forbidden for url:

### Your environment
* Operating System (name/version): Windows 10 64bit
* Python version: 3.9
* coursera-dl version: 0.11.5

### Steps to reproduce

1.coursera-dl.conf have been created as below and save under C:\coursera-dl\coursera-dl.conf 
--username [id]
--password [password]
--subtitle-language en
--video-resolution 720p
--download-quizzes True
--download-notebooks True
--cauth [copy from Chrome]

2.issue this command 
coursera-dl introduction-to-data-analytics

* Is the problem happening with the latest version of the script? yes
* Do you have all the recommended versions of the modules? 
  C:\coursera-dl\requirements.txt
beautifulsoup4>=4.1.3
requests>=2.10.0
six>=1.5.0
urllib3>=1.23
pyasn1>=0.1.7
keyring>=4.0
configargparse>=0.12.0
attrs==18.1.0

* What is the course that you are trying to access? https://www.coursera.org/learn/introduction-to-data-analytics/home/welcome
* What is the precise command line that you are using? coursera-dl introduction-to-data-analytics
* What are the precise messages that you get? 
  C:\coursera-dl>coursera-dl --list-courses --debug
root[main] coursera_dl version 0.11.5
root[main] Listing enrolled courses
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepare_auth_headers] Forging cookie header: csrftoken=; csrf2_token=.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org:443
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 400 84
Traceback (most recent call last):
  File "C:\coursera-dl\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\coursera-dl\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "C:\coursera-dl\coursera\coursera_dl.py", line 232, in main
    list_courses(args)
  File "C:\coursera-dl\coursera\coursera_dl.py", line 108, in list_courses
    login(session, args.username, args.password)
  File "C:\coursera-dl\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

C:\coursera-dl>

### Expected behaviour

no expected downloading in progress

### Actual behaviour

C:\coursera-dl>coursera-dl introduction-to-data-analytics
coursera_dl version 0.11.5
Downloading class: introduction-to-data-analytics (1 / 1)
Parsing syllabus of on-demand course (id=ZWYBq9zVEeqMbw6VbjEnNw). This may take some time, please be patient ...
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled

C:\coursera-dl>

**Comment by srg9000** [comment]
How did you fix it?
