### ISSUE TITLE
Autosave failed and permission denied in all notebooks

### ISSUE THREAD

**Issue by mvanzulli** [coursera-dl/coursera-dl#848]
After deleting my /tmp/ file I can't submit any coursera notebook.  

![image](https://user-images.githubusercontent.com/50339940/229314210-f86deba6-13cc-421c-be0d-fc781190817d.png)

### Subject of the issue
Describe your issue here.

### Your environment
* Operating System (name/version): Manjaro
* Python version:python3
* coursera-dl version: 0.11

**Comment by 95nadia** [comment]
I have the same problem!!

**Comment by mvanzulli** [comment]
Here is the solution: https://www.coursera.support/s/question/0D58W0000A3Ze2rSQC/cannot-save-or-submit-the-programming-assignments-due-to-the-error-permission-denied?language=en_US. It seems you have to create a new folder with the assigment folder name and then all the files will be updated.
