### ISSUE TITLE
Ability to skip a single video by request

### ISSUE THREAD

**Issue by floriankilian** [coursera-dl/coursera-dl#862]
### Subject of the issue
I want to download a course, and one of the videos is not downloadable (saw a comment in the forum there too)

### Your environment
* Operating System (name/version): Windows 11, Version 23H2 
* Python version: 3.9.6
* coursera-dl version: Newest from http://coursera-downloader.rf.gd/ (Download 30.1.24)

### Steps to reproduce
I try to download https://www.coursera.org/learn/data-analysis-and-visualization-with-power-bi/home/week/1
And on the lecture what-are-visualizations it stops, I retried to download it 3 times.
<img width="654" alt="image" src="https://github.com/coursera-dl/coursera-dl/assets/34104015/f49c4558-0f51-4aab-9902-8135d550735c">

### Expected behaviour
I would love to have an option to just skip that lecture, as of now I cannot download anything of that course bc of that one lecture.

**Comment by abomsco** [comment]
did you just install the coursera full course downloader or you started the process using commands from cmd normally

**Comment by floriankilian** [comment]
Hey!

I just downloaded the full course downloader and used the .exe / GUI.

**Comment by abomsco** [comment]
okay chat me up on telegram @Cruisebeats

**Comment by floriankilian** [comment]
Not sure, why I had an older version of coursera-dl.

This comment and updating it fixed it:

https://github.com/coursera-dl/coursera-dl/issues/854#issuecomment-1795342487
