### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by rbrito** [coursera-dl/coursera-dl#97]
This is copied from a previous comment of mine on an issue:

---

Regarding your question about `.netrc`, what exactly would you like to specify there? The download method? If yes, then, it would be possible in dirty ways (say, by specifying something like machine name as `coursera-dl-wget`), but that's the _wrong_ way of using `.netrc`: its purpose is to hold authentication data and that only. I would not accept contributions for that.

We may (and _that_ does make sense) use a configuration file to `coursera-dl` where we specify options for how we frequently want `coursera-dl` to be called.

Please file a new issue with a detailed explanation (perhaps cuting and pasting my rationale above) and I may work on that (or accept pull requests that implement that).

**Comment by FedericoCeratto** [comment]
I'm not sure if this is the right issue to report my question, anyways:
The use of .netrc is quite uncommon (it would get really bloated if many network-enabled applications started using it).
Would you consider using ~/.config/coursera-dl/settings (maybe .json or .yaml) as by http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html instead?

**Comment by dzhuang** [comment]
Please use the git version with the latest commit, create a file named ``coursera-dl.conf`` at where the script is about to be executed, to store the configurations (see the docs). I think it can now be closed. @balta2ar

**Comment by balta2ar** [comment]
Thanks. Available in version 0.9.0. Closing.

**Comment by IbraamYounan** [comment]
please, need sample for coursera-dl.conf with explnation for all obtions available .... help not clear, also i not able to use it however i put it beside script file.
  thanks

**Comment by Sadia360** [comment]
how to solve "Please provide a username with the -u option, or a .netrc file with the -n option.
